//go:build !cmd_go_bootstrap && cgo

package openssl

import (
	"runtime"
	"unsafe"

	"github.com/golang-fips/openssl/v2/internal/ossl"
)

// SupportsDSA returns true if the OpenSSL library supports DSA.
func SupportsDSA() bool {
	ctx, err := ossl.EVP_PKEY_CTX_new_id(ossl.EVP_PKEY_DSA, nil)
	if err != nil {
		return false
	}
	ossl.EVP_PKEY_CTX_free(ctx)
	return true
}

// DSAParameters contains the DSA parameters.
type DSAParameters struct {
	P, Q, G BigInt
}

// PrivateKeyDSA represents a DSA private key.
type PrivateKeyDSA struct {
	DSAParameters
	X, Y BigInt

	// _pkey MUST NOT be accessed directly. Instead, use the withKey method.
	_pkey ossl.EVP_PKEY_PTR
}

func (k *PrivateKeyDSA) finalize() {
	ossl.EVP_PKEY_free(k._pkey)
}

func (k *PrivateKeyDSA) withKey(f func(ossl.EVP_PKEY_PTR) error) error {
	defer runtime.KeepAlive(k)
	return f(k._pkey)
}

// PublicKeyDSA represents a DSA public key.
type PublicKeyDSA struct {
	DSAParameters
	Y BigInt

	// _pkey MUST NOT be accessed directly. Instead, use the withKey method.
	_pkey ossl.EVP_PKEY_PTR
}

func (k *PublicKeyDSA) finalize() {
	ossl.EVP_PKEY_free(k._pkey)
}

func (k *PublicKeyDSA) withKey(f func(ossl.EVP_PKEY_PTR) error) error {
	defer runtime.KeepAlive(k)
	return f(k._pkey)
}

// GenerateDSAParameters generates a set of DSA parameters.
func GenerateDSAParameters(l, n int) (DSAParameters, error) {
	// The DSA parameters are generated by creating a new DSA key and
	// extracting the domain parameters from it.

	// Generate a new DSA key context and set the known parameters.
	ctx, err := ossl.EVP_PKEY_CTX_new_id(ossl.EVP_PKEY_DSA, nil)
	if err != nil {
		return DSAParameters{}, err
	}
	defer ossl.EVP_PKEY_CTX_free(ctx)
	if err := ossl.EVP_PKEY_paramgen_init(ctx); err != nil {
		return DSAParameters{}, err
	}
	if err := ossl.EVP_PKEY_CTX_ctrl(ctx, ossl.EVP_PKEY_DSA, -1, ossl.EVP_PKEY_CTRL_DSA_PARAMGEN_BITS, int32(l), nil); err != nil {
		return DSAParameters{}, err
	}
	if err := ossl.EVP_PKEY_CTX_ctrl(ctx, ossl.EVP_PKEY_DSA, -1, ossl.EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS, int32(n), nil); err != nil {
		return DSAParameters{}, err
	}
	var pkey ossl.EVP_PKEY_PTR
	if err := ossl.EVP_PKEY_paramgen(ctx, &pkey); err != nil {
		return DSAParameters{}, err
	}
	defer ossl.EVP_PKEY_free(pkey)

	// Extract the domain parameters from the generated key.
	var p, q, g ossl.BIGNUM_PTR
	switch vMajor {
	case 1:
		dsa := getDSA(pkey)
		if vMinor == 0 {
			ossl.DSA_get0_pqg_backport(dsa, &p, &q, &g)
		} else {
			ossl.DSA_get0_pqg(dsa, &p, &q, &g)
		}
	case 3:
		defer func() {
			ossl.BN_free(p)
			ossl.BN_free(q)
			ossl.BN_free(g)
		}()
		if err := getBnParam(pkey, ossl.OSSL_PKEY_PARAM_FFC_P, &p); err != err {
			return DSAParameters{}, err
		}
		if err := getBnParam(pkey, ossl.OSSL_PKEY_PARAM_FFC_Q, &q); err != err {
			return DSAParameters{}, err
		}
		if err := getBnParam(pkey, ossl.OSSL_PKEY_PARAM_FFC_G, &g); err != err {
			return DSAParameters{}, err
		}
	default:
		panic(errUnsupportedVersion())
	}

	return DSAParameters{
		P: bnToBig(p),
		Q: bnToBig(q),
		G: bnToBig(g),
	}, nil
}

// NewPrivateKeyDSA creates a new DSA private key from the given parameters.
func NewPrivateKeyDSA(params DSAParameters, x, y BigInt) (*PrivateKeyDSA, error) {
	if x == nil || y == nil {
		panic("x and y must not be nil")
	}
	pkey, err := newDSA(params, x, y)
	if err != nil {
		return nil, err
	}
	k := &PrivateKeyDSA{params, x, y, pkey}
	runtime.SetFinalizer(k, (*PrivateKeyDSA).finalize)
	return k, nil
}

// NewPublicKeyDSA creates a new DSA public key from the given parameters.
func NewPublicKeyDSA(params DSAParameters, y BigInt) (*PublicKeyDSA, error) {
	if y == nil {
		panic("y must not be nil")
	}
	pkey, err := newDSA(params, nil, y)
	if err != nil {
		return nil, err
	}
	k := &PublicKeyDSA{params, y, pkey}
	runtime.SetFinalizer(k, (*PublicKeyDSA).finalize)
	return k, nil
}

// GenerateKeyDSA generates a new private DSA key using the given parameters.
func GenerateKeyDSA(params DSAParameters) (*PrivateKeyDSA, error) {
	pkey, err := newDSA(params, nil, nil)
	if err != nil {
		return nil, err
	}
	var x, y ossl.BIGNUM_PTR
	switch vMajor {
	case 1:
		dsa := getDSA(pkey)
		if vMinor == 0 {
			ossl.DSA_get0_key_backport(dsa, &y, &x)
		} else {
			ossl.DSA_get0_key(dsa, &y, &x)
		}
	case 3:
		defer func() {
			ossl.BN_clear_free(x)
			ossl.BN_free(y)
		}()
		if err := getBnParam(pkey, ossl.OSSL_PKEY_PARAM_PUB_KEY, &y); err != nil {
			return nil, err
		}
		if err := getBnParam(pkey, ossl.OSSL_PKEY_PARAM_PRIV_KEY, &x); err != nil {
			return nil, err
		}
	default:
		panic(errUnsupportedVersion())
	}
	k := &PrivateKeyDSA{params, bnToBig(x), bnToBig(y), pkey}
	runtime.SetFinalizer(k, (*PrivateKeyDSA).finalize)
	return k, nil
}

// SignDSA signs a hash (which should be the result of hashing a larger message).
func SignDSA(priv *PrivateKeyDSA, hash []byte) ([]byte, error) {
	return evpSign(priv.withKey, 0, 0, 0, hash)
}

// VerifyDSA verifiessig using the public key, pub.
func VerifyDSA(pub *PublicKeyDSA, hash []byte, sig []byte) bool {
	return evpVerify(pub.withKey, 0, 0, 0, sig, hash) == nil
}

func newDSA(params DSAParameters, x, y BigInt) (ossl.EVP_PKEY_PTR, error) {
	switch vMajor {
	case 1:
		return newDSA1(params, x, y)
	case 3:
		return newDSA3(params, x, y)
	default:
		panic(errUnsupportedVersion())
	}
}

func newDSA1(params DSAParameters, x, y BigInt) (pkey ossl.EVP_PKEY_PTR, _ error) {
	checkMajorVersion(1)

	dsa, err := ossl.DSA_new()
	if err != nil {
		return nil, err
	}
	defer func() {
		if pkey == nil {
			ossl.DSA_free(dsa)
		}
	}()

	p, q, g := bigToBN(params.P), bigToBN(params.Q), bigToBN(params.G)
	if vMinor == 0 {
		err = ossl.DSA_set0_pqg_backport(dsa, p, q, g)
	} else {
		err = ossl.DSA_set0_pqg(dsa, p, q, g)
	}
	if err != nil {
		ossl.BN_free(p)
		ossl.BN_free(q)
		ossl.BN_free(g)
		return nil, err
	}
	if y != nil {
		pub, priv := bigToBN(y), bigToBN(x)
		if vMinor == 0 {
			err = ossl.DSA_set0_key_backport(dsa, pub, priv)
		} else {
			err = ossl.DSA_set0_key(dsa, pub, priv)
		}
		if err != nil {
			ossl.BN_free(pub)
			ossl.BN_clear_free(priv)
			return nil, err
		}
	} else {
		if err := ossl.DSA_generate_key(dsa); err != nil {
			return nil, err
		}
	}
	pkey, err = ossl.EVP_PKEY_new()
	if err != nil {
		return nil, err
	}
	if err := ossl.EVP_PKEY_assign(pkey, ossl.EVP_PKEY_DSA, unsafe.Pointer(dsa)); err != nil {
		ossl.EVP_PKEY_free(pkey)
		return nil, err
	}
	return pkey, nil
}

func newDSA3(params DSAParameters, x, y BigInt) (ossl.EVP_PKEY_PTR, error) {
	checkMajorVersion(3)

	bld, err := newParamBuilder()
	if err != nil {
		return nil, err
	}
	defer bld.finalize()

	bld.addBigInt(ossl.OSSL_PKEY_PARAM_FFC_P, params.P, false)
	bld.addBigInt(ossl.OSSL_PKEY_PARAM_FFC_Q, params.Q, false)
	bld.addBigInt(ossl.OSSL_PKEY_PARAM_FFC_G, params.G, false)
	selection := ossl.EVP_PKEY_KEYPAIR
	if y != nil {
		bld.addBigInt(ossl.OSSL_PKEY_PARAM_PUB_KEY, y, false)
		if x == nil {
			selection = ossl.EVP_PKEY_PUBLIC_KEY
		}
	}
	if x != nil {
		bld.addBigInt(ossl.OSSL_PKEY_PARAM_PRIV_KEY, x, true)
	}
	bldparams, err := bld.build()
	if err != nil {
		return nil, err
	}
	defer ossl.OSSL_PARAM_free(bldparams)
	pkey, err := newEvpFromParams(ossl.EVP_PKEY_DSA, selection, bldparams)
	if err != nil {
		return nil, err
	}
	if y != nil {
		return pkey, nil
	}
	// pkey doesn't contain the public component, but the crypto/dsa package
	// expects it to be always there. Generate a new key using pkey as domain
	// parameters placeholder.
	defer ossl.EVP_PKEY_free(pkey)
	ctx, err := ossl.EVP_PKEY_CTX_new_from_pkey(nil, pkey, nil)
	if err != nil {
		return nil, err
	}
	defer ossl.EVP_PKEY_CTX_free(ctx)
	if err := ossl.EVP_PKEY_keygen_init(ctx); err != nil {
		return nil, err
	}
	var gkey ossl.EVP_PKEY_PTR
	if err := ossl.EVP_PKEY_keygen(ctx, &gkey); err != nil {
		return nil, err
	}
	return gkey, nil
}

// getDSA returns the DSA from pkey.
// If pkey does not contain an DSA it panics.
// The returned key should not be freed.
func getDSA(pkey ossl.EVP_PKEY_PTR) (key ossl.DSA_PTR) {
	if vMajor == 1 && vMinor == 0 {
		if key0, err := ossl.EVP_PKEY_get0(pkey); err == nil {
			key = ossl.DSA_PTR(key0)
		}
	} else {
		key, _ = ossl.EVP_PKEY_get0_DSA(pkey)
	}
	if key == nil {
		panic("pkey does not contain an DSA")
	}
	return key
}
