// Code generated by mkcgo. DO NOT EDIT.

#include "shims.h"
#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>

#ifdef _WIN32
#include <windows.h>
#define dlsym GetProcAddress
#else
#include <dlfcn.h>
#endif

_BIGNUM_PTR (*_g_BN_bin2bn)(const unsigned char*, int, _BIGNUM_PTR);
int (*_g_BN_bn2binpad)(const _BIGNUM_PTR, unsigned char*, int);
int (*_g_BN_bn2lebinpad)(const _BIGNUM_PTR, unsigned char*, int);
void (*_g_BN_clear)(_BIGNUM_PTR);
void (*_g_BN_clear_free)(_BIGNUM_PTR);
void (*_g_BN_free)(_BIGNUM_PTR);
_BIGNUM_PTR (*_g_BN_lebin2bn)(const unsigned char*, int, _BIGNUM_PTR);
_BIGNUM_PTR (*_g_BN_new)(void);
int (*_g_BN_num_bits)(const _BIGNUM_PTR);
void (*_g_CRYPTO_free)(void*, const char*, int);
void* (*_g_CRYPTO_malloc)(size_t, const char*, int);
void (*_g_DSA_free)(_DSA_PTR);
int (*_g_DSA_generate_key)(_DSA_PTR);
void (*_g_DSA_get0_key)(const _DSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void (*_g_DSA_get0_pqg)(const _DSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
_DSA_PTR (*_g_DSA_new)(void);
int (*_g_DSA_set0_key)(_DSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
int (*_g_DSA_set0_pqg)(_DSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
void (*_g_EC_GROUP_free)(_EC_GROUP_PTR);
_EC_GROUP_PTR (*_g_EC_GROUP_new_by_curve_name)(int);
int (*_g_EC_KEY_check_key)(const _EC_KEY_PTR);
void (*_g_EC_KEY_free)(_EC_KEY_PTR);
const _EC_GROUP_PTR (*_g_EC_KEY_get0_group)(const _EC_KEY_PTR);
const _BIGNUM_PTR (*_g_EC_KEY_get0_private_key)(const _EC_KEY_PTR);
const _EC_POINT_PTR (*_g_EC_KEY_get0_public_key)(const _EC_KEY_PTR);
_EC_KEY_PTR (*_g_EC_KEY_new_by_curve_name)(int);
int (*_g_EC_KEY_set_private_key)(_EC_KEY_PTR, const _BIGNUM_PTR);
int (*_g_EC_KEY_set_public_key)(_EC_KEY_PTR, const _EC_POINT_PTR);
int (*_g_EC_KEY_set_public_key_affine_coordinates)(_EC_KEY_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
void (*_g_EC_POINT_free)(_EC_POINT_PTR);
int (*_g_EC_POINT_get_affine_coordinates_GFp)(const _EC_GROUP_PTR, const _EC_POINT_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BN_CTX_PTR);
int (*_g_EC_POINT_mul)(const _EC_GROUP_PTR, _EC_POINT_PTR, const _BIGNUM_PTR, const _EC_POINT_PTR, const _BIGNUM_PTR, _BN_CTX_PTR);
_EC_POINT_PTR (*_g_EC_POINT_new)(const _EC_GROUP_PTR);
int (*_g_EC_POINT_oct2point)(const _EC_GROUP_PTR, _EC_POINT_PTR, const unsigned char*, size_t, _BN_CTX_PTR);
size_t (*_g_EC_POINT_point2oct)(const _EC_GROUP_PTR, const _EC_POINT_PTR, point_conversion_form_t, unsigned char*, size_t, _BN_CTX_PTR);
int (*_g_EC_POINT_set_affine_coordinates)(const _EC_GROUP_PTR, _EC_POINT_PTR, const _BIGNUM_PTR, const _BIGNUM_PTR, _BN_CTX_PTR);
void (*_g_ERR_clear_error)(void);
void (*_g_ERR_error_string_n)(unsigned long, char*, size_t);
unsigned long (*_g_ERR_get_error_all)(const char**, int*, const char**, const char**, int*);
unsigned long (*_g_ERR_get_error_line)(const char**, int*);
int (*_g_EVP_CIPHER_CTX_ctrl)(_EVP_CIPHER_CTX_PTR, int, int, void*);
void (*_g_EVP_CIPHER_CTX_free)(_EVP_CIPHER_CTX_PTR);
_EVP_CIPHER_CTX_PTR (*_g_EVP_CIPHER_CTX_new)(void);
int (*_g_EVP_CIPHER_CTX_set_key_length)(_EVP_CIPHER_CTX_PTR, int);
int (*_g_EVP_CIPHER_CTX_set_padding)(_EVP_CIPHER_CTX_PTR, int);
int (*_g_EVP_CIPHER_block_size)(const _EVP_CIPHER_PTR);
_EVP_CIPHER_PTR (*_g_EVP_CIPHER_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
const char* (*_g_EVP_CIPHER_get0_name)(const _EVP_CIPHER_PTR);
int (*_g_EVP_CIPHER_get_block_size)(const _EVP_CIPHER_PTR);
int (*_g_EVP_CipherInit_ex)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*, int);
int (*_g_EVP_CipherUpdate)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
int (*_g_EVP_DecryptFinal_ex)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*);
int (*_g_EVP_DecryptInit_ex)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*);
int (*_g_EVP_DecryptUpdate)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
int (*_g_EVP_Digest)(const void*, size_t, unsigned char*, unsigned int*, const _EVP_MD_PTR, _ENGINE_PTR);
int (*_g_EVP_DigestFinal_ex)(_EVP_MD_CTX_PTR, unsigned char*, unsigned int*);
int (*_g_EVP_DigestInit)(_EVP_MD_CTX_PTR, const _EVP_MD_PTR);
int (*_g_EVP_DigestInit_ex)(_EVP_MD_CTX_PTR, const _EVP_MD_PTR, _ENGINE_PTR);
int (*_g_EVP_DigestSign)(_EVP_MD_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_DigestSignFinal)(_EVP_MD_CTX_PTR, unsigned char*, size_t*);
int (*_g_EVP_DigestSignInit)(_EVP_MD_CTX_PTR, _EVP_PKEY_CTX_PTR*, const _EVP_MD_PTR, _ENGINE_PTR, _EVP_PKEY_PTR);
int (*_g_EVP_DigestUpdate)(_EVP_MD_CTX_PTR, const void*, size_t);
int (*_g_EVP_DigestVerify)(_EVP_MD_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t);
int (*_g_EVP_DigestVerifyFinal)(_EVP_MD_CTX_PTR, const unsigned char*, size_t);
int (*_g_EVP_DigestVerifyInit)(_EVP_MD_CTX_PTR, _EVP_PKEY_CTX_PTR*, const _EVP_MD_PTR, _ENGINE_PTR, _EVP_PKEY_PTR);
int (*_g_EVP_EncryptFinal_ex)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*);
int (*_g_EVP_EncryptInit_ex)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*);
int (*_g_EVP_EncryptUpdate)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
void (*_g_EVP_KDF_CTX_free)(_EVP_KDF_CTX_PTR);
size_t (*_g_EVP_KDF_CTX_get_kdf_size)(_EVP_KDF_CTX_PTR);
_EVP_KDF_CTX_PTR (*_g_EVP_KDF_CTX_new)(_EVP_KDF_PTR);
int (*_g_EVP_KDF_CTX_set_params)(_EVP_KDF_CTX_PTR, const _OSSL_PARAM_PTR);
int (*_g_EVP_KDF_derive)(_EVP_KDF_CTX_PTR, unsigned char*, size_t, const _OSSL_PARAM_PTR);
_EVP_KDF_PTR (*_g_EVP_KDF_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_KDF_free)(_EVP_KDF_PTR);
_EVP_MAC_CTX_PTR (*_g_EVP_MAC_CTX_dup)(const _EVP_MAC_CTX_PTR);
void (*_g_EVP_MAC_CTX_free)(_EVP_MAC_CTX_PTR);
_EVP_MAC_CTX_PTR (*_g_EVP_MAC_CTX_new)(_EVP_MAC_PTR);
int (*_g_EVP_MAC_CTX_set_params)(_EVP_MAC_CTX_PTR, const _OSSL_PARAM_PTR);
_EVP_MAC_PTR (*_g_EVP_MAC_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
int (*_g_EVP_MAC_final)(_EVP_MAC_CTX_PTR, unsigned char*, size_t*, size_t);
int (*_g_EVP_MAC_init)(_EVP_MAC_CTX_PTR, const unsigned char*, size_t, const _OSSL_PARAM_PTR);
int (*_g_EVP_MAC_update)(_EVP_MAC_CTX_PTR, const unsigned char*, size_t);
int (*_g_EVP_MD_CTX_copy)(_EVP_MD_CTX_PTR, const _EVP_MD_CTX_PTR);
int (*_g_EVP_MD_CTX_copy_ex)(_EVP_MD_CTX_PTR, const _EVP_MD_CTX_PTR);
void (*_g_EVP_MD_CTX_free)(_EVP_MD_CTX_PTR);
_EVP_MD_CTX_PTR (*_g_EVP_MD_CTX_new)(void);
int (*_g_EVP_MD_block_size)(const _EVP_MD_PTR);
_EVP_MD_PTR (*_g_EVP_MD_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_MD_free)(_EVP_MD_PTR);
const char* (*_g_EVP_MD_get0_name)(const _EVP_MD_PTR);
const _OSSL_PROVIDER_PTR (*_g_EVP_MD_get0_provider)(const _EVP_MD_PTR);
int (*_g_EVP_MD_get_block_size)(const _EVP_MD_PTR);
int (*_g_EVP_MD_get_size)(const _EVP_MD_PTR);
int (*_g_EVP_MD_get_type)(const _EVP_MD_PTR);
int (*_g_EVP_MD_size)(const _EVP_MD_PTR);
int (*_g_EVP_PKEY_CTX_add1_hkdf_info)(_EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_ctrl)(_EVP_PKEY_CTX_PTR, int, int, int, int, void*);
void (*_g_EVP_PKEY_CTX_free)(_EVP_PKEY_CTX_PTR);
_EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new)(_EVP_PKEY_PTR, _ENGINE_PTR);
_EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new_from_pkey)(_OSSL_LIB_CTX_PTR, _EVP_PKEY_PTR, const char*);
_EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new_id)(int, _ENGINE_PTR);
int (*_g_EVP_PKEY_CTX_set0_rsa_oaep_label)(_EVP_PKEY_CTX_PTR, void*, int);
int (*_g_EVP_PKEY_CTX_set1_hkdf_key)(_EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_set1_hkdf_salt)(_EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_set_hkdf_md)(_EVP_PKEY_CTX_PTR, const _EVP_MD_PTR);
int (*_g_EVP_PKEY_CTX_set_hkdf_mode)(_EVP_PKEY_CTX_PTR, int);
_EVP_PKEY_PTR (*_g_EVP_PKEY_Q_keygen)(_OSSL_LIB_CTX_PTR, const char*, const char*);
_EVP_PKEY_PTR (*_g_EVP_PKEY_Q_keygen_EC)(_OSSL_LIB_CTX_PTR, const char*, const char*, const char*);
_EVP_PKEY_PTR (*_g_EVP_PKEY_Q_keygen_RSA)(_OSSL_LIB_CTX_PTR, const char*, const char*, size_t);
int (*_g_EVP_PKEY_assign)(_EVP_PKEY_PTR, int, void*);
int (*_g_EVP_PKEY_bits)(const _EVP_PKEY_PTR);
int (*_g_EVP_PKEY_decrypt)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_decrypt_init)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_derive)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_derive_init)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_derive_set_peer)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR);
int (*_g_EVP_PKEY_encrypt)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_encrypt_init)(_EVP_PKEY_CTX_PTR);
void (*_g_EVP_PKEY_free)(_EVP_PKEY_PTR);
int (*_g_EVP_PKEY_fromdata)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*, int, _OSSL_PARAM_PTR);
int (*_g_EVP_PKEY_fromdata_init)(_EVP_PKEY_CTX_PTR);
_DSA_PTR (*_g_EVP_PKEY_get0_DSA)(_EVP_PKEY_PTR);
_EC_KEY_PTR (*_g_EVP_PKEY_get0_EC_KEY)(_EVP_PKEY_PTR);
_RSA_PTR (*_g_EVP_PKEY_get1_RSA)(_EVP_PKEY_PTR);
size_t (*_g_EVP_PKEY_get1_encoded_public_key)(_EVP_PKEY_PTR, unsigned char**);
int (*_g_EVP_PKEY_get_bits)(const _EVP_PKEY_PTR);
int (*_g_EVP_PKEY_get_bn_param)(const _EVP_PKEY_PTR, const char*, _BIGNUM_PTR*);
int (*_g_EVP_PKEY_get_raw_private_key)(const _EVP_PKEY_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_get_raw_public_key)(const _EVP_PKEY_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_get_size)(const _EVP_PKEY_PTR);
int (*_g_EVP_PKEY_keygen)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*);
int (*_g_EVP_PKEY_keygen_init)(_EVP_PKEY_CTX_PTR);
_EVP_PKEY_PTR (*_g_EVP_PKEY_new)(void);
_EVP_PKEY_PTR (*_g_EVP_PKEY_new_raw_private_key)(int, _ENGINE_PTR, const unsigned char*, size_t);
_EVP_PKEY_PTR (*_g_EVP_PKEY_new_raw_public_key)(int, _ENGINE_PTR, const unsigned char*, size_t);
int (*_g_EVP_PKEY_paramgen)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*);
int (*_g_EVP_PKEY_paramgen_init)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_private_check)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_public_check_quick)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_set1_EC_KEY)(_EVP_PKEY_PTR, _EC_KEY_PTR);
int (*_g_EVP_PKEY_set1_encoded_public_key)(_EVP_PKEY_PTR, const unsigned char*, size_t);
int (*_g_EVP_PKEY_sign)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_sign_init)(_EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_size)(const _EVP_PKEY_PTR);
int (*_g_EVP_PKEY_up_ref)(_EVP_PKEY_PTR);
int (*_g_EVP_PKEY_verify)(_EVP_PKEY_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t);
int (*_g_EVP_PKEY_verify_init)(_EVP_PKEY_CTX_PTR);
_EVP_SIGNATURE_PTR (*_g_EVP_SIGNATURE_fetch)(_OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_SIGNATURE_free)(_EVP_SIGNATURE_PTR);
const _EVP_CIPHER_PTR (*_g_EVP_aes_128_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_128_ctr)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_128_ecb)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_128_gcm)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_192_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_192_ctr)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_192_ecb)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_192_gcm)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_256_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_256_ctr)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_256_ecb)(void);
const _EVP_CIPHER_PTR (*_g_EVP_aes_256_gcm)(void);
int (*_g_EVP_default_properties_enable_fips)(_OSSL_LIB_CTX_PTR, int);
int (*_g_EVP_default_properties_is_fips_enabled)(_OSSL_LIB_CTX_PTR);
const _EVP_CIPHER_PTR (*_g_EVP_des_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_des_ecb)(void);
const _EVP_CIPHER_PTR (*_g_EVP_des_ede3_cbc)(void);
const _EVP_CIPHER_PTR (*_g_EVP_des_ede3_ecb)(void);
const _EVP_MD_PTR (*_g_EVP_md4)(void);
const _EVP_MD_PTR (*_g_EVP_md5)(void);
const _EVP_MD_PTR (*_g_EVP_md5_sha1)(void);
const _EVP_CIPHER_PTR (*_g_EVP_rc4)(void);
const _EVP_MD_PTR (*_g_EVP_ripemd160)(void);
const _EVP_MD_PTR (*_g_EVP_sha1)(void);
const _EVP_MD_PTR (*_g_EVP_sha224)(void);
const _EVP_MD_PTR (*_g_EVP_sha256)(void);
const _EVP_MD_PTR (*_g_EVP_sha384)(void);
const _EVP_MD_PTR (*_g_EVP_sha3_224)(void);
const _EVP_MD_PTR (*_g_EVP_sha3_256)(void);
const _EVP_MD_PTR (*_g_EVP_sha3_384)(void);
const _EVP_MD_PTR (*_g_EVP_sha3_512)(void);
const _EVP_MD_PTR (*_g_EVP_sha512)(void);
const _EVP_MD_PTR (*_g_EVP_sha512_224)(void);
const _EVP_MD_PTR (*_g_EVP_sha512_256)(void);
int (*_g_FIPS_mode)(void);
int (*_g_FIPS_mode_set)(int);
int (*_g_HMAC_CTX_copy)(_HMAC_CTX_PTR, _HMAC_CTX_PTR);
void (*_g_HMAC_CTX_free)(_HMAC_CTX_PTR);
_HMAC_CTX_PTR (*_g_HMAC_CTX_new)(void);
int (*_g_HMAC_Final)(_HMAC_CTX_PTR, unsigned char*, unsigned int*);
int (*_g_HMAC_Init_ex)(_HMAC_CTX_PTR, const void*, int, const _EVP_MD_PTR, _ENGINE_PTR);
int (*_g_HMAC_Update)(_HMAC_CTX_PTR, const unsigned char*, size_t);
const char* (*_g_OBJ_nid2sn)(int);
void (*_g_OPENSSL_init)(void);
int (*_g_OPENSSL_init_crypto)(uint64_t, const _OPENSSL_INIT_SETTINGS_PTR);
void (*_g_OSSL_PARAM_BLD_free)(_OSSL_PARAM_BLD_PTR);
_OSSL_PARAM_BLD_PTR (*_g_OSSL_PARAM_BLD_new)(void);
int (*_g_OSSL_PARAM_BLD_push_BN)(_OSSL_PARAM_BLD_PTR, const char*, const _BIGNUM_PTR);
int (*_g_OSSL_PARAM_BLD_push_int32)(_OSSL_PARAM_BLD_PTR, const char*, int32_t);
int (*_g_OSSL_PARAM_BLD_push_octet_string)(_OSSL_PARAM_BLD_PTR, const char*, const void*, size_t);
int (*_g_OSSL_PARAM_BLD_push_utf8_string)(_OSSL_PARAM_BLD_PTR, const char*, const char*, size_t);
_OSSL_PARAM_PTR (*_g_OSSL_PARAM_BLD_to_param)(_OSSL_PARAM_BLD_PTR);
void (*_g_OSSL_PARAM_free)(_OSSL_PARAM_PTR);
int (*_g_OSSL_PROVIDER_available)(_OSSL_LIB_CTX_PTR, const char*);
const char* (*_g_OSSL_PROVIDER_get0_name)(const _OSSL_PROVIDER_PTR);
_OSSL_PROVIDER_PTR (*_g_OSSL_PROVIDER_try_load)(_OSSL_LIB_CTX_PTR, const char*, int);
const char* (*_g_OpenSSL_version)(int);
int (*_g_PKCS5_PBKDF2_HMAC)(const char*, int, const unsigned char*, int, int, const _EVP_MD_PTR, int, unsigned char*);
int (*_g_RAND_bytes)(unsigned char*, int);
void (*_g_RSA_free)(_RSA_PTR);
void (*_g_RSA_get0_crt_params)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void (*_g_RSA_get0_factors)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
void (*_g_RSA_get0_key)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*);
_RSA_PTR (*_g_RSA_new)(void);
int (*_g_RSA_set0_crt_params)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
int (*_g_RSA_set0_factors)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR);
int (*_g_RSA_set0_key)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR);

void __mkcgoLoad_(void* handle) {
	_g_BN_bin2bn = (_BIGNUM_PTR (*)(const unsigned char*, int, _BIGNUM_PTR))dlsym(handle, "BN_bin2bn");
	_g_BN_bn2binpad = (int (*)(const _BIGNUM_PTR, unsigned char*, int))dlsym(handle, "BN_bn2binpad");
	_g_BN_bn2lebinpad = (int (*)(const _BIGNUM_PTR, unsigned char*, int))dlsym(handle, "BN_bn2lebinpad");
	_g_BN_clear = (void (*)(_BIGNUM_PTR))dlsym(handle, "BN_clear");
	_g_BN_clear_free = (void (*)(_BIGNUM_PTR))dlsym(handle, "BN_clear_free");
	_g_BN_free = (void (*)(_BIGNUM_PTR))dlsym(handle, "BN_free");
	_g_BN_lebin2bn = (_BIGNUM_PTR (*)(const unsigned char*, int, _BIGNUM_PTR))dlsym(handle, "BN_lebin2bn");
	_g_BN_new = (_BIGNUM_PTR (*)(void))dlsym(handle, "BN_new");
	_g_BN_num_bits = (int (*)(const _BIGNUM_PTR))dlsym(handle, "BN_num_bits");
	_g_CRYPTO_free = (void (*)(void*, const char*, int))dlsym(handle, "CRYPTO_free");
	_g_CRYPTO_malloc = (void* (*)(size_t, const char*, int))dlsym(handle, "CRYPTO_malloc");
	_g_EC_GROUP_free = (void (*)(_EC_GROUP_PTR))dlsym(handle, "EC_GROUP_free");
	_g_EC_GROUP_new_by_curve_name = (_EC_GROUP_PTR (*)(int))dlsym(handle, "EC_GROUP_new_by_curve_name");
	_g_EC_POINT_free = (void (*)(_EC_POINT_PTR))dlsym(handle, "EC_POINT_free");
	_g_EC_POINT_mul = (int (*)(const _EC_GROUP_PTR, _EC_POINT_PTR, const _BIGNUM_PTR, const _EC_POINT_PTR, const _BIGNUM_PTR, _BN_CTX_PTR))dlsym(handle, "EC_POINT_mul");
	_g_EC_POINT_new = (_EC_POINT_PTR (*)(const _EC_GROUP_PTR))dlsym(handle, "EC_POINT_new");
	_g_EC_POINT_oct2point = (int (*)(const _EC_GROUP_PTR, _EC_POINT_PTR, const unsigned char*, size_t, _BN_CTX_PTR))dlsym(handle, "EC_POINT_oct2point");
	_g_EC_POINT_point2oct = (size_t (*)(const _EC_GROUP_PTR, const _EC_POINT_PTR, point_conversion_form_t, unsigned char*, size_t, _BN_CTX_PTR))dlsym(handle, "EC_POINT_point2oct");
	_g_ERR_clear_error = (void (*)(void))dlsym(handle, "ERR_clear_error");
	_g_ERR_error_string_n = (void (*)(unsigned long, char*, size_t))dlsym(handle, "ERR_error_string_n");
	_g_EVP_CIPHER_CTX_ctrl = (int (*)(_EVP_CIPHER_CTX_PTR, int, int, void*))dlsym(handle, "EVP_CIPHER_CTX_ctrl");
	_g_EVP_CIPHER_CTX_free = (void (*)(_EVP_CIPHER_CTX_PTR))dlsym(handle, "EVP_CIPHER_CTX_free");
	_g_EVP_CIPHER_CTX_new = (_EVP_CIPHER_CTX_PTR (*)(void))dlsym(handle, "EVP_CIPHER_CTX_new");
	_g_EVP_CIPHER_CTX_set_key_length = (int (*)(_EVP_CIPHER_CTX_PTR, int))dlsym(handle, "EVP_CIPHER_CTX_set_key_length");
	_g_EVP_CIPHER_CTX_set_padding = (int (*)(_EVP_CIPHER_CTX_PTR, int))dlsym(handle, "EVP_CIPHER_CTX_set_padding");
	_g_EVP_CipherInit_ex = (int (*)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*, int))dlsym(handle, "EVP_CipherInit_ex");
	_g_EVP_CipherUpdate = (int (*)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int))dlsym(handle, "EVP_CipherUpdate");
	_g_EVP_DecryptFinal_ex = (int (*)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*))dlsym(handle, "EVP_DecryptFinal_ex");
	_g_EVP_DecryptInit_ex = (int (*)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*))dlsym(handle, "EVP_DecryptInit_ex");
	_g_EVP_DecryptUpdate = (int (*)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int))dlsym(handle, "EVP_DecryptUpdate");
	_g_EVP_Digest = (int (*)(const void*, size_t, unsigned char*, unsigned int*, const _EVP_MD_PTR, _ENGINE_PTR))dlsym(handle, "EVP_Digest");
	_g_EVP_DigestFinal_ex = (int (*)(_EVP_MD_CTX_PTR, unsigned char*, unsigned int*))dlsym(handle, "EVP_DigestFinal_ex");
	_g_EVP_DigestInit = (int (*)(_EVP_MD_CTX_PTR, const _EVP_MD_PTR))dlsym(handle, "EVP_DigestInit");
	_g_EVP_DigestInit_ex = (int (*)(_EVP_MD_CTX_PTR, const _EVP_MD_PTR, _ENGINE_PTR))dlsym(handle, "EVP_DigestInit_ex");
	_g_EVP_DigestSignFinal = (int (*)(_EVP_MD_CTX_PTR, unsigned char*, size_t*))dlsym(handle, "EVP_DigestSignFinal");
	_g_EVP_DigestSignInit = (int (*)(_EVP_MD_CTX_PTR, _EVP_PKEY_CTX_PTR*, const _EVP_MD_PTR, _ENGINE_PTR, _EVP_PKEY_PTR))dlsym(handle, "EVP_DigestSignInit");
	_g_EVP_DigestUpdate = (int (*)(_EVP_MD_CTX_PTR, const void*, size_t))dlsym(handle, "EVP_DigestUpdate");
	_g_EVP_DigestVerifyFinal = (int (*)(_EVP_MD_CTX_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_DigestVerifyFinal");
	_g_EVP_DigestVerifyInit = (int (*)(_EVP_MD_CTX_PTR, _EVP_PKEY_CTX_PTR*, const _EVP_MD_PTR, _ENGINE_PTR, _EVP_PKEY_PTR))dlsym(handle, "EVP_DigestVerifyInit");
	_g_EVP_EncryptFinal_ex = (int (*)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*))dlsym(handle, "EVP_EncryptFinal_ex");
	_g_EVP_EncryptInit_ex = (int (*)(_EVP_CIPHER_CTX_PTR, const _EVP_CIPHER_PTR, _ENGINE_PTR, const unsigned char*, const unsigned char*))dlsym(handle, "EVP_EncryptInit_ex");
	_g_EVP_EncryptUpdate = (int (*)(_EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int))dlsym(handle, "EVP_EncryptUpdate");
	_g_EVP_MD_CTX_copy = (int (*)(_EVP_MD_CTX_PTR, const _EVP_MD_CTX_PTR))dlsym(handle, "EVP_MD_CTX_copy");
	_g_EVP_MD_CTX_copy_ex = (int (*)(_EVP_MD_CTX_PTR, const _EVP_MD_CTX_PTR))dlsym(handle, "EVP_MD_CTX_copy_ex");
	_g_EVP_MD_CTX_free = (void (*)(_EVP_MD_CTX_PTR))dlsym(handle, "EVP_MD_CTX_free");
	_g_EVP_MD_CTX_new = (_EVP_MD_CTX_PTR (*)(void))dlsym(handle, "EVP_MD_CTX_new");
	_g_EVP_PKEY_CTX_ctrl = (int (*)(_EVP_PKEY_CTX_PTR, int, int, int, int, void*))dlsym(handle, "EVP_PKEY_CTX_ctrl");
	_g_EVP_PKEY_CTX_free = (void (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_CTX_free");
	_g_EVP_PKEY_CTX_new = (_EVP_PKEY_CTX_PTR (*)(_EVP_PKEY_PTR, _ENGINE_PTR))dlsym(handle, "EVP_PKEY_CTX_new");
	_g_EVP_PKEY_CTX_new_id = (_EVP_PKEY_CTX_PTR (*)(int, _ENGINE_PTR))dlsym(handle, "EVP_PKEY_CTX_new_id");
	_g_EVP_PKEY_decrypt = (int (*)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_decrypt");
	_g_EVP_PKEY_decrypt_init = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_decrypt_init");
	_g_EVP_PKEY_derive = (int (*)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*))dlsym(handle, "EVP_PKEY_derive");
	_g_EVP_PKEY_derive_init = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_derive_init");
	_g_EVP_PKEY_derive_set_peer = (int (*)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_derive_set_peer");
	_g_EVP_PKEY_encrypt = (int (*)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_encrypt");
	_g_EVP_PKEY_encrypt_init = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_encrypt_init");
	_g_EVP_PKEY_free = (void (*)(_EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_free");
	_g_EVP_PKEY_keygen = (int (*)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*))dlsym(handle, "EVP_PKEY_keygen");
	_g_EVP_PKEY_keygen_init = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_keygen_init");
	_g_EVP_PKEY_new = (_EVP_PKEY_PTR (*)(void))dlsym(handle, "EVP_PKEY_new");
	_g_EVP_PKEY_paramgen = (int (*)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*))dlsym(handle, "EVP_PKEY_paramgen");
	_g_EVP_PKEY_paramgen_init = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_paramgen_init");
	_g_EVP_PKEY_sign = (int (*)(_EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_sign");
	_g_EVP_PKEY_sign_init = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_sign_init");
	_g_EVP_PKEY_verify = (int (*)(_EVP_PKEY_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_verify");
	_g_EVP_PKEY_verify_init = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_verify_init");
	_g_EVP_aes_128_cbc = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_128_cbc");
	_g_EVP_aes_128_ctr = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_128_ctr");
	_g_EVP_aes_128_ecb = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_128_ecb");
	_g_EVP_aes_128_gcm = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_128_gcm");
	_g_EVP_aes_192_cbc = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_192_cbc");
	_g_EVP_aes_192_ctr = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_192_ctr");
	_g_EVP_aes_192_ecb = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_192_ecb");
	_g_EVP_aes_192_gcm = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_192_gcm");
	_g_EVP_aes_256_cbc = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_256_cbc");
	_g_EVP_aes_256_ctr = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_256_ctr");
	_g_EVP_aes_256_ecb = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_256_ecb");
	_g_EVP_aes_256_gcm = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_256_gcm");
	_g_EVP_des_cbc = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_des_cbc");
	_g_EVP_des_ecb = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_des_ecb");
	_g_EVP_des_ede3_cbc = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_des_ede3_cbc");
	_g_EVP_des_ede3_ecb = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_des_ede3_ecb");
	_g_EVP_md4 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_md4");
	_g_EVP_md5 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_md5");
	_g_EVP_md5_sha1 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_md5_sha1");
	_g_EVP_rc4 = (const _EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_rc4");
	_g_EVP_ripemd160 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_ripemd160");
	_g_EVP_sha1 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha1");
	_g_EVP_sha224 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha224");
	_g_EVP_sha256 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha256");
	_g_EVP_sha384 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha384");
	_g_EVP_sha512 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha512");
	_g_OBJ_nid2sn = (const char* (*)(int))dlsym(handle, "OBJ_nid2sn");
	_g_OPENSSL_init = (void (*)(void))dlsym(handle, "OPENSSL_init");
	_g_OPENSSL_init_crypto = (int (*)(uint64_t, const _OPENSSL_INIT_SETTINGS_PTR))dlsym(handle, "OPENSSL_init_crypto");
	_g_OpenSSL_version = (const char* (*)(int))dlsym(handle, "OpenSSL_version");
	_g_PKCS5_PBKDF2_HMAC = (int (*)(const char*, int, const unsigned char*, int, int, const _EVP_MD_PTR, int, unsigned char*))dlsym(handle, "PKCS5_PBKDF2_HMAC");
	_g_RAND_bytes = (int (*)(unsigned char*, int))dlsym(handle, "RAND_bytes");
}

void __mkcgoLoad_111(void* handle) {
	_g_EVP_DigestSign = (int (*)(_EVP_MD_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t))dlsym(handle, "EVP_DigestSign");
	_g_EVP_DigestVerify = (int (*)(_EVP_MD_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t))dlsym(handle, "EVP_DigestVerify");
	_g_EVP_PKEY_get_raw_private_key = (int (*)(const _EVP_PKEY_PTR, unsigned char*, size_t*))dlsym(handle, "EVP_PKEY_get_raw_private_key");
	_g_EVP_PKEY_get_raw_public_key = (int (*)(const _EVP_PKEY_PTR, unsigned char*, size_t*))dlsym(handle, "EVP_PKEY_get_raw_public_key");
	_g_EVP_PKEY_new_raw_private_key = (_EVP_PKEY_PTR (*)(int, _ENGINE_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_new_raw_private_key");
	_g_EVP_PKEY_new_raw_public_key = (_EVP_PKEY_PTR (*)(int, _ENGINE_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_new_raw_public_key");
	_g_EVP_sha3_224 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha3_224");
	_g_EVP_sha3_256 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha3_256");
	_g_EVP_sha3_384 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha3_384");
	_g_EVP_sha3_512 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha3_512");
	_g_EVP_sha512_224 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha512_224");
	_g_EVP_sha512_256 = (const _EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha512_256");
}

void __mkcgoLoad_3(void* handle) {
	_g_EC_POINT_set_affine_coordinates = (int (*)(const _EC_GROUP_PTR, _EC_POINT_PTR, const _BIGNUM_PTR, const _BIGNUM_PTR, _BN_CTX_PTR))dlsym(handle, "EC_POINT_set_affine_coordinates");
	_g_ERR_get_error_all = (unsigned long (*)(const char**, int*, const char**, const char**, int*))dlsym(handle, "ERR_get_error_all");
	_g_EVP_CIPHER_fetch = (_EVP_CIPHER_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_CIPHER_fetch");
	_g_EVP_CIPHER_get0_name = (const char* (*)(const _EVP_CIPHER_PTR))dlsym(handle, "EVP_CIPHER_get0_name");
	_g_EVP_CIPHER_get_block_size = (int (*)(const _EVP_CIPHER_PTR))dlsym(handle, "EVP_CIPHER_get_block_size");
	_g_EVP_KDF_CTX_free = (void (*)(_EVP_KDF_CTX_PTR))dlsym(handle, "EVP_KDF_CTX_free");
	_g_EVP_KDF_CTX_get_kdf_size = (size_t (*)(_EVP_KDF_CTX_PTR))dlsym(handle, "EVP_KDF_CTX_get_kdf_size");
	_g_EVP_KDF_CTX_new = (_EVP_KDF_CTX_PTR (*)(_EVP_KDF_PTR))dlsym(handle, "EVP_KDF_CTX_new");
	_g_EVP_KDF_CTX_set_params = (int (*)(_EVP_KDF_CTX_PTR, const _OSSL_PARAM_PTR))dlsym(handle, "EVP_KDF_CTX_set_params");
	_g_EVP_KDF_derive = (int (*)(_EVP_KDF_CTX_PTR, unsigned char*, size_t, const _OSSL_PARAM_PTR))dlsym(handle, "EVP_KDF_derive");
	_g_EVP_KDF_fetch = (_EVP_KDF_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_KDF_fetch");
	_g_EVP_KDF_free = (void (*)(_EVP_KDF_PTR))dlsym(handle, "EVP_KDF_free");
	_g_EVP_MAC_CTX_dup = (_EVP_MAC_CTX_PTR (*)(const _EVP_MAC_CTX_PTR))dlsym(handle, "EVP_MAC_CTX_dup");
	_g_EVP_MAC_CTX_free = (void (*)(_EVP_MAC_CTX_PTR))dlsym(handle, "EVP_MAC_CTX_free");
	_g_EVP_MAC_CTX_new = (_EVP_MAC_CTX_PTR (*)(_EVP_MAC_PTR))dlsym(handle, "EVP_MAC_CTX_new");
	_g_EVP_MAC_CTX_set_params = (int (*)(_EVP_MAC_CTX_PTR, const _OSSL_PARAM_PTR))dlsym(handle, "EVP_MAC_CTX_set_params");
	_g_EVP_MAC_fetch = (_EVP_MAC_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_MAC_fetch");
	_g_EVP_MAC_final = (int (*)(_EVP_MAC_CTX_PTR, unsigned char*, size_t*, size_t))dlsym(handle, "EVP_MAC_final");
	_g_EVP_MAC_init = (int (*)(_EVP_MAC_CTX_PTR, const unsigned char*, size_t, const _OSSL_PARAM_PTR))dlsym(handle, "EVP_MAC_init");
	_g_EVP_MAC_update = (int (*)(_EVP_MAC_CTX_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_MAC_update");
	_g_EVP_MD_fetch = (_EVP_MD_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_MD_fetch");
	_g_EVP_MD_free = (void (*)(_EVP_MD_PTR))dlsym(handle, "EVP_MD_free");
	_g_EVP_MD_get0_name = (const char* (*)(const _EVP_MD_PTR))dlsym(handle, "EVP_MD_get0_name");
	_g_EVP_MD_get0_provider = (const _OSSL_PROVIDER_PTR (*)(const _EVP_MD_PTR))dlsym(handle, "EVP_MD_get0_provider");
	_g_EVP_MD_get_block_size = (int (*)(const _EVP_MD_PTR))dlsym(handle, "EVP_MD_get_block_size");
	_g_EVP_MD_get_size = (int (*)(const _EVP_MD_PTR))dlsym(handle, "EVP_MD_get_size");
	_g_EVP_MD_get_type = (int (*)(const _EVP_MD_PTR))dlsym(handle, "EVP_MD_get_type");
	_g_EVP_PKEY_CTX_add1_hkdf_info = (int (*)(_EVP_PKEY_CTX_PTR, const unsigned char*, int))dlsym(handle, "EVP_PKEY_CTX_add1_hkdf_info");
	_g_EVP_PKEY_CTX_new_from_pkey = (_EVP_PKEY_CTX_PTR (*)(_OSSL_LIB_CTX_PTR, _EVP_PKEY_PTR, const char*))dlsym(handle, "EVP_PKEY_CTX_new_from_pkey");
	_g_EVP_PKEY_CTX_set0_rsa_oaep_label = (int (*)(_EVP_PKEY_CTX_PTR, void*, int))dlsym(handle, "EVP_PKEY_CTX_set0_rsa_oaep_label");
	_g_EVP_PKEY_CTX_set1_hkdf_key = (int (*)(_EVP_PKEY_CTX_PTR, const unsigned char*, int))dlsym(handle, "EVP_PKEY_CTX_set1_hkdf_key");
	_g_EVP_PKEY_CTX_set1_hkdf_salt = (int (*)(_EVP_PKEY_CTX_PTR, const unsigned char*, int))dlsym(handle, "EVP_PKEY_CTX_set1_hkdf_salt");
	_g_EVP_PKEY_CTX_set_hkdf_md = (int (*)(_EVP_PKEY_CTX_PTR, const _EVP_MD_PTR))dlsym(handle, "EVP_PKEY_CTX_set_hkdf_md");
	_g_EVP_PKEY_CTX_set_hkdf_mode = (int (*)(_EVP_PKEY_CTX_PTR, int))dlsym(handle, "EVP_PKEY_CTX_set_hkdf_mode");
	_g_EVP_PKEY_Q_keygen = (_EVP_PKEY_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_PKEY_Q_keygen");
	_g_EVP_PKEY_Q_keygen_EC = (_EVP_PKEY_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, const char*, const char*))dlsym(handle, "EVP_PKEY_Q_keygen");
	_g_EVP_PKEY_Q_keygen_RSA = (_EVP_PKEY_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, const char*, size_t))dlsym(handle, "EVP_PKEY_Q_keygen");
	_g_EVP_PKEY_fromdata = (int (*)(_EVP_PKEY_CTX_PTR, _EVP_PKEY_PTR*, int, _OSSL_PARAM_PTR))dlsym(handle, "EVP_PKEY_fromdata");
	_g_EVP_PKEY_fromdata_init = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_fromdata_init");
	_g_EVP_PKEY_get1_encoded_public_key = (size_t (*)(_EVP_PKEY_PTR, unsigned char**))dlsym(handle, "EVP_PKEY_get1_encoded_public_key");
	_g_EVP_PKEY_get_bits = (int (*)(const _EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get_bits");
	_g_EVP_PKEY_get_bn_param = (int (*)(const _EVP_PKEY_PTR, const char*, _BIGNUM_PTR*))dlsym(handle, "EVP_PKEY_get_bn_param");
	_g_EVP_PKEY_get_size = (int (*)(const _EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get_size");
	_g_EVP_PKEY_private_check = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_private_check");
	_g_EVP_PKEY_public_check_quick = (int (*)(_EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_public_check_quick");
	_g_EVP_PKEY_set1_encoded_public_key = (int (*)(_EVP_PKEY_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_set1_encoded_public_key");
	_g_EVP_PKEY_up_ref = (int (*)(_EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_up_ref");
	_g_EVP_SIGNATURE_fetch = (_EVP_SIGNATURE_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_SIGNATURE_fetch");
	_g_EVP_SIGNATURE_free = (void (*)(_EVP_SIGNATURE_PTR))dlsym(handle, "EVP_SIGNATURE_free");
	_g_EVP_default_properties_enable_fips = (int (*)(_OSSL_LIB_CTX_PTR, int))dlsym(handle, "EVP_default_properties_enable_fips");
	_g_EVP_default_properties_is_fips_enabled = (int (*)(_OSSL_LIB_CTX_PTR))dlsym(handle, "EVP_default_properties_is_fips_enabled");
	_g_OSSL_PARAM_BLD_free = (void (*)(_OSSL_PARAM_BLD_PTR))dlsym(handle, "OSSL_PARAM_BLD_free");
	_g_OSSL_PARAM_BLD_new = (_OSSL_PARAM_BLD_PTR (*)(void))dlsym(handle, "OSSL_PARAM_BLD_new");
	_g_OSSL_PARAM_BLD_push_BN = (int (*)(_OSSL_PARAM_BLD_PTR, const char*, const _BIGNUM_PTR))dlsym(handle, "OSSL_PARAM_BLD_push_BN");
	_g_OSSL_PARAM_BLD_push_int32 = (int (*)(_OSSL_PARAM_BLD_PTR, const char*, int32_t))dlsym(handle, "OSSL_PARAM_BLD_push_int32");
	_g_OSSL_PARAM_BLD_push_octet_string = (int (*)(_OSSL_PARAM_BLD_PTR, const char*, const void*, size_t))dlsym(handle, "OSSL_PARAM_BLD_push_octet_string");
	_g_OSSL_PARAM_BLD_push_utf8_string = (int (*)(_OSSL_PARAM_BLD_PTR, const char*, const char*, size_t))dlsym(handle, "OSSL_PARAM_BLD_push_utf8_string");
	_g_OSSL_PARAM_BLD_to_param = (_OSSL_PARAM_PTR (*)(_OSSL_PARAM_BLD_PTR))dlsym(handle, "OSSL_PARAM_BLD_to_param");
	_g_OSSL_PARAM_free = (void (*)(_OSSL_PARAM_PTR))dlsym(handle, "OSSL_PARAM_free");
	_g_OSSL_PROVIDER_available = (int (*)(_OSSL_LIB_CTX_PTR, const char*))dlsym(handle, "OSSL_PROVIDER_available");
	_g_OSSL_PROVIDER_get0_name = (const char* (*)(const _OSSL_PROVIDER_PTR))dlsym(handle, "OSSL_PROVIDER_get0_name");
	_g_OSSL_PROVIDER_try_load = (_OSSL_PROVIDER_PTR (*)(_OSSL_LIB_CTX_PTR, const char*, int))dlsym(handle, "OSSL_PROVIDER_try_load");
}

void __mkcgoLoad_legacy_1(void* handle) {
	_g_DSA_free = (void (*)(_DSA_PTR))dlsym(handle, "DSA_free");
	_g_DSA_generate_key = (int (*)(_DSA_PTR))dlsym(handle, "DSA_generate_key");
	_g_DSA_get0_key = (void (*)(const _DSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*))dlsym(handle, "DSA_get0_key");
	_g_DSA_get0_pqg = (void (*)(const _DSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*))dlsym(handle, "DSA_get0_pqg");
	_g_DSA_new = (_DSA_PTR (*)(void))dlsym(handle, "DSA_new");
	_g_DSA_set0_key = (int (*)(_DSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR))dlsym(handle, "DSA_set0_key");
	_g_DSA_set0_pqg = (int (*)(_DSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR))dlsym(handle, "DSA_set0_pqg");
	_g_EC_KEY_check_key = (int (*)(const _EC_KEY_PTR))dlsym(handle, "EC_KEY_check_key");
	_g_EC_KEY_free = (void (*)(_EC_KEY_PTR))dlsym(handle, "EC_KEY_free");
	_g_EC_KEY_get0_group = (const _EC_GROUP_PTR (*)(const _EC_KEY_PTR))dlsym(handle, "EC_KEY_get0_group");
	_g_EC_KEY_get0_private_key = (const _BIGNUM_PTR (*)(const _EC_KEY_PTR))dlsym(handle, "EC_KEY_get0_private_key");
	_g_EC_KEY_get0_public_key = (const _EC_POINT_PTR (*)(const _EC_KEY_PTR))dlsym(handle, "EC_KEY_get0_public_key");
	_g_EC_KEY_new_by_curve_name = (_EC_KEY_PTR (*)(int))dlsym(handle, "EC_KEY_new_by_curve_name");
	_g_EC_KEY_set_private_key = (int (*)(_EC_KEY_PTR, const _BIGNUM_PTR))dlsym(handle, "EC_KEY_set_private_key");
	_g_EC_KEY_set_public_key = (int (*)(_EC_KEY_PTR, const _EC_POINT_PTR))dlsym(handle, "EC_KEY_set_public_key");
	_g_EC_KEY_set_public_key_affine_coordinates = (int (*)(_EC_KEY_PTR, _BIGNUM_PTR, _BIGNUM_PTR))dlsym(handle, "EC_KEY_set_public_key_affine_coordinates");
	_g_EC_POINT_get_affine_coordinates_GFp = (int (*)(const _EC_GROUP_PTR, const _EC_POINT_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BN_CTX_PTR))dlsym(handle, "EC_POINT_get_affine_coordinates_GFp");
	_g_ERR_get_error_line = (unsigned long (*)(const char**, int*))dlsym(handle, "ERR_get_error_line");
	_g_EVP_CIPHER_block_size = (int (*)(const _EVP_CIPHER_PTR))dlsym(handle, "EVP_CIPHER_block_size");
	_g_EVP_MD_block_size = (int (*)(const _EVP_MD_PTR))dlsym(handle, "EVP_MD_block_size");
	_g_EVP_MD_size = (int (*)(const _EVP_MD_PTR))dlsym(handle, "EVP_MD_size");
	_g_EVP_PKEY_assign = (int (*)(_EVP_PKEY_PTR, int, void*))dlsym(handle, "EVP_PKEY_assign");
	_g_EVP_PKEY_bits = (int (*)(const _EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_bits");
	_g_EVP_PKEY_get0_DSA = (_DSA_PTR (*)(_EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get0_DSA");
	_g_EVP_PKEY_get0_EC_KEY = (_EC_KEY_PTR (*)(_EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get0_EC_KEY");
	_g_EVP_PKEY_get1_RSA = (_RSA_PTR (*)(_EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get1_RSA");
	_g_EVP_PKEY_set1_EC_KEY = (int (*)(_EVP_PKEY_PTR, _EC_KEY_PTR))dlsym(handle, "EVP_PKEY_set1_EC_KEY");
	_g_EVP_PKEY_size = (int (*)(const _EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_size");
	_g_FIPS_mode = (int (*)(void))dlsym(handle, "FIPS_mode");
	_g_FIPS_mode_set = (int (*)(int))dlsym(handle, "FIPS_mode_set");
	_g_HMAC_CTX_copy = (int (*)(_HMAC_CTX_PTR, _HMAC_CTX_PTR))dlsym(handle, "HMAC_CTX_copy");
	_g_HMAC_CTX_free = (void (*)(_HMAC_CTX_PTR))dlsym(handle, "HMAC_CTX_free");
	_g_HMAC_CTX_new = (_HMAC_CTX_PTR (*)(void))dlsym(handle, "HMAC_CTX_new");
	_g_HMAC_Final = (int (*)(_HMAC_CTX_PTR, unsigned char*, unsigned int*))dlsym(handle, "HMAC_Final");
	_g_HMAC_Init_ex = (int (*)(_HMAC_CTX_PTR, const void*, int, const _EVP_MD_PTR, _ENGINE_PTR))dlsym(handle, "HMAC_Init_ex");
	_g_HMAC_Update = (int (*)(_HMAC_CTX_PTR, const unsigned char*, size_t))dlsym(handle, "HMAC_Update");
	_g_RSA_free = (void (*)(_RSA_PTR))dlsym(handle, "RSA_free");
	_g_RSA_get0_crt_params = (void (*)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*))dlsym(handle, "RSA_get0_crt_params");
	_g_RSA_get0_factors = (void (*)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*))dlsym(handle, "RSA_get0_factors");
	_g_RSA_get0_key = (void (*)(const _RSA_PTR, const _BIGNUM_PTR*, const _BIGNUM_PTR*, const _BIGNUM_PTR*))dlsym(handle, "RSA_get0_key");
	_g_RSA_new = (_RSA_PTR (*)(void))dlsym(handle, "RSA_new");
	_g_RSA_set0_crt_params = (int (*)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR))dlsym(handle, "RSA_set0_crt_params");
	_g_RSA_set0_factors = (int (*)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR))dlsym(handle, "RSA_set0_factors");
	_g_RSA_set0_key = (int (*)(_RSA_PTR, _BIGNUM_PTR, _BIGNUM_PTR, _BIGNUM_PTR))dlsym(handle, "RSA_set0_key");
}

_BIGNUM_PTR BN_bin2bn(const unsigned char* _arg0, int _arg1, _BIGNUM_PTR _arg2) {
	return _g_BN_bin2bn(_arg0, _arg1, _arg2);
}

int BN_bn2binpad(const _BIGNUM_PTR _arg0, unsigned char* _arg1, int _arg2) {
	return _g_BN_bn2binpad(_arg0, _arg1, _arg2);
}

int BN_bn2lebinpad(const _BIGNUM_PTR _arg0, unsigned char* _arg1, int _arg2) {
	return _g_BN_bn2lebinpad(_arg0, _arg1, _arg2);
}

void BN_clear(_BIGNUM_PTR _arg0) {
	_g_BN_clear(_arg0);
}

void BN_clear_free(_BIGNUM_PTR _arg0) {
	_g_BN_clear_free(_arg0);
}

void BN_free(_BIGNUM_PTR _arg0) {
	_g_BN_free(_arg0);
}

_BIGNUM_PTR BN_lebin2bn(const unsigned char* _arg0, int _arg1, _BIGNUM_PTR _arg2) {
	return _g_BN_lebin2bn(_arg0, _arg1, _arg2);
}

_BIGNUM_PTR BN_new(void) {
	return _g_BN_new();
}

int BN_num_bits(const _BIGNUM_PTR _arg0) {
	return _g_BN_num_bits(_arg0);
}

void CRYPTO_free(void* _arg0, const char* _arg1, int _arg2) {
	_g_CRYPTO_free(_arg0, _arg1, _arg2);
}

void* CRYPTO_malloc(size_t _arg0, const char* _arg1, int _arg2) {
	return _g_CRYPTO_malloc(_arg0, _arg1, _arg2);
}

void DSA_free(_DSA_PTR _arg0) {
	_g_DSA_free(_arg0);
}

int DSA_generate_key(_DSA_PTR _arg0) {
	return _g_DSA_generate_key(_arg0);
}

void DSA_get0_key(const _DSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2) {
	_g_DSA_get0_key(_arg0, _arg1, _arg2);
}

void DSA_get0_pqg(const _DSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2, const _BIGNUM_PTR* _arg3) {
	_g_DSA_get0_pqg(_arg0, _arg1, _arg2, _arg3);
}

_DSA_PTR DSA_new(void) {
	return _g_DSA_new();
}

int DSA_set0_key(_DSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2) {
	return _g_DSA_set0_key(_arg0, _arg1, _arg2);
}

int DSA_set0_pqg(_DSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, _BIGNUM_PTR _arg3) {
	return _g_DSA_set0_pqg(_arg0, _arg1, _arg2, _arg3);
}

void EC_GROUP_free(_EC_GROUP_PTR _arg0) {
	_g_EC_GROUP_free(_arg0);
}

_EC_GROUP_PTR EC_GROUP_new_by_curve_name(int _arg0) {
	return _g_EC_GROUP_new_by_curve_name(_arg0);
}

int EC_KEY_check_key(const _EC_KEY_PTR _arg0) {
	return _g_EC_KEY_check_key(_arg0);
}

void EC_KEY_free(_EC_KEY_PTR _arg0) {
	_g_EC_KEY_free(_arg0);
}

const _EC_GROUP_PTR EC_KEY_get0_group(const _EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_group(_arg0);
}

const _BIGNUM_PTR EC_KEY_get0_private_key(const _EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_private_key(_arg0);
}

const _EC_POINT_PTR EC_KEY_get0_public_key(const _EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_public_key(_arg0);
}

_EC_KEY_PTR EC_KEY_new_by_curve_name(int _arg0) {
	return _g_EC_KEY_new_by_curve_name(_arg0);
}

int EC_KEY_set_private_key(_EC_KEY_PTR _arg0, const _BIGNUM_PTR _arg1) {
	return _g_EC_KEY_set_private_key(_arg0, _arg1);
}

int EC_KEY_set_public_key(_EC_KEY_PTR _arg0, const _EC_POINT_PTR _arg1) {
	return _g_EC_KEY_set_public_key(_arg0, _arg1);
}

int EC_KEY_set_public_key_affine_coordinates(_EC_KEY_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2) {
	return _g_EC_KEY_set_public_key_affine_coordinates(_arg0, _arg1, _arg2);
}

void EC_POINT_free(_EC_POINT_PTR _arg0) {
	_g_EC_POINT_free(_arg0);
}

int EC_POINT_get_affine_coordinates_GFp(const _EC_GROUP_PTR _arg0, const _EC_POINT_PTR _arg1, _BIGNUM_PTR _arg2, _BIGNUM_PTR _arg3, _BN_CTX_PTR _arg4) {
	return _g_EC_POINT_get_affine_coordinates_GFp(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EC_POINT_mul(const _EC_GROUP_PTR _arg0, _EC_POINT_PTR _arg1, const _BIGNUM_PTR _arg2, const _EC_POINT_PTR _arg3, const _BIGNUM_PTR _arg4, _BN_CTX_PTR _arg5) {
	return _g_EC_POINT_mul(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

_EC_POINT_PTR EC_POINT_new(const _EC_GROUP_PTR _arg0) {
	return _g_EC_POINT_new(_arg0);
}

int EC_POINT_oct2point(const _EC_GROUP_PTR _arg0, _EC_POINT_PTR _arg1, const unsigned char* _arg2, size_t _arg3, _BN_CTX_PTR _arg4) {
	return _g_EC_POINT_oct2point(_arg0, _arg1, _arg2, _arg3, _arg4);
}

size_t EC_POINT_point2oct(const _EC_GROUP_PTR _arg0, const _EC_POINT_PTR _arg1, point_conversion_form_t _arg2, unsigned char* _arg3, size_t _arg4, _BN_CTX_PTR _arg5) {
	return _g_EC_POINT_point2oct(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int EC_POINT_set_affine_coordinates(const _EC_GROUP_PTR _arg0, _EC_POINT_PTR _arg1, const _BIGNUM_PTR _arg2, const _BIGNUM_PTR _arg3, _BN_CTX_PTR _arg4) {
	return _g_EC_POINT_set_affine_coordinates(_arg0, _arg1, _arg2, _arg3, _arg4);
}

void ERR_clear_error(void) {
	_g_ERR_clear_error();
}

void ERR_error_string_n(unsigned long _arg0, char* _arg1, size_t _arg2) {
	_g_ERR_error_string_n(_arg0, _arg1, _arg2);
}

unsigned long ERR_get_error_all(const char** _arg0, int* _arg1, const char** _arg2, const char** _arg3, int* _arg4) {
	return _g_ERR_get_error_all(_arg0, _arg1, _arg2, _arg3, _arg4);
}

unsigned long ERR_get_error_line(const char** _arg0, int* _arg1) {
	return _g_ERR_get_error_line(_arg0, _arg1);
}

int EVP_CIPHER_CTX_ctrl(_EVP_CIPHER_CTX_PTR _arg0, int _arg1, int _arg2, void* _arg3) {
	return _g_EVP_CIPHER_CTX_ctrl(_arg0, _arg1, _arg2, _arg3);
}

void EVP_CIPHER_CTX_free(_EVP_CIPHER_CTX_PTR _arg0) {
	_g_EVP_CIPHER_CTX_free(_arg0);
}

_EVP_CIPHER_CTX_PTR EVP_CIPHER_CTX_new(void) {
	return _g_EVP_CIPHER_CTX_new();
}

int EVP_CIPHER_CTX_set_key_length(_EVP_CIPHER_CTX_PTR _arg0, int _arg1) {
	return _g_EVP_CIPHER_CTX_set_key_length(_arg0, _arg1);
}

int EVP_CIPHER_CTX_set_padding(_EVP_CIPHER_CTX_PTR _arg0, int _arg1) {
	return _g_EVP_CIPHER_CTX_set_padding(_arg0, _arg1);
}

int EVP_CIPHER_block_size(const _EVP_CIPHER_PTR _arg0) {
	return _g_EVP_CIPHER_block_size(_arg0);
}

_EVP_CIPHER_PTR EVP_CIPHER_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_CIPHER_fetch(_arg0, _arg1, _arg2);
}

const char* EVP_CIPHER_get0_name(const _EVP_CIPHER_PTR _arg0) {
	return _g_EVP_CIPHER_get0_name(_arg0);
}

int EVP_CIPHER_get_block_size(const _EVP_CIPHER_PTR _arg0) {
	return _g_EVP_CIPHER_get_block_size(_arg0);
}

int EVP_CipherInit_ex(_EVP_CIPHER_CTX_PTR _arg0, const _EVP_CIPHER_PTR _arg1, _ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4, int _arg5) {
	return _g_EVP_CipherInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int EVP_CipherUpdate(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4) {
	return _g_EVP_CipherUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DecryptFinal_ex(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2) {
	return _g_EVP_DecryptFinal_ex(_arg0, _arg1, _arg2);
}

int EVP_DecryptInit_ex(_EVP_CIPHER_CTX_PTR _arg0, const _EVP_CIPHER_PTR _arg1, _ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4) {
	return _g_EVP_DecryptInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DecryptUpdate(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4) {
	return _g_EVP_DecryptUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_Digest(const void* _arg0, size_t _arg1, unsigned char* _arg2, unsigned int* _arg3, const _EVP_MD_PTR _arg4, _ENGINE_PTR _arg5) {
	return _g_EVP_Digest(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int EVP_DigestFinal_ex(_EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, unsigned int* _arg2) {
	return _g_EVP_DigestFinal_ex(_arg0, _arg1, _arg2);
}

int EVP_DigestInit(_EVP_MD_CTX_PTR _arg0, const _EVP_MD_PTR _arg1) {
	return _g_EVP_DigestInit(_arg0, _arg1);
}

int EVP_DigestInit_ex(_EVP_MD_CTX_PTR _arg0, const _EVP_MD_PTR _arg1, _ENGINE_PTR _arg2) {
	return _g_EVP_DigestInit_ex(_arg0, _arg1, _arg2);
}

int EVP_DigestSign(_EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_DigestSign(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DigestSignFinal(_EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2) {
	return _g_EVP_DigestSignFinal(_arg0, _arg1, _arg2);
}

int EVP_DigestSignInit(_EVP_MD_CTX_PTR _arg0, _EVP_PKEY_CTX_PTR* _arg1, const _EVP_MD_PTR _arg2, _ENGINE_PTR _arg3, _EVP_PKEY_PTR _arg4) {
	return _g_EVP_DigestSignInit(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DigestUpdate(_EVP_MD_CTX_PTR _arg0, const void* _arg1, size_t _arg2) {
	return _g_EVP_DigestUpdate(_arg0, _arg1, _arg2);
}

int EVP_DigestVerify(_EVP_MD_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_DigestVerify(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DigestVerifyFinal(_EVP_MD_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2) {
	return _g_EVP_DigestVerifyFinal(_arg0, _arg1, _arg2);
}

int EVP_DigestVerifyInit(_EVP_MD_CTX_PTR _arg0, _EVP_PKEY_CTX_PTR* _arg1, const _EVP_MD_PTR _arg2, _ENGINE_PTR _arg3, _EVP_PKEY_PTR _arg4) {
	return _g_EVP_DigestVerifyInit(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_EncryptFinal_ex(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2) {
	return _g_EVP_EncryptFinal_ex(_arg0, _arg1, _arg2);
}

int EVP_EncryptInit_ex(_EVP_CIPHER_CTX_PTR _arg0, const _EVP_CIPHER_PTR _arg1, _ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4) {
	return _g_EVP_EncryptInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_EncryptUpdate(_EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4) {
	return _g_EVP_EncryptUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
}

void EVP_KDF_CTX_free(_EVP_KDF_CTX_PTR _arg0) {
	_g_EVP_KDF_CTX_free(_arg0);
}

size_t EVP_KDF_CTX_get_kdf_size(_EVP_KDF_CTX_PTR _arg0) {
	return _g_EVP_KDF_CTX_get_kdf_size(_arg0);
}

_EVP_KDF_CTX_PTR EVP_KDF_CTX_new(_EVP_KDF_PTR _arg0) {
	return _g_EVP_KDF_CTX_new(_arg0);
}

int EVP_KDF_CTX_set_params(_EVP_KDF_CTX_PTR _arg0, const _OSSL_PARAM_PTR _arg1) {
	return _g_EVP_KDF_CTX_set_params(_arg0, _arg1);
}

int EVP_KDF_derive(_EVP_KDF_CTX_PTR _arg0, unsigned char* _arg1, size_t _arg2, const _OSSL_PARAM_PTR _arg3) {
	return _g_EVP_KDF_derive(_arg0, _arg1, _arg2, _arg3);
}

_EVP_KDF_PTR EVP_KDF_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_KDF_fetch(_arg0, _arg1, _arg2);
}

void EVP_KDF_free(_EVP_KDF_PTR _arg0) {
	_g_EVP_KDF_free(_arg0);
}

_EVP_MAC_CTX_PTR EVP_MAC_CTX_dup(const _EVP_MAC_CTX_PTR _arg0) {
	return _g_EVP_MAC_CTX_dup(_arg0);
}

void EVP_MAC_CTX_free(_EVP_MAC_CTX_PTR _arg0) {
	_g_EVP_MAC_CTX_free(_arg0);
}

_EVP_MAC_CTX_PTR EVP_MAC_CTX_new(_EVP_MAC_PTR _arg0) {
	return _g_EVP_MAC_CTX_new(_arg0);
}

int EVP_MAC_CTX_set_params(_EVP_MAC_CTX_PTR _arg0, const _OSSL_PARAM_PTR _arg1) {
	return _g_EVP_MAC_CTX_set_params(_arg0, _arg1);
}

_EVP_MAC_PTR EVP_MAC_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_MAC_fetch(_arg0, _arg1, _arg2);
}

int EVP_MAC_final(_EVP_MAC_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, size_t _arg3) {
	return _g_EVP_MAC_final(_arg0, _arg1, _arg2, _arg3);
}

int EVP_MAC_init(_EVP_MAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const _OSSL_PARAM_PTR _arg3) {
	return _g_EVP_MAC_init(_arg0, _arg1, _arg2, _arg3);
}

int EVP_MAC_update(_EVP_MAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2) {
	return _g_EVP_MAC_update(_arg0, _arg1, _arg2);
}

int EVP_MD_CTX_copy(_EVP_MD_CTX_PTR _arg0, const _EVP_MD_CTX_PTR _arg1) {
	return _g_EVP_MD_CTX_copy(_arg0, _arg1);
}

int EVP_MD_CTX_copy_ex(_EVP_MD_CTX_PTR _arg0, const _EVP_MD_CTX_PTR _arg1) {
	return _g_EVP_MD_CTX_copy_ex(_arg0, _arg1);
}

void EVP_MD_CTX_free(_EVP_MD_CTX_PTR _arg0) {
	_g_EVP_MD_CTX_free(_arg0);
}

_EVP_MD_CTX_PTR EVP_MD_CTX_new(void) {
	return _g_EVP_MD_CTX_new();
}

int EVP_MD_block_size(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_block_size(_arg0);
}

_EVP_MD_PTR EVP_MD_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_MD_fetch(_arg0, _arg1, _arg2);
}

void EVP_MD_free(_EVP_MD_PTR _arg0) {
	_g_EVP_MD_free(_arg0);
}

const char* EVP_MD_get0_name(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get0_name(_arg0);
}

const _OSSL_PROVIDER_PTR EVP_MD_get0_provider(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get0_provider(_arg0);
}

int EVP_MD_get_block_size(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get_block_size(_arg0);
}

int EVP_MD_get_size(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get_size(_arg0);
}

int EVP_MD_get_type(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get_type(_arg0);
}

int EVP_MD_size(const _EVP_MD_PTR _arg0) {
	return _g_EVP_MD_size(_arg0);
}

int EVP_PKEY_CTX_add1_hkdf_info(_EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2) {
	return _g_EVP_PKEY_CTX_add1_hkdf_info(_arg0, _arg1, _arg2);
}

int EVP_PKEY_CTX_ctrl(_EVP_PKEY_CTX_PTR _arg0, int _arg1, int _arg2, int _arg3, int _arg4, void* _arg5) {
	return _g_EVP_PKEY_CTX_ctrl(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

void EVP_PKEY_CTX_free(_EVP_PKEY_CTX_PTR _arg0) {
	_g_EVP_PKEY_CTX_free(_arg0);
}

_EVP_PKEY_CTX_PTR EVP_PKEY_CTX_new(_EVP_PKEY_PTR _arg0, _ENGINE_PTR _arg1) {
	return _g_EVP_PKEY_CTX_new(_arg0, _arg1);
}

_EVP_PKEY_CTX_PTR EVP_PKEY_CTX_new_from_pkey(_OSSL_LIB_CTX_PTR _arg0, _EVP_PKEY_PTR _arg1, const char* _arg2) {
	return _g_EVP_PKEY_CTX_new_from_pkey(_arg0, _arg1, _arg2);
}

_EVP_PKEY_CTX_PTR EVP_PKEY_CTX_new_id(int _arg0, _ENGINE_PTR _arg1) {
	return _g_EVP_PKEY_CTX_new_id(_arg0, _arg1);
}

int EVP_PKEY_CTX_set0_rsa_oaep_label(_EVP_PKEY_CTX_PTR _arg0, void* _arg1, int _arg2) {
	return _g_EVP_PKEY_CTX_set0_rsa_oaep_label(_arg0, _arg1, _arg2);
}

int EVP_PKEY_CTX_set1_hkdf_key(_EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2) {
	return _g_EVP_PKEY_CTX_set1_hkdf_key(_arg0, _arg1, _arg2);
}

int EVP_PKEY_CTX_set1_hkdf_salt(_EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2) {
	return _g_EVP_PKEY_CTX_set1_hkdf_salt(_arg0, _arg1, _arg2);
}

int EVP_PKEY_CTX_set_hkdf_md(_EVP_PKEY_CTX_PTR _arg0, const _EVP_MD_PTR _arg1) {
	return _g_EVP_PKEY_CTX_set_hkdf_md(_arg0, _arg1);
}

int EVP_PKEY_CTX_set_hkdf_mode(_EVP_PKEY_CTX_PTR _arg0, int _arg1) {
	return _g_EVP_PKEY_CTX_set_hkdf_mode(_arg0, _arg1);
}

_EVP_PKEY_PTR EVP_PKEY_Q_keygen(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_PKEY_Q_keygen(_arg0, _arg1, _arg2);
}

_EVP_PKEY_PTR EVP_PKEY_Q_keygen_EC(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, const char* _arg3) {
	return _g_EVP_PKEY_Q_keygen_EC(_arg0, _arg1, _arg2, _arg3);
}

_EVP_PKEY_PTR EVP_PKEY_Q_keygen_RSA(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, size_t _arg3) {
	return _g_EVP_PKEY_Q_keygen_RSA(_arg0, _arg1, _arg2, _arg3);
}

int EVP_PKEY_assign(_EVP_PKEY_PTR _arg0, int _arg1, void* _arg2) {
	return _g_EVP_PKEY_assign(_arg0, _arg1, _arg2);
}

int EVP_PKEY_bits(const _EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_bits(_arg0);
}

int EVP_PKEY_decrypt(_EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_PKEY_decrypt(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_PKEY_decrypt_init(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_decrypt_init(_arg0);
}

int EVP_PKEY_derive(_EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2) {
	return _g_EVP_PKEY_derive(_arg0, _arg1, _arg2);
}

int EVP_PKEY_derive_init(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_derive_init(_arg0);
}

int EVP_PKEY_derive_set_peer(_EVP_PKEY_CTX_PTR _arg0, _EVP_PKEY_PTR _arg1) {
	return _g_EVP_PKEY_derive_set_peer(_arg0, _arg1);
}

int EVP_PKEY_encrypt(_EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_PKEY_encrypt(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_PKEY_encrypt_init(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_encrypt_init(_arg0);
}

void EVP_PKEY_free(_EVP_PKEY_PTR _arg0) {
	_g_EVP_PKEY_free(_arg0);
}

int EVP_PKEY_fromdata(_EVP_PKEY_CTX_PTR _arg0, _EVP_PKEY_PTR* _arg1, int _arg2, _OSSL_PARAM_PTR _arg3) {
	return _g_EVP_PKEY_fromdata(_arg0, _arg1, _arg2, _arg3);
}

int EVP_PKEY_fromdata_init(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_fromdata_init(_arg0);
}

_DSA_PTR EVP_PKEY_get0_DSA(_EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get0_DSA(_arg0);
}

_EC_KEY_PTR EVP_PKEY_get0_EC_KEY(_EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get0_EC_KEY(_arg0);
}

_RSA_PTR EVP_PKEY_get1_RSA(_EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get1_RSA(_arg0);
}

size_t EVP_PKEY_get1_encoded_public_key(_EVP_PKEY_PTR _arg0, unsigned char** _arg1) {
	return _g_EVP_PKEY_get1_encoded_public_key(_arg0, _arg1);
}

int EVP_PKEY_get_bits(const _EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get_bits(_arg0);
}

int EVP_PKEY_get_bn_param(const _EVP_PKEY_PTR _arg0, const char* _arg1, _BIGNUM_PTR* _arg2) {
	return _g_EVP_PKEY_get_bn_param(_arg0, _arg1, _arg2);
}

int EVP_PKEY_get_raw_private_key(const _EVP_PKEY_PTR _arg0, unsigned char* _arg1, size_t* _arg2) {
	return _g_EVP_PKEY_get_raw_private_key(_arg0, _arg1, _arg2);
}

int EVP_PKEY_get_raw_public_key(const _EVP_PKEY_PTR _arg0, unsigned char* _arg1, size_t* _arg2) {
	return _g_EVP_PKEY_get_raw_public_key(_arg0, _arg1, _arg2);
}

int EVP_PKEY_get_size(const _EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get_size(_arg0);
}

int EVP_PKEY_keygen(_EVP_PKEY_CTX_PTR _arg0, _EVP_PKEY_PTR* _arg1) {
	return _g_EVP_PKEY_keygen(_arg0, _arg1);
}

int EVP_PKEY_keygen_init(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_keygen_init(_arg0);
}

_EVP_PKEY_PTR EVP_PKEY_new(void) {
	return _g_EVP_PKEY_new();
}

_EVP_PKEY_PTR EVP_PKEY_new_raw_private_key(int _arg0, _ENGINE_PTR _arg1, const unsigned char* _arg2, size_t _arg3) {
	return _g_EVP_PKEY_new_raw_private_key(_arg0, _arg1, _arg2, _arg3);
}

_EVP_PKEY_PTR EVP_PKEY_new_raw_public_key(int _arg0, _ENGINE_PTR _arg1, const unsigned char* _arg2, size_t _arg3) {
	return _g_EVP_PKEY_new_raw_public_key(_arg0, _arg1, _arg2, _arg3);
}

int EVP_PKEY_paramgen(_EVP_PKEY_CTX_PTR _arg0, _EVP_PKEY_PTR* _arg1) {
	return _g_EVP_PKEY_paramgen(_arg0, _arg1);
}

int EVP_PKEY_paramgen_init(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_paramgen_init(_arg0);
}

int EVP_PKEY_private_check(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_private_check(_arg0);
}

int EVP_PKEY_public_check_quick(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_public_check_quick(_arg0);
}

int EVP_PKEY_set1_EC_KEY(_EVP_PKEY_PTR _arg0, _EC_KEY_PTR _arg1) {
	return _g_EVP_PKEY_set1_EC_KEY(_arg0, _arg1);
}

int EVP_PKEY_set1_encoded_public_key(_EVP_PKEY_PTR _arg0, const unsigned char* _arg1, size_t _arg2) {
	return _g_EVP_PKEY_set1_encoded_public_key(_arg0, _arg1, _arg2);
}

int EVP_PKEY_sign(_EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_PKEY_sign(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_PKEY_sign_init(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_sign_init(_arg0);
}

int EVP_PKEY_size(const _EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_size(_arg0);
}

int EVP_PKEY_up_ref(_EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_up_ref(_arg0);
}

int EVP_PKEY_verify(_EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_PKEY_verify(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_PKEY_verify_init(_EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_verify_init(_arg0);
}

_EVP_SIGNATURE_PTR EVP_SIGNATURE_fetch(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_SIGNATURE_fetch(_arg0, _arg1, _arg2);
}

void EVP_SIGNATURE_free(_EVP_SIGNATURE_PTR _arg0) {
	_g_EVP_SIGNATURE_free(_arg0);
}

const _EVP_CIPHER_PTR EVP_aes_128_cbc(void) {
	return _g_EVP_aes_128_cbc();
}

const _EVP_CIPHER_PTR EVP_aes_128_ctr(void) {
	return _g_EVP_aes_128_ctr();
}

const _EVP_CIPHER_PTR EVP_aes_128_ecb(void) {
	return _g_EVP_aes_128_ecb();
}

const _EVP_CIPHER_PTR EVP_aes_128_gcm(void) {
	return _g_EVP_aes_128_gcm();
}

const _EVP_CIPHER_PTR EVP_aes_192_cbc(void) {
	return _g_EVP_aes_192_cbc();
}

const _EVP_CIPHER_PTR EVP_aes_192_ctr(void) {
	return _g_EVP_aes_192_ctr();
}

const _EVP_CIPHER_PTR EVP_aes_192_ecb(void) {
	return _g_EVP_aes_192_ecb();
}

const _EVP_CIPHER_PTR EVP_aes_192_gcm(void) {
	return _g_EVP_aes_192_gcm();
}

const _EVP_CIPHER_PTR EVP_aes_256_cbc(void) {
	return _g_EVP_aes_256_cbc();
}

const _EVP_CIPHER_PTR EVP_aes_256_ctr(void) {
	return _g_EVP_aes_256_ctr();
}

const _EVP_CIPHER_PTR EVP_aes_256_ecb(void) {
	return _g_EVP_aes_256_ecb();
}

const _EVP_CIPHER_PTR EVP_aes_256_gcm(void) {
	return _g_EVP_aes_256_gcm();
}

int EVP_default_properties_enable_fips(_OSSL_LIB_CTX_PTR _arg0, int _arg1) {
	return _g_EVP_default_properties_enable_fips(_arg0, _arg1);
}

int EVP_default_properties_is_fips_enabled(_OSSL_LIB_CTX_PTR _arg0) {
	return _g_EVP_default_properties_is_fips_enabled(_arg0);
}

const _EVP_CIPHER_PTR EVP_des_cbc(void) {
	return _g_EVP_des_cbc();
}

const _EVP_CIPHER_PTR EVP_des_ecb(void) {
	return _g_EVP_des_ecb();
}

const _EVP_CIPHER_PTR EVP_des_ede3_cbc(void) {
	return _g_EVP_des_ede3_cbc();
}

const _EVP_CIPHER_PTR EVP_des_ede3_ecb(void) {
	return _g_EVP_des_ede3_ecb();
}

const _EVP_MD_PTR EVP_md4(void) {
	return _g_EVP_md4();
}

const _EVP_MD_PTR EVP_md5(void) {
	return _g_EVP_md5();
}

const _EVP_MD_PTR EVP_md5_sha1(void) {
	return _g_EVP_md5_sha1();
}

const _EVP_CIPHER_PTR EVP_rc4(void) {
	return _g_EVP_rc4();
}

const _EVP_MD_PTR EVP_ripemd160(void) {
	return _g_EVP_ripemd160();
}

const _EVP_MD_PTR EVP_sha1(void) {
	return _g_EVP_sha1();
}

const _EVP_MD_PTR EVP_sha224(void) {
	return _g_EVP_sha224();
}

const _EVP_MD_PTR EVP_sha256(void) {
	return _g_EVP_sha256();
}

const _EVP_MD_PTR EVP_sha384(void) {
	return _g_EVP_sha384();
}

const _EVP_MD_PTR EVP_sha3_224(void) {
	return _g_EVP_sha3_224();
}

const _EVP_MD_PTR EVP_sha3_256(void) {
	return _g_EVP_sha3_256();
}

const _EVP_MD_PTR EVP_sha3_384(void) {
	return _g_EVP_sha3_384();
}

const _EVP_MD_PTR EVP_sha3_512(void) {
	return _g_EVP_sha3_512();
}

const _EVP_MD_PTR EVP_sha512(void) {
	return _g_EVP_sha512();
}

const _EVP_MD_PTR EVP_sha512_224(void) {
	return _g_EVP_sha512_224();
}

const _EVP_MD_PTR EVP_sha512_256(void) {
	return _g_EVP_sha512_256();
}

int FIPS_mode(void) {
	return _g_FIPS_mode();
}

int FIPS_mode_set(int _arg0) {
	return _g_FIPS_mode_set(_arg0);
}

int HMAC_CTX_copy(_HMAC_CTX_PTR _arg0, _HMAC_CTX_PTR _arg1) {
	return _g_HMAC_CTX_copy(_arg0, _arg1);
}

void HMAC_CTX_free(_HMAC_CTX_PTR _arg0) {
	_g_HMAC_CTX_free(_arg0);
}

_HMAC_CTX_PTR HMAC_CTX_new(void) {
	return _g_HMAC_CTX_new();
}

int HMAC_Final(_HMAC_CTX_PTR _arg0, unsigned char* _arg1, unsigned int* _arg2) {
	return _g_HMAC_Final(_arg0, _arg1, _arg2);
}

int HMAC_Init_ex(_HMAC_CTX_PTR _arg0, const void* _arg1, int _arg2, const _EVP_MD_PTR _arg3, _ENGINE_PTR _arg4) {
	return _g_HMAC_Init_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int HMAC_Update(_HMAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2) {
	return _g_HMAC_Update(_arg0, _arg1, _arg2);
}

const char* OBJ_nid2sn(int _arg0) {
	return _g_OBJ_nid2sn(_arg0);
}

void OPENSSL_init(void) {
	_g_OPENSSL_init();
}

int OPENSSL_init_crypto(uint64_t _arg0, const _OPENSSL_INIT_SETTINGS_PTR _arg1) {
	return _g_OPENSSL_init_crypto(_arg0, _arg1);
}

void OSSL_PARAM_BLD_free(_OSSL_PARAM_BLD_PTR _arg0) {
	_g_OSSL_PARAM_BLD_free(_arg0);
}

_OSSL_PARAM_BLD_PTR OSSL_PARAM_BLD_new(void) {
	return _g_OSSL_PARAM_BLD_new();
}

int OSSL_PARAM_BLD_push_BN(_OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const _BIGNUM_PTR _arg2) {
	return _g_OSSL_PARAM_BLD_push_BN(_arg0, _arg1, _arg2);
}

int OSSL_PARAM_BLD_push_int32(_OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, int32_t _arg2) {
	return _g_OSSL_PARAM_BLD_push_int32(_arg0, _arg1, _arg2);
}

int OSSL_PARAM_BLD_push_octet_string(_OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const void* _arg2, size_t _arg3) {
	return _g_OSSL_PARAM_BLD_push_octet_string(_arg0, _arg1, _arg2, _arg3);
}

int OSSL_PARAM_BLD_push_utf8_string(_OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const char* _arg2, size_t _arg3) {
	return _g_OSSL_PARAM_BLD_push_utf8_string(_arg0, _arg1, _arg2, _arg3);
}

_OSSL_PARAM_PTR OSSL_PARAM_BLD_to_param(_OSSL_PARAM_BLD_PTR _arg0) {
	return _g_OSSL_PARAM_BLD_to_param(_arg0);
}

void OSSL_PARAM_free(_OSSL_PARAM_PTR _arg0) {
	_g_OSSL_PARAM_free(_arg0);
}

int OSSL_PROVIDER_available(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1) {
	return _g_OSSL_PROVIDER_available(_arg0, _arg1);
}

const char* OSSL_PROVIDER_get0_name(const _OSSL_PROVIDER_PTR _arg0) {
	return _g_OSSL_PROVIDER_get0_name(_arg0);
}

_OSSL_PROVIDER_PTR OSSL_PROVIDER_try_load(_OSSL_LIB_CTX_PTR _arg0, const char* _arg1, int _arg2) {
	return _g_OSSL_PROVIDER_try_load(_arg0, _arg1, _arg2);
}

const char* OpenSSL_version(int _arg0) {
	return _g_OpenSSL_version(_arg0);
}

int PKCS5_PBKDF2_HMAC(const char* _arg0, int _arg1, const unsigned char* _arg2, int _arg3, int _arg4, const _EVP_MD_PTR _arg5, int _arg6, unsigned char* _arg7) {
	return _g_PKCS5_PBKDF2_HMAC(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7);
}

int RAND_bytes(unsigned char* _arg0, int _arg1) {
	return _g_RAND_bytes(_arg0, _arg1);
}

void RSA_free(_RSA_PTR _arg0) {
	_g_RSA_free(_arg0);
}

void RSA_get0_crt_params(const _RSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2, const _BIGNUM_PTR* _arg3) {
	_g_RSA_get0_crt_params(_arg0, _arg1, _arg2, _arg3);
}

void RSA_get0_factors(const _RSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2) {
	_g_RSA_get0_factors(_arg0, _arg1, _arg2);
}

void RSA_get0_key(const _RSA_PTR _arg0, const _BIGNUM_PTR* _arg1, const _BIGNUM_PTR* _arg2, const _BIGNUM_PTR* _arg3) {
	_g_RSA_get0_key(_arg0, _arg1, _arg2, _arg3);
}

_RSA_PTR RSA_new(void) {
	return _g_RSA_new();
}

int RSA_set0_crt_params(_RSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, _BIGNUM_PTR _arg3) {
	return _g_RSA_set0_crt_params(_arg0, _arg1, _arg2, _arg3);
}

int RSA_set0_factors(_RSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2) {
	return _g_RSA_set0_factors(_arg0, _arg1, _arg2);
}

int RSA_set0_key(_RSA_PTR _arg0, _BIGNUM_PTR _arg1, _BIGNUM_PTR _arg2, _BIGNUM_PTR _arg3) {
	return _g_RSA_set0_key(_arg0, _arg1, _arg2, _arg3);
}

