package main

import (
	"fmt"
	"io"
	"slices"
	"strconv"
	"strings"
)

// Generate output source file from a source set src.
func (src *source) generate(w io.Writer) {
	fmt.Fprintf(w, "// Code generated by mkcgo. DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", *packageName)
	fmt.Fprintf(w, "/*\n")
	if *includeHeader != "" {
		fmt.Fprintf(w, "#include \"%s\"\n", *includeHeader)
	}
	for _, file := range src.files {
		fmt.Fprintf(w, "#include %q\n", file)
	}
	fmt.Fprintf(w, "void __mkcgoLoad_%s(void* handle);\n", *libName)
	fmt.Fprintf(w, "*/\n")
	fmt.Fprintf(w, "import \"C\"\n")
	if len(src.stdLibImports) > 0 {
		fmt.Fprintf(w, "import (\n")
		for _, imp := range src.stdLibImports {
			fmt.Fprintf(w, "\t%q\n", imp)
		}
		fmt.Fprintf(w, ")\n\n")
	}

	fmt.Fprintf(w, "func mkcgoLoad_%s(handle unsafe.Pointer) {\n", *libName)
	fmt.Fprintf(w, "\tC.__mkcgoLoad_%s(handle)\n", *libName)
	fmt.Fprintf(w, "}\n\n")

	for _, fn := range src.funcs {
		if fn.cOnly {
			continue
		}
		fn.generate(w)
	}
}

func (src *source) generateC(w io.Writer) {
	fmt.Fprintf(w, "// Code generated by mkcgo. DO NOT EDIT.\n\n")
	if *includeHeader != "" {
		fmt.Fprintf(w, "#include \"%s\"\n", *includeHeader)
	}
	fmt.Fprintf(w, "#include <stddef.h>\n")
	fmt.Fprintf(w, "#include <stdlib.h>\n")
	fmt.Fprintf(w, "#include <stdint.h>\n")
	fmt.Fprintf(w, "\n")

	fmt.Fprintf(w, "#ifdef _WIN32\n")
	fmt.Fprintf(w, "#include <windows.h>\n")
	fmt.Fprintf(w, "#define dlsym GetProcAddress\n")
	fmt.Fprintf(w, "#else\n")
	fmt.Fprintf(w, "#include <dlfcn.h>\n")
	fmt.Fprintf(w, "#endif\n\n")

	for _, fn := range src.funcs {
		if fn.isVariadic {
			continue
		}
		fmt.Fprintf(w, "%s (*_g_%s)(%s);\n", fn.rets.typ, fn.libName, fn.libArgList(false, true))
	}
	fmt.Fprintf(w, "\n")

	fmt.Fprintf(w, "void __mkcgoLoad_%s(void* handle) {\n", *libName)
	for _, fn := range src.funcs {
		if fn.isVariadic {
			continue
		}
		fmt.Fprintf(w, "\t_g_%s = (%s (*)(%s))dlsym(handle, %q);\n", fn.libName, fn.rets.typ, fn.libArgList(false, true), fn.importName)
	}
	fmt.Fprintf(w, "}\n\n")

	for _, fn := range src.funcs {
		if fn.isVariadic {
			continue
		}
		fmt.Fprintf(w, "%s %s(%s) {\n", fn.rets.typ, fn.libName, fn.libArgList(true, true))
		fmt.Fprintf(w, "\t")
		if fn.rets.typ != "void" {
			fmt.Fprintf(w, "return ")
		}
		fmt.Fprintf(w, "_g_%s(%s);\n", fn.libName, fn.libArgList(true, false))
		fmt.Fprintf(w, "}\n\n")
	}
}

func (f *fn) generate(w io.Writer) {
	fmt.Fprintf(w, "func %s(%s)", f.name, f.paramList())
	ret := f.rets.list()
	if len(ret) > 0 {
		fmt.Fprintf(w, " %s ", ret)
	}
	fmt.Fprintf(w, "{\n")
	fmt.Fprintf(w, "\t")
	if !f.rets.isVoid() {
		fmt.Fprintf(w, "r0 := ")
	}
	fmt.Fprintf(w, "C.%s(%s)\n", f.libName, f.argList())
	if !f.rets.isVoid() {
		errSrc := f.rets.errorSrc(f.libName)
		if len(errSrc) > 0 {
			fmt.Fprintf(w, "\t%s\n", errSrc)
		}
		fmt.Fprintf(w, "\treturn\n")
	}
	fmt.Fprintf(w, "}\n\n")
}

// argList returns source code fragments representing p parameter in a C call.
// Slices are translated into 2 syscall parameters: pointer to the first element and length.
func (p *param) argList() []string {
	goType := cArgToGo(p.typ)
	var s string
	switch {
	case goType == "":
		return []string{""}
	case goType == "unsafe.Pointer":
		return []string{p.name}
	case goType[0] == '*':
		return []string{fmt.Sprintf("(%s)(unsafe.Pointer(%s))", goType, p.name)}
	default:
		s = p.name
	}
	return []string{fmt.Sprintf("%s(%s)", goType, s)}
}

func cArgToGo(t string) string {
	t, _ = strings.CutPrefix(t, "const ")
	if t == "void" {
		return ""
	}
	if strings.Contains(t, "void*") {
		return "unsafe.Pointer"
	}
	if strings.HasSuffix(t, "*") {
		// Remove all trailing '*' characters.
		var i, n int
		for i = len(t) - 1; i >= 0; i-- {
			if t[i] != '*' {
				break
			}
			n++
		}
		s := cArgToGo(t[:i+1])
		s = strings.Repeat("*", n) + s
		return s
	}
	// Map C types with spaces to cgo special-cased types.
	switch t {
	case "signed char":
		t = "schar"
	case "unsigned char":
		t = "uchar"
	case "unsigned short":
		t = "ushort"
	case "unsigned int":
		t = "uint"
	case "unsigned long":
		t = "ulong"
	case "long long":
		t = "longlong"
	case "unsigned long long":
		t = "ulonglong"
	}
	return "C." + t
}

func cTypeToGo(t string) string {
	t, _ = strings.CutPrefix(t, "const ")
	if t == "void" {
		return ""
	}
	if strings.HasSuffix(t, "void*") {
		return "unsafe.Pointer"
	}
	if strings.HasSuffix(t, "*") {
		// Remove all trailing '*' characters.
		var i, n int
		for i = len(t) - 1; i >= 0; i-- {
			if t[i] != '*' {
				break
			}
			n++
		}
		s := cTypeToGo(t[:i+1])
		s = strings.Repeat("*", n) + s
		return s
	}
	var s string
	switch t {
	case "int8_t":
		s = "int8"
	case "uint8_t":
		s = "uint8"
	case "int16_t":
		s = "int16"
	case "uint16_t":
		s = "uint16"
	case "int32_t":
		s = "int32"
	case "uint32_t":
		s = "uint32"
	case "int64_t":
		s = "int64"
	case "uint64_t":
		s = "uint64"
	case "int":
		s = "int32"
	case "unsigned int":
		s = "uint32"
	case "long":
		s = "int64"
	case "unsigned long":
		s = "uint64"
	case "size_t":
		s = "int"
	case "uintptr_t":
		s = "uintptr"
	case "char", "unsigned char":
		s = "byte"
	default:
		s = strings.ToUpper(t[:1]) + t[1:]
	}
	return s
}

func (p *param) libArgList(paramNames, paramTypes bool) []string {
	var s string
	if paramTypes {
		s += p.typ
	}
	if paramNames && p.typ != "void" {
		if len(s) > 0 {
			s += " "
		}
		s += "_arg" + strconv.Itoa(p.tmpVarIdx)
	}
	return []string{s}
}

// toParams converts r into slice of *Param.
func (r *rets) toParams() []*param {
	ps := make([]*param, 0, 2)
	if len(r.name) > 0 && !r.isVoid() && !r.errorOnly {
		ps = append(ps, &param{name: r.name, typ: cTypeToGo(r.typ), tmpVarIdx: len(ps)})
	}
	if r.returnsError {
		ps = append(ps, &param{name: "err", typ: "error", tmpVarIdx: len(ps)})
	}
	return ps
}

// list returns source code of syscall return parameters.
func (r *rets) list() string {
	s := join(r.toParams(), func(p *param) string { return p.name + " " + p.typ }, ", ")
	if len(s) > 0 {
		s = "(" + s + ")"
	} else if r.fnMaybeAbsent {
		s = "(err error)"
	}
	return s
}

func (r *rets) useLongHandleErrorCode(retvar, msg string) string {
	const code = `if %s {
		err = newError(%q)
	}`
	var cond string
	if strings.HasSuffix(r.typ, "*") || strings.HasSuffix(strings.ToUpper(r.typ), "_PTR") {
		cond = retvar + " == nil"
	} else {
		cond = strings.Replace(r.failCond, "retval", retvar, 1)
	}
	return fmt.Sprintf(code, cond, msg)
}

func (r *rets) isVoid() bool {
	return r.typ == "void"
}

// errorSrc returns source code that sets return parameters.
func (r *rets) errorSrc(fnName string) string {
	if r.isVoid() {
		return ""
	}
	if r.name == "" || r.errorOnly {
		return r.useLongHandleErrorCode("r0", fnName)
	}
	goType := cTypeToGo(r.typ)
	s := ""
	switch {
	case goType[0] == '*':
		s = fmt.Sprintf("%s = (%s)(unsafe.Pointer(r0))", r.name, goType)
	default:
		s = fmt.Sprintf("%s = %s(r0)", r.name, goType)
	}
	if !r.returnsError {
		return s
	}
	return s + "\n\t" + r.useLongHandleErrorCode(r.name, fnName)
}

// paramList returns source code for function f parameters.
func (f *fn) paramList() string {
	return join(f.params, func(p *param) string { return p.name + " " + cTypeToGo(p.typ) }, ", ")
}

func syscalldot() string {
	return "syscall."
}

// argList returns source code for C parameters for function f.
func (f *fn) argList() string {
	a := make([]string, 0, len(f.params))
	for _, p := range f.params {
		a = append(a, p.argList()...)
	}
	a = slices.DeleteFunc(a, func(s string) bool {
		return s == ""
	})
	return strings.Join(a, ", ")
}

// libArgList returns source code for C parameters for function f.
func (f *fn) libArgList(paramNames, paramTypes bool) string {
	a := make([]string, 0, len(f.params))
	for _, p := range f.params {
		a = append(a, p.libArgList(paramNames, paramTypes)...)
	}
	a = slices.DeleteFunc(a, func(s string) bool {
		return s == ""
	})
	return strings.Join(a, ", ")
}

// join concatenates parameters ps into a string with sep separator.
// Each parameter is converted into string by applying fn to it
// before conversion.
func join(ps []*param, fn func(*param) string, sep string) string {
	if len(ps) == 0 {
		return ""
	}
	a := make([]string, 0, len(ps))
	for _, p := range ps {
		a = append(a, fn(p))
	}
	return strings.Join(a, sep)
}
