//go:build cgo

package ossl

import "C"

type Point_conversion_form_t = C.point_conversion_form_t

type OPENSSL_INIT_SETTINGS_PTR = C.OPENSSL_INIT_SETTINGS_PTR
type OSSL_LIB_CTX_PTR = C.OSSL_LIB_CTX_PTR
type OSSL_PROVIDER_PTR = C.OSSL_PROVIDER_PTR
type ENGINE_PTR = C.ENGINE_PTR
type EVP_PKEY_PTR = C.EVP_PKEY_PTR
type EVP_PKEY_CTX_PTR = C.EVP_PKEY_CTX_PTR
type EVP_MD_PTR = C.EVP_MD_PTR
type EVP_MD_CTX_PTR = C.EVP_MD_CTX_PTR
type HMAC_CTX_PTR = C.HMAC_CTX_PTR
type EVP_CIPHER_PTR = C.EVP_CIPHER_PTR
type EVP_CIPHER_CTX_PTR = C.EVP_CIPHER_CTX_PTR
type EC_KEY_PTR = C.EC_KEY_PTR
type EC_POINT_PTR = C.EC_POINT_PTR
type EC_GROUP_PTR = C.EC_GROUP_PTR
type RSA_PTR = C.RSA_PTR
type BIGNUM_PTR = C.BIGNUM_PTR
type BN_CTX_PTR = C.BN_CTX_PTR
type EVP_MAC_PTR = C.EVP_MAC_PTR
type EVP_MAC_CTX_PTR = C.EVP_MAC_CTX_PTR
type OSSL_PARAM_BLD_PTR = C.OSSL_PARAM_BLD_PTR
type OSSL_PARAM_PTR = C.OSSL_PARAM_PTR
type CRYPTO_THREADID_PTR = C.CRYPTO_THREADID_PTR
type EVP_SIGNATURE_PTR = C.EVP_SIGNATURE_PTR
type DSA_PTR = C.DSA_PTR
type EVP_KDF_PTR = C.EVP_KDF_PTR
type EVP_KDF_CTX_PTR = C.EVP_KDF_CTX_PTR
type MD5_CTX_PTR = C.MD5_CTX_PTR
type SHA_CTX_PTR = C.SHA_CTX_PTR
