// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo

#include "textflag.h"
 
TEXT _mkcgo_dlopen_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_dlopen(SB)
GLOBL   ·_mkcgo_dlopen_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_dlopen_trampoline_addr(SB)/8, $_mkcgo_dlopen_trampoline<>(SB)

TEXT _mkcgo_dlsym_trampoline<>(SB),NOSPLIT,$0-0
    JMP _mkcgo_dlsym(SB)
GLOBL   ·_mkcgo_dlsym_trampoline_addr(SB), RODATA, $8
DATA    ·_mkcgo_dlsym_trampoline_addr(SB)/8, $_mkcgo_dlsym_trampoline<>(SB)

