// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo && unix

package ossl

import (
	"runtime"
	"unsafe"
)

var _ = runtime.GOOS

var _mkcgoAlwaysFalse__mkcgoEscapePtr_dl bool
var _mkcgoEscapeSink__mkcgoEscapePtr_dl unsafe.Pointer

// _mkcgoEscapePtr_dl forces p to escape to the heap.
// This implementation is also used in the standard library:
// https://github.com/golang/go/blob/f71432d223eeb2139b460957817400750fd13655/src/internal/abi/escape.go#L24-L33
func _mkcgoEscapePtr_dl(p unsafe.Pointer) unsafe.Pointer {
	if _mkcgoAlwaysFalse__mkcgoEscapePtr_dl {
		_mkcgoEscapeSink__mkcgoEscapePtr_dl = p
	}
	return p
}

//go:cgo_import_dynamic _mkcgo_dlclose dlclose ""
//go:cgo_import_dynamic _mkcgo_dlerror dlerror ""
//go:cgo_import_dynamic _mkcgo_dlopen dlopen ""
//go:cgo_import_dynamic _mkcgo_dlsym dlsym ""

var _mkcgo_dlclose_trampoline_addr uintptr

func Dlclose(handle unsafe.Pointer) int32 {
	r0, _ := syscallN(0, _mkcgo_dlclose_trampoline_addr, uintptr(handle))
	return int32(r0)
}

var _mkcgo_dlerror_trampoline_addr uintptr

func Dlerror() *byte {
	r0, _ := syscallN(0, _mkcgo_dlerror_trampoline_addr)
	return (*byte)(unsafe.Pointer(r0))
}

var _mkcgo_dlopen_trampoline_addr uintptr

func Dlopen(path *byte, flags int32) unsafe.Pointer {
	r0, _ := syscallN(0, _mkcgo_dlopen_trampoline_addr, uintptr(_mkcgoEscapePtr_dl(unsafe.Pointer(path))), uintptr(flags))
	return unsafe.Pointer(r0)
}

var _mkcgo_dlsym_trampoline_addr uintptr

func Dlsym(handle unsafe.Pointer, symbol *byte) unsafe.Pointer {
	r0, _ := syscallN(0, _mkcgo_dlsym_trampoline_addr, uintptr(handle), uintptr(_mkcgoEscapePtr_dl(unsafe.Pointer(symbol))))
	return unsafe.Pointer(r0)
}
