// Code generated by mkcgo. DO NOT EDIT.

#include "ossl.h"
#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>

#ifdef _WIN32
#include <windows.h>
#define dlsym GetProcAddress
#else
#include <dlfcn.h>
#endif

BIGNUM_PTR (*_g_BN_bin2bn)(const unsigned char*, int, BIGNUM_PTR);
int (*_g_BN_bn2bin)(const BIGNUM_PTR, unsigned char*);
int (*_g_BN_bn2binpad)(const BIGNUM_PTR, unsigned char*, int);
int (*_g_BN_bn2lebinpad)(const BIGNUM_PTR, unsigned char*, int);
void (*_g_BN_clear)(BIGNUM_PTR);
void (*_g_BN_clear_free)(BIGNUM_PTR);
void (*_g_BN_free)(BIGNUM_PTR);
BIGNUM_PTR (*_g_BN_lebin2bn)(const unsigned char*, int, BIGNUM_PTR);
BIGNUM_PTR (*_g_BN_new)(void);
int (*_g_BN_num_bits)(const BIGNUM_PTR);
int (*_g_CRYPTO_THREADID_set_callback)(threadid_func);
void (*_g_CRYPTO_THREADID_set_numeric)(CRYPTO_THREADID_PTR, unsigned long);
void (*_g_CRYPTO_free)(void*, const char*, int);
void* (*_g_CRYPTO_malloc)(size_t, const char*, int);
int (*_g_CRYPTO_num_locks)(void);
void (*_g_CRYPTO_set_locking_callback)(locking_func);
void (*_g_DSA_free)(DSA_PTR);
int (*_g_DSA_generate_key)(DSA_PTR);
void (*_g_DSA_get0_key)(const DSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*);
void (*_g_DSA_get0_pqg)(const DSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*, const BIGNUM_PTR*);
DSA_PTR (*_g_DSA_new)(void);
int (*_g_DSA_set0_key)(DSA_PTR, BIGNUM_PTR, BIGNUM_PTR);
int (*_g_DSA_set0_pqg)(DSA_PTR, BIGNUM_PTR, BIGNUM_PTR, BIGNUM_PTR);
void (*_g_EC_GROUP_free)(EC_GROUP_PTR);
EC_GROUP_PTR (*_g_EC_GROUP_new_by_curve_name)(int);
void (*_g_EC_KEY_free)(EC_KEY_PTR);
const EC_GROUP_PTR (*_g_EC_KEY_get0_group)(const EC_KEY_PTR);
const BIGNUM_PTR (*_g_EC_KEY_get0_private_key)(const EC_KEY_PTR);
const EC_POINT_PTR (*_g_EC_KEY_get0_public_key)(const EC_KEY_PTR);
EC_KEY_PTR (*_g_EC_KEY_new_by_curve_name)(int);
int (*_g_EC_KEY_set_private_key)(EC_KEY_PTR, const BIGNUM_PTR);
int (*_g_EC_KEY_set_public_key)(EC_KEY_PTR, const EC_POINT_PTR);
int (*_g_EC_KEY_set_public_key_affine_coordinates)(EC_KEY_PTR, BIGNUM_PTR, BIGNUM_PTR);
void (*_g_EC_POINT_free)(EC_POINT_PTR);
int (*_g_EC_POINT_get_affine_coordinates_GFp)(const EC_GROUP_PTR, const EC_POINT_PTR, BIGNUM_PTR, BIGNUM_PTR, BN_CTX_PTR);
int (*_g_EC_POINT_mul)(const EC_GROUP_PTR, EC_POINT_PTR, const BIGNUM_PTR, const EC_POINT_PTR, const BIGNUM_PTR, BN_CTX_PTR);
EC_POINT_PTR (*_g_EC_POINT_new)(const EC_GROUP_PTR);
int (*_g_EC_POINT_oct2point)(const EC_GROUP_PTR, EC_POINT_PTR, const unsigned char*, size_t, BN_CTX_PTR);
size_t (*_g_EC_POINT_point2oct)(const EC_GROUP_PTR, const EC_POINT_PTR, point_conversion_form_t, unsigned char*, size_t, BN_CTX_PTR);
int (*_g_EC_POINT_set_affine_coordinates)(const EC_GROUP_PTR, EC_POINT_PTR, const BIGNUM_PTR, const BIGNUM_PTR, BN_CTX_PTR);
void (*_g_ERR_clear_error)(void);
void (*_g_ERR_error_string_n)(unsigned long, char*, size_t);
unsigned long (*_g_ERR_get_error_all)(const char**, int*, const char**, const char**, int*);
unsigned long (*_g_ERR_get_error_line)(const char**, int*);
void (*_g_ERR_load_crypto_strings)(void);
void (*_g_ERR_remove_thread_state)(const CRYPTO_THREADID_PTR);
int (*_g_EVP_CIPHER_CTX_ctrl)(EVP_CIPHER_CTX_PTR, int, int, void*);
void (*_g_EVP_CIPHER_CTX_free)(EVP_CIPHER_CTX_PTR);
EVP_CIPHER_CTX_PTR (*_g_EVP_CIPHER_CTX_new)(void);
int (*_g_EVP_CIPHER_CTX_set_key_length)(EVP_CIPHER_CTX_PTR, int);
int (*_g_EVP_CIPHER_CTX_set_padding)(EVP_CIPHER_CTX_PTR, int);
int (*_g_EVP_CIPHER_block_size)(const EVP_CIPHER_PTR);
EVP_CIPHER_PTR (*_g_EVP_CIPHER_fetch)(OSSL_LIB_CTX_PTR, const char*, const char*);
const char* (*_g_EVP_CIPHER_get0_name)(const EVP_CIPHER_PTR);
int (*_g_EVP_CIPHER_get_block_size)(const EVP_CIPHER_PTR);
int (*_g_EVP_CipherInit_ex)(EVP_CIPHER_CTX_PTR, const EVP_CIPHER_PTR, ENGINE_PTR, const unsigned char*, const unsigned char*, int);
int (*_g_EVP_CipherUpdate)(EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
int (*_g_EVP_DecryptFinal_ex)(EVP_CIPHER_CTX_PTR, unsigned char*, int*);
int (*_g_EVP_DecryptInit_ex)(EVP_CIPHER_CTX_PTR, const EVP_CIPHER_PTR, ENGINE_PTR, const unsigned char*, const unsigned char*);
int (*_g_EVP_DecryptUpdate)(EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
int (*_g_EVP_Digest)(const void*, size_t, unsigned char*, unsigned int*, const EVP_MD_PTR, ENGINE_PTR);
int (*_g_EVP_DigestFinal)(EVP_MD_CTX_PTR, unsigned char*, unsigned int*);
int (*_g_EVP_DigestInit)(EVP_MD_CTX_PTR, const EVP_MD_PTR);
int (*_g_EVP_DigestInit_ex)(EVP_MD_CTX_PTR, const EVP_MD_PTR, ENGINE_PTR);
int (*_g_EVP_DigestSign)(EVP_MD_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_DigestSignFinal)(EVP_MD_CTX_PTR, unsigned char*, size_t*);
int (*_g_EVP_DigestSignInit)(EVP_MD_CTX_PTR, EVP_PKEY_CTX_PTR*, const EVP_MD_PTR, ENGINE_PTR, EVP_PKEY_PTR);
int (*_g_EVP_DigestUpdate)(EVP_MD_CTX_PTR, const void*, size_t);
int (*_g_EVP_DigestVerify)(EVP_MD_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t);
int (*_g_EVP_DigestVerifyFinal)(EVP_MD_CTX_PTR, const unsigned char*, size_t);
int (*_g_EVP_DigestVerifyInit)(EVP_MD_CTX_PTR, EVP_PKEY_CTX_PTR*, const EVP_MD_PTR, ENGINE_PTR, EVP_PKEY_PTR);
int (*_g_EVP_EncryptFinal_ex)(EVP_CIPHER_CTX_PTR, unsigned char*, int*);
int (*_g_EVP_EncryptInit_ex)(EVP_CIPHER_CTX_PTR, const EVP_CIPHER_PTR, ENGINE_PTR, const unsigned char*, const unsigned char*);
int (*_g_EVP_EncryptUpdate)(EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int);
void (*_g_EVP_KDF_CTX_free)(EVP_KDF_CTX_PTR);
size_t (*_g_EVP_KDF_CTX_get_kdf_size)(EVP_KDF_CTX_PTR);
EVP_KDF_CTX_PTR (*_g_EVP_KDF_CTX_new)(EVP_KDF_PTR);
int (*_g_EVP_KDF_CTX_set_params)(EVP_KDF_CTX_PTR, const OSSL_PARAM_PTR);
int (*_g_EVP_KDF_derive)(EVP_KDF_CTX_PTR, unsigned char*, size_t, const OSSL_PARAM_PTR);
EVP_KDF_PTR (*_g_EVP_KDF_fetch)(OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_KDF_free)(EVP_KDF_PTR);
EVP_MAC_CTX_PTR (*_g_EVP_MAC_CTX_dup)(const EVP_MAC_CTX_PTR);
void (*_g_EVP_MAC_CTX_free)(EVP_MAC_CTX_PTR);
EVP_MAC_CTX_PTR (*_g_EVP_MAC_CTX_new)(EVP_MAC_PTR);
int (*_g_EVP_MAC_CTX_set_params)(EVP_MAC_CTX_PTR, const OSSL_PARAM_PTR);
EVP_MAC_PTR (*_g_EVP_MAC_fetch)(OSSL_LIB_CTX_PTR, const char*, const char*);
int (*_g_EVP_MAC_final)(EVP_MAC_CTX_PTR, unsigned char*, size_t*, size_t);
int (*_g_EVP_MAC_init)(EVP_MAC_CTX_PTR, const unsigned char*, size_t, const OSSL_PARAM_PTR);
int (*_g_EVP_MAC_update)(EVP_MAC_CTX_PTR, const unsigned char*, size_t);
int (*_g_EVP_MD_CTX_copy)(EVP_MD_CTX_PTR, const EVP_MD_CTX_PTR);
int (*_g_EVP_MD_CTX_copy_ex)(EVP_MD_CTX_PTR, const EVP_MD_CTX_PTR);
EVP_MD_CTX_PTR (*_g_EVP_MD_CTX_create)(void);
void (*_g_EVP_MD_CTX_destroy)(EVP_MD_CTX_PTR);
void (*_g_EVP_MD_CTX_free)(EVP_MD_CTX_PTR);
EVP_MD_CTX_PTR (*_g_EVP_MD_CTX_new)(void);
int (*_g_EVP_MD_block_size)(const EVP_MD_PTR);
EVP_MD_PTR (*_g_EVP_MD_fetch)(OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_MD_free)(EVP_MD_PTR);
const char* (*_g_EVP_MD_get0_name)(const EVP_MD_PTR);
const OSSL_PROVIDER_PTR (*_g_EVP_MD_get0_provider)(const EVP_MD_PTR);
int (*_g_EVP_MD_get_block_size)(const EVP_MD_PTR);
int (*_g_EVP_MD_get_size)(const EVP_MD_PTR);
int (*_g_EVP_MD_size)(const EVP_MD_PTR);
int (*_g_EVP_PKEY_CTX_add1_hkdf_info)(EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_ctrl)(EVP_PKEY_CTX_PTR, int, int, int, int, void*);
void (*_g_EVP_PKEY_CTX_free)(EVP_PKEY_CTX_PTR);
EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new)(EVP_PKEY_PTR, ENGINE_PTR);
EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new_from_pkey)(OSSL_LIB_CTX_PTR, EVP_PKEY_PTR, const char*);
EVP_PKEY_CTX_PTR (*_g_EVP_PKEY_CTX_new_id)(int, ENGINE_PTR);
int (*_g_EVP_PKEY_CTX_set0_rsa_oaep_label)(EVP_PKEY_CTX_PTR, void*, int);
int (*_g_EVP_PKEY_CTX_set1_hkdf_key)(EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_set1_hkdf_salt)(EVP_PKEY_CTX_PTR, const unsigned char*, int);
int (*_g_EVP_PKEY_CTX_set_hkdf_md)(EVP_PKEY_CTX_PTR, const EVP_MD_PTR);
int (*_g_EVP_PKEY_CTX_set_hkdf_mode)(EVP_PKEY_CTX_PTR, int);
EVP_PKEY_PTR (*_g_EVP_PKEY_Q_keygen_EC)(OSSL_LIB_CTX_PTR, const char*, const char*, const char*);
EVP_PKEY_PTR (*_g_EVP_PKEY_Q_keygen_ED25519)(OSSL_LIB_CTX_PTR, const char*, const char*);
EVP_PKEY_PTR (*_g_EVP_PKEY_Q_keygen_RSA)(OSSL_LIB_CTX_PTR, const char*, const char*, size_t);
int (*_g_EVP_PKEY_assign)(EVP_PKEY_PTR, int, void*);
int (*_g_EVP_PKEY_bits)(const EVP_PKEY_PTR);
int (*_g_EVP_PKEY_decrypt)(EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_decrypt_init)(EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_derive)(EVP_PKEY_CTX_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_derive_init)(EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_derive_set_peer)(EVP_PKEY_CTX_PTR, EVP_PKEY_PTR);
int (*_g_EVP_PKEY_encrypt)(EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_encrypt_init)(EVP_PKEY_CTX_PTR);
void (*_g_EVP_PKEY_free)(EVP_PKEY_PTR);
int (*_g_EVP_PKEY_fromdata)(EVP_PKEY_CTX_PTR, EVP_PKEY_PTR*, int, OSSL_PARAM_PTR);
int (*_g_EVP_PKEY_fromdata_init)(EVP_PKEY_CTX_PTR);
void* (*_g_EVP_PKEY_get0)(const EVP_PKEY_PTR);
const DSA_PTR (*_g_EVP_PKEY_get0_DSA)(const EVP_PKEY_PTR);
const EC_KEY_PTR (*_g_EVP_PKEY_get0_EC_KEY)(const EVP_PKEY_PTR);
RSA_PTR (*_g_EVP_PKEY_get1_RSA)(EVP_PKEY_PTR);
size_t (*_g_EVP_PKEY_get1_encoded_public_key)(EVP_PKEY_PTR, unsigned char**);
int (*_g_EVP_PKEY_get_bits)(const EVP_PKEY_PTR);
int (*_g_EVP_PKEY_get_bn_param)(const EVP_PKEY_PTR, const char*, BIGNUM_PTR*);
int (*_g_EVP_PKEY_get_raw_private_key)(const EVP_PKEY_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_get_raw_public_key)(const EVP_PKEY_PTR, unsigned char*, size_t*);
int (*_g_EVP_PKEY_get_size)(const EVP_PKEY_PTR);
int (*_g_EVP_PKEY_keygen)(EVP_PKEY_CTX_PTR, EVP_PKEY_PTR*);
int (*_g_EVP_PKEY_keygen_init)(EVP_PKEY_CTX_PTR);
EVP_PKEY_PTR (*_g_EVP_PKEY_new)(void);
EVP_PKEY_PTR (*_g_EVP_PKEY_new_raw_private_key)(int, ENGINE_PTR, const unsigned char*, size_t);
EVP_PKEY_PTR (*_g_EVP_PKEY_new_raw_public_key)(int, ENGINE_PTR, const unsigned char*, size_t);
int (*_g_EVP_PKEY_paramgen)(EVP_PKEY_CTX_PTR, EVP_PKEY_PTR*);
int (*_g_EVP_PKEY_paramgen_init)(EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_set1_EC_KEY)(EVP_PKEY_PTR, EC_KEY_PTR);
int (*_g_EVP_PKEY_set1_encoded_public_key)(EVP_PKEY_PTR, const unsigned char*, size_t);
int (*_g_EVP_PKEY_sign)(EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t);
int (*_g_EVP_PKEY_sign_init)(EVP_PKEY_CTX_PTR);
int (*_g_EVP_PKEY_size)(const EVP_PKEY_PTR);
int (*_g_EVP_PKEY_up_ref)(EVP_PKEY_PTR);
int (*_g_EVP_PKEY_verify)(EVP_PKEY_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t);
int (*_g_EVP_PKEY_verify_init)(EVP_PKEY_CTX_PTR);
EVP_SIGNATURE_PTR (*_g_EVP_SIGNATURE_fetch)(OSSL_LIB_CTX_PTR, const char*, const char*);
void (*_g_EVP_SIGNATURE_free)(EVP_SIGNATURE_PTR);
EVP_CIPHER_PTR (*_g_EVP_aes_128_cbc)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_128_ctr)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_128_ecb)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_128_gcm)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_192_cbc)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_192_ctr)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_192_ecb)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_192_gcm)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_256_cbc)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_256_ctr)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_256_ecb)(void);
EVP_CIPHER_PTR (*_g_EVP_aes_256_gcm)(void);
int (*_g_EVP_default_properties_enable_fips)(OSSL_LIB_CTX_PTR, int);
int (*_g_EVP_default_properties_is_fips_enabled)(OSSL_LIB_CTX_PTR);
EVP_CIPHER_PTR (*_g_EVP_des_cbc)(void);
EVP_CIPHER_PTR (*_g_EVP_des_ecb)(void);
EVP_CIPHER_PTR (*_g_EVP_des_ede3_cbc)(void);
EVP_CIPHER_PTR (*_g_EVP_des_ede3_ecb)(void);
const EVP_MD_PTR (*_g_EVP_md4)(void);
const EVP_MD_PTR (*_g_EVP_md5)(void);
const EVP_MD_PTR (*_g_EVP_md5_sha1)(void);
EVP_CIPHER_PTR (*_g_EVP_rc4)(void);
const EVP_MD_PTR (*_g_EVP_sha1)(void);
const EVP_MD_PTR (*_g_EVP_sha224)(void);
const EVP_MD_PTR (*_g_EVP_sha256)(void);
const EVP_MD_PTR (*_g_EVP_sha384)(void);
const EVP_MD_PTR (*_g_EVP_sha3_224)(void);
const EVP_MD_PTR (*_g_EVP_sha3_256)(void);
const EVP_MD_PTR (*_g_EVP_sha3_384)(void);
const EVP_MD_PTR (*_g_EVP_sha3_512)(void);
const EVP_MD_PTR (*_g_EVP_sha512)(void);
int (*_g_FIPS_mode)(void);
int (*_g_FIPS_mode_set)(int);
void (*_g_HMAC_CTX_cleanup)(HMAC_CTX_PTR);
int (*_g_HMAC_CTX_copy)(HMAC_CTX_PTR, HMAC_CTX_PTR);
void (*_g_HMAC_CTX_free)(HMAC_CTX_PTR);
void (*_g_HMAC_CTX_init)(HMAC_CTX_PTR);
HMAC_CTX_PTR (*_g_HMAC_CTX_new)(void);
int (*_g_HMAC_Final)(HMAC_CTX_PTR, unsigned char*, unsigned int*);
int (*_g_HMAC_Init_ex)(HMAC_CTX_PTR, const void*, int, const EVP_MD_PTR, ENGINE_PTR);
int (*_g_HMAC_Update)(HMAC_CTX_PTR, const unsigned char*, size_t);
int (*_g_MD5_Final)(unsigned char*, MD5_CTX_PTR);
int (*_g_MD5_Init)(MD5_CTX_PTR);
int (*_g_MD5_Update)(MD5_CTX_PTR, const void*, size_t);
const char* (*_g_OBJ_nid2sn)(int);
void (*_g_OPENSSL_add_all_algorithms_conf)(void);
void (*_g_OPENSSL_init)(void);
int (*_g_OPENSSL_init_crypto)(uint64_t, const OPENSSL_INIT_SETTINGS_PTR);
void (*_g_OSSL_PARAM_BLD_free)(OSSL_PARAM_BLD_PTR);
OSSL_PARAM_BLD_PTR (*_g_OSSL_PARAM_BLD_new)(void);
int (*_g_OSSL_PARAM_BLD_push_BN)(OSSL_PARAM_BLD_PTR, const char*, const BIGNUM_PTR);
int (*_g_OSSL_PARAM_BLD_push_int32)(OSSL_PARAM_BLD_PTR, const char*, int32_t);
int (*_g_OSSL_PARAM_BLD_push_octet_string)(OSSL_PARAM_BLD_PTR, const char*, const void*, size_t);
int (*_g_OSSL_PARAM_BLD_push_utf8_string)(OSSL_PARAM_BLD_PTR, const char*, const char*, size_t);
OSSL_PARAM_PTR (*_g_OSSL_PARAM_BLD_to_param)(OSSL_PARAM_BLD_PTR);
void (*_g_OSSL_PARAM_free)(OSSL_PARAM_PTR);
int (*_g_OSSL_PROVIDER_available)(OSSL_LIB_CTX_PTR, const char*);
const char* (*_g_OSSL_PROVIDER_get0_name)(const OSSL_PROVIDER_PTR);
OSSL_PROVIDER_PTR (*_g_OSSL_PROVIDER_try_load)(OSSL_LIB_CTX_PTR, const char*, int);
const char* (*_g_OpenSSL_version)(int);
int (*_g_PKCS5_PBKDF2_HMAC)(const char*, int, const unsigned char*, int, int, const EVP_MD_PTR, int, unsigned char*);
int (*_g_RAND_bytes)(unsigned char*, int);
void (*_g_RSA_free)(RSA_PTR);
void (*_g_RSA_get0_crt_params)(const RSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*, const BIGNUM_PTR*);
void (*_g_RSA_get0_factors)(const RSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*);
void (*_g_RSA_get0_key)(const RSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*, const BIGNUM_PTR*);
RSA_PTR (*_g_RSA_new)(void);
int (*_g_RSA_set0_crt_params)(RSA_PTR, BIGNUM_PTR, BIGNUM_PTR, BIGNUM_PTR);
int (*_g_RSA_set0_factors)(RSA_PTR, BIGNUM_PTR, BIGNUM_PTR);
int (*_g_RSA_set0_key)(RSA_PTR, BIGNUM_PTR, BIGNUM_PTR, BIGNUM_PTR);
int (*_g_SHA1_Final)(unsigned char*, SHA_CTX_PTR);
int (*_g_SHA1_Init)(SHA_CTX_PTR);
int (*_g_SHA1_Update)(SHA_CTX_PTR, const void*, size_t);
const char* (*_g_SSLeay_version)(int);
BIGNUM_PTR (*_g_bn_expand2)(BIGNUM_PTR, int);

void __mkcgoLoad_crypto(void* handle) {
	_g_BN_bin2bn = (BIGNUM_PTR (*)(const unsigned char*, int, BIGNUM_PTR))dlsym(handle, "BN_bin2bn");
	_g_BN_bn2bin = (int (*)(const BIGNUM_PTR, unsigned char*))dlsym(handle, "BN_bn2bin");
	_g_BN_bn2binpad = (int (*)(const BIGNUM_PTR, unsigned char*, int))dlsym(handle, "BN_bn2binpad");
	_g_BN_bn2lebinpad = (int (*)(const BIGNUM_PTR, unsigned char*, int))dlsym(handle, "BN_bn2lebinpad");
	_g_BN_clear = (void (*)(BIGNUM_PTR))dlsym(handle, "BN_clear");
	_g_BN_clear_free = (void (*)(BIGNUM_PTR))dlsym(handle, "BN_clear_free");
	_g_BN_free = (void (*)(BIGNUM_PTR))dlsym(handle, "BN_free");
	_g_BN_lebin2bn = (BIGNUM_PTR (*)(const unsigned char*, int, BIGNUM_PTR))dlsym(handle, "BN_lebin2bn");
	_g_BN_new = (BIGNUM_PTR (*)(void))dlsym(handle, "BN_new");
	_g_BN_num_bits = (int (*)(const BIGNUM_PTR))dlsym(handle, "BN_num_bits");
	_g_CRYPTO_THREADID_set_callback = (int (*)(threadid_func))dlsym(handle, "CRYPTO_THREADID_set_callback");
	_g_CRYPTO_THREADID_set_numeric = (void (*)(CRYPTO_THREADID_PTR, unsigned long))dlsym(handle, "CRYPTO_THREADID_set_numeric");
	_g_CRYPTO_free = (void (*)(void*, const char*, int))dlsym(handle, "CRYPTO_free");
	_g_CRYPTO_malloc = (void* (*)(size_t, const char*, int))dlsym(handle, "CRYPTO_malloc");
	_g_CRYPTO_num_locks = (int (*)(void))dlsym(handle, "CRYPTO_num_locks");
	_g_CRYPTO_set_locking_callback = (void (*)(locking_func))dlsym(handle, "CRYPTO_set_locking_callback");
	_g_DSA_free = (void (*)(DSA_PTR))dlsym(handle, "DSA_free");
	_g_DSA_generate_key = (int (*)(DSA_PTR))dlsym(handle, "DSA_generate_key");
	_g_DSA_get0_key = (void (*)(const DSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*))dlsym(handle, "DSA_get0_key");
	_g_DSA_get0_pqg = (void (*)(const DSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*, const BIGNUM_PTR*))dlsym(handle, "DSA_get0_pqg");
	_g_DSA_new = (DSA_PTR (*)(void))dlsym(handle, "DSA_new");
	_g_DSA_set0_key = (int (*)(DSA_PTR, BIGNUM_PTR, BIGNUM_PTR))dlsym(handle, "DSA_set0_key");
	_g_DSA_set0_pqg = (int (*)(DSA_PTR, BIGNUM_PTR, BIGNUM_PTR, BIGNUM_PTR))dlsym(handle, "DSA_set0_pqg");
	_g_EC_GROUP_free = (void (*)(EC_GROUP_PTR))dlsym(handle, "EC_GROUP_free");
	_g_EC_GROUP_new_by_curve_name = (EC_GROUP_PTR (*)(int))dlsym(handle, "EC_GROUP_new_by_curve_name");
	_g_EC_KEY_free = (void (*)(EC_KEY_PTR))dlsym(handle, "EC_KEY_free");
	_g_EC_KEY_get0_group = (const EC_GROUP_PTR (*)(const EC_KEY_PTR))dlsym(handle, "EC_KEY_get0_group");
	_g_EC_KEY_get0_private_key = (const BIGNUM_PTR (*)(const EC_KEY_PTR))dlsym(handle, "EC_KEY_get0_private_key");
	_g_EC_KEY_get0_public_key = (const EC_POINT_PTR (*)(const EC_KEY_PTR))dlsym(handle, "EC_KEY_get0_public_key");
	_g_EC_KEY_new_by_curve_name = (EC_KEY_PTR (*)(int))dlsym(handle, "EC_KEY_new_by_curve_name");
	_g_EC_KEY_set_private_key = (int (*)(EC_KEY_PTR, const BIGNUM_PTR))dlsym(handle, "EC_KEY_set_private_key");
	_g_EC_KEY_set_public_key = (int (*)(EC_KEY_PTR, const EC_POINT_PTR))dlsym(handle, "EC_KEY_set_public_key");
	_g_EC_KEY_set_public_key_affine_coordinates = (int (*)(EC_KEY_PTR, BIGNUM_PTR, BIGNUM_PTR))dlsym(handle, "EC_KEY_set_public_key_affine_coordinates");
	_g_EC_POINT_free = (void (*)(EC_POINT_PTR))dlsym(handle, "EC_POINT_free");
	_g_EC_POINT_get_affine_coordinates_GFp = (int (*)(const EC_GROUP_PTR, const EC_POINT_PTR, BIGNUM_PTR, BIGNUM_PTR, BN_CTX_PTR))dlsym(handle, "EC_POINT_get_affine_coordinates_GFp");
	_g_EC_POINT_mul = (int (*)(const EC_GROUP_PTR, EC_POINT_PTR, const BIGNUM_PTR, const EC_POINT_PTR, const BIGNUM_PTR, BN_CTX_PTR))dlsym(handle, "EC_POINT_mul");
	_g_EC_POINT_new = (EC_POINT_PTR (*)(const EC_GROUP_PTR))dlsym(handle, "EC_POINT_new");
	_g_EC_POINT_oct2point = (int (*)(const EC_GROUP_PTR, EC_POINT_PTR, const unsigned char*, size_t, BN_CTX_PTR))dlsym(handle, "EC_POINT_oct2point");
	_g_EC_POINT_point2oct = (size_t (*)(const EC_GROUP_PTR, const EC_POINT_PTR, point_conversion_form_t, unsigned char*, size_t, BN_CTX_PTR))dlsym(handle, "EC_POINT_point2oct");
	_g_EC_POINT_set_affine_coordinates = (int (*)(const EC_GROUP_PTR, EC_POINT_PTR, const BIGNUM_PTR, const BIGNUM_PTR, BN_CTX_PTR))dlsym(handle, "EC_POINT_set_affine_coordinates");
	_g_ERR_clear_error = (void (*)(void))dlsym(handle, "ERR_clear_error");
	_g_ERR_error_string_n = (void (*)(unsigned long, char*, size_t))dlsym(handle, "ERR_error_string_n");
	_g_ERR_get_error_all = (unsigned long (*)(const char**, int*, const char**, const char**, int*))dlsym(handle, "ERR_get_error_all");
	_g_ERR_get_error_line = (unsigned long (*)(const char**, int*))dlsym(handle, "ERR_get_error_line");
	_g_ERR_load_crypto_strings = (void (*)(void))dlsym(handle, "ERR_load_crypto_strings");
	_g_ERR_remove_thread_state = (void (*)(const CRYPTO_THREADID_PTR))dlsym(handle, "ERR_remove_thread_state");
	_g_EVP_CIPHER_CTX_ctrl = (int (*)(EVP_CIPHER_CTX_PTR, int, int, void*))dlsym(handle, "EVP_CIPHER_CTX_ctrl");
	_g_EVP_CIPHER_CTX_free = (void (*)(EVP_CIPHER_CTX_PTR))dlsym(handle, "EVP_CIPHER_CTX_free");
	_g_EVP_CIPHER_CTX_new = (EVP_CIPHER_CTX_PTR (*)(void))dlsym(handle, "EVP_CIPHER_CTX_new");
	_g_EVP_CIPHER_CTX_set_key_length = (int (*)(EVP_CIPHER_CTX_PTR, int))dlsym(handle, "EVP_CIPHER_CTX_set_key_length");
	_g_EVP_CIPHER_CTX_set_padding = (int (*)(EVP_CIPHER_CTX_PTR, int))dlsym(handle, "EVP_CIPHER_CTX_set_padding");
	_g_EVP_CIPHER_block_size = (int (*)(const EVP_CIPHER_PTR))dlsym(handle, "EVP_CIPHER_block_size");
	_g_EVP_CIPHER_fetch = (EVP_CIPHER_PTR (*)(OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_CIPHER_fetch");
	_g_EVP_CIPHER_get0_name = (const char* (*)(const EVP_CIPHER_PTR))dlsym(handle, "EVP_CIPHER_get0_name");
	_g_EVP_CIPHER_get_block_size = (int (*)(const EVP_CIPHER_PTR))dlsym(handle, "EVP_CIPHER_get_block_size");
	_g_EVP_CipherInit_ex = (int (*)(EVP_CIPHER_CTX_PTR, const EVP_CIPHER_PTR, ENGINE_PTR, const unsigned char*, const unsigned char*, int))dlsym(handle, "EVP_CipherInit_ex");
	_g_EVP_CipherUpdate = (int (*)(EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int))dlsym(handle, "EVP_CipherUpdate");
	_g_EVP_DecryptFinal_ex = (int (*)(EVP_CIPHER_CTX_PTR, unsigned char*, int*))dlsym(handle, "EVP_DecryptFinal_ex");
	_g_EVP_DecryptInit_ex = (int (*)(EVP_CIPHER_CTX_PTR, const EVP_CIPHER_PTR, ENGINE_PTR, const unsigned char*, const unsigned char*))dlsym(handle, "EVP_DecryptInit_ex");
	_g_EVP_DecryptUpdate = (int (*)(EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int))dlsym(handle, "EVP_DecryptUpdate");
	_g_EVP_Digest = (int (*)(const void*, size_t, unsigned char*, unsigned int*, const EVP_MD_PTR, ENGINE_PTR))dlsym(handle, "EVP_Digest");
	_g_EVP_DigestFinal = (int (*)(EVP_MD_CTX_PTR, unsigned char*, unsigned int*))dlsym(handle, "EVP_DigestFinal");
	_g_EVP_DigestInit = (int (*)(EVP_MD_CTX_PTR, const EVP_MD_PTR))dlsym(handle, "EVP_DigestInit");
	_g_EVP_DigestInit_ex = (int (*)(EVP_MD_CTX_PTR, const EVP_MD_PTR, ENGINE_PTR))dlsym(handle, "EVP_DigestInit_ex");
	_g_EVP_DigestSign = (int (*)(EVP_MD_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t))dlsym(handle, "EVP_DigestSign");
	_g_EVP_DigestSignFinal = (int (*)(EVP_MD_CTX_PTR, unsigned char*, size_t*))dlsym(handle, "EVP_DigestSignFinal");
	_g_EVP_DigestSignInit = (int (*)(EVP_MD_CTX_PTR, EVP_PKEY_CTX_PTR*, const EVP_MD_PTR, ENGINE_PTR, EVP_PKEY_PTR))dlsym(handle, "EVP_DigestSignInit");
	_g_EVP_DigestUpdate = (int (*)(EVP_MD_CTX_PTR, const void*, size_t))dlsym(handle, "EVP_DigestUpdate");
	_g_EVP_DigestVerify = (int (*)(EVP_MD_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t))dlsym(handle, "EVP_DigestVerify");
	_g_EVP_DigestVerifyFinal = (int (*)(EVP_MD_CTX_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_DigestVerifyFinal");
	_g_EVP_DigestVerifyInit = (int (*)(EVP_MD_CTX_PTR, EVP_PKEY_CTX_PTR*, const EVP_MD_PTR, ENGINE_PTR, EVP_PKEY_PTR))dlsym(handle, "EVP_DigestVerifyInit");
	_g_EVP_EncryptFinal_ex = (int (*)(EVP_CIPHER_CTX_PTR, unsigned char*, int*))dlsym(handle, "EVP_EncryptFinal_ex");
	_g_EVP_EncryptInit_ex = (int (*)(EVP_CIPHER_CTX_PTR, const EVP_CIPHER_PTR, ENGINE_PTR, const unsigned char*, const unsigned char*))dlsym(handle, "EVP_EncryptInit_ex");
	_g_EVP_EncryptUpdate = (int (*)(EVP_CIPHER_CTX_PTR, unsigned char*, int*, const unsigned char*, int))dlsym(handle, "EVP_EncryptUpdate");
	_g_EVP_KDF_CTX_free = (void (*)(EVP_KDF_CTX_PTR))dlsym(handle, "EVP_KDF_CTX_free");
	_g_EVP_KDF_CTX_get_kdf_size = (size_t (*)(EVP_KDF_CTX_PTR))dlsym(handle, "EVP_KDF_CTX_get_kdf_size");
	_g_EVP_KDF_CTX_new = (EVP_KDF_CTX_PTR (*)(EVP_KDF_PTR))dlsym(handle, "EVP_KDF_CTX_new");
	_g_EVP_KDF_CTX_set_params = (int (*)(EVP_KDF_CTX_PTR, const OSSL_PARAM_PTR))dlsym(handle, "EVP_KDF_CTX_set_params");
	_g_EVP_KDF_derive = (int (*)(EVP_KDF_CTX_PTR, unsigned char*, size_t, const OSSL_PARAM_PTR))dlsym(handle, "EVP_KDF_derive");
	_g_EVP_KDF_fetch = (EVP_KDF_PTR (*)(OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_KDF_fetch");
	_g_EVP_KDF_free = (void (*)(EVP_KDF_PTR))dlsym(handle, "EVP_KDF_free");
	_g_EVP_MAC_CTX_dup = (EVP_MAC_CTX_PTR (*)(const EVP_MAC_CTX_PTR))dlsym(handle, "EVP_MAC_CTX_dup");
	_g_EVP_MAC_CTX_free = (void (*)(EVP_MAC_CTX_PTR))dlsym(handle, "EVP_MAC_CTX_free");
	_g_EVP_MAC_CTX_new = (EVP_MAC_CTX_PTR (*)(EVP_MAC_PTR))dlsym(handle, "EVP_MAC_CTX_new");
	_g_EVP_MAC_CTX_set_params = (int (*)(EVP_MAC_CTX_PTR, const OSSL_PARAM_PTR))dlsym(handle, "EVP_MAC_CTX_set_params");
	_g_EVP_MAC_fetch = (EVP_MAC_PTR (*)(OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_MAC_fetch");
	_g_EVP_MAC_final = (int (*)(EVP_MAC_CTX_PTR, unsigned char*, size_t*, size_t))dlsym(handle, "EVP_MAC_final");
	_g_EVP_MAC_init = (int (*)(EVP_MAC_CTX_PTR, const unsigned char*, size_t, const OSSL_PARAM_PTR))dlsym(handle, "EVP_MAC_init");
	_g_EVP_MAC_update = (int (*)(EVP_MAC_CTX_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_MAC_update");
	_g_EVP_MD_CTX_copy = (int (*)(EVP_MD_CTX_PTR, const EVP_MD_CTX_PTR))dlsym(handle, "EVP_MD_CTX_copy");
	_g_EVP_MD_CTX_copy_ex = (int (*)(EVP_MD_CTX_PTR, const EVP_MD_CTX_PTR))dlsym(handle, "EVP_MD_CTX_copy_ex");
	_g_EVP_MD_CTX_create = (EVP_MD_CTX_PTR (*)(void))dlsym(handle, "EVP_MD_CTX_create");
	_g_EVP_MD_CTX_destroy = (void (*)(EVP_MD_CTX_PTR))dlsym(handle, "EVP_MD_CTX_destroy");
	_g_EVP_MD_CTX_free = (void (*)(EVP_MD_CTX_PTR))dlsym(handle, "EVP_MD_CTX_free");
	_g_EVP_MD_CTX_new = (EVP_MD_CTX_PTR (*)(void))dlsym(handle, "EVP_MD_CTX_new");
	_g_EVP_MD_block_size = (int (*)(const EVP_MD_PTR))dlsym(handle, "EVP_MD_block_size");
	_g_EVP_MD_fetch = (EVP_MD_PTR (*)(OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_MD_fetch");
	_g_EVP_MD_free = (void (*)(EVP_MD_PTR))dlsym(handle, "EVP_MD_free");
	_g_EVP_MD_get0_name = (const char* (*)(const EVP_MD_PTR))dlsym(handle, "EVP_MD_get0_name");
	_g_EVP_MD_get0_provider = (const OSSL_PROVIDER_PTR (*)(const EVP_MD_PTR))dlsym(handle, "EVP_MD_get0_provider");
	_g_EVP_MD_get_block_size = (int (*)(const EVP_MD_PTR))dlsym(handle, "EVP_MD_get_block_size");
	_g_EVP_MD_get_size = (int (*)(const EVP_MD_PTR))dlsym(handle, "EVP_MD_get_size");
	_g_EVP_MD_size = (int (*)(const EVP_MD_PTR))dlsym(handle, "EVP_MD_size");
	_g_EVP_PKEY_CTX_add1_hkdf_info = (int (*)(EVP_PKEY_CTX_PTR, const unsigned char*, int))dlsym(handle, "EVP_PKEY_CTX_add1_hkdf_info");
	_g_EVP_PKEY_CTX_ctrl = (int (*)(EVP_PKEY_CTX_PTR, int, int, int, int, void*))dlsym(handle, "EVP_PKEY_CTX_ctrl");
	_g_EVP_PKEY_CTX_free = (void (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_CTX_free");
	_g_EVP_PKEY_CTX_new = (EVP_PKEY_CTX_PTR (*)(EVP_PKEY_PTR, ENGINE_PTR))dlsym(handle, "EVP_PKEY_CTX_new");
	_g_EVP_PKEY_CTX_new_from_pkey = (EVP_PKEY_CTX_PTR (*)(OSSL_LIB_CTX_PTR, EVP_PKEY_PTR, const char*))dlsym(handle, "EVP_PKEY_CTX_new_from_pkey");
	_g_EVP_PKEY_CTX_new_id = (EVP_PKEY_CTX_PTR (*)(int, ENGINE_PTR))dlsym(handle, "EVP_PKEY_CTX_new_id");
	_g_EVP_PKEY_CTX_set0_rsa_oaep_label = (int (*)(EVP_PKEY_CTX_PTR, void*, int))dlsym(handle, "EVP_PKEY_CTX_set0_rsa_oaep_label");
	_g_EVP_PKEY_CTX_set1_hkdf_key = (int (*)(EVP_PKEY_CTX_PTR, const unsigned char*, int))dlsym(handle, "EVP_PKEY_CTX_set1_hkdf_key");
	_g_EVP_PKEY_CTX_set1_hkdf_salt = (int (*)(EVP_PKEY_CTX_PTR, const unsigned char*, int))dlsym(handle, "EVP_PKEY_CTX_set1_hkdf_salt");
	_g_EVP_PKEY_CTX_set_hkdf_md = (int (*)(EVP_PKEY_CTX_PTR, const EVP_MD_PTR))dlsym(handle, "EVP_PKEY_CTX_set_hkdf_md");
	_g_EVP_PKEY_CTX_set_hkdf_mode = (int (*)(EVP_PKEY_CTX_PTR, int))dlsym(handle, "EVP_PKEY_CTX_set_hkdf_mode");
	_g_EVP_PKEY_Q_keygen_EC = (EVP_PKEY_PTR (*)(OSSL_LIB_CTX_PTR, const char*, const char*, const char*))dlsym(handle, "EVP_PKEY_Q_keygen");
	_g_EVP_PKEY_Q_keygen_ED25519 = (EVP_PKEY_PTR (*)(OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_PKEY_Q_keygen");
	_g_EVP_PKEY_Q_keygen_RSA = (EVP_PKEY_PTR (*)(OSSL_LIB_CTX_PTR, const char*, const char*, size_t))dlsym(handle, "EVP_PKEY_Q_keygen");
	_g_EVP_PKEY_assign = (int (*)(EVP_PKEY_PTR, int, void*))dlsym(handle, "EVP_PKEY_assign");
	_g_EVP_PKEY_bits = (int (*)(const EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_bits");
	_g_EVP_PKEY_decrypt = (int (*)(EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_decrypt");
	_g_EVP_PKEY_decrypt_init = (int (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_decrypt_init");
	_g_EVP_PKEY_derive = (int (*)(EVP_PKEY_CTX_PTR, unsigned char*, size_t*))dlsym(handle, "EVP_PKEY_derive");
	_g_EVP_PKEY_derive_init = (int (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_derive_init");
	_g_EVP_PKEY_derive_set_peer = (int (*)(EVP_PKEY_CTX_PTR, EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_derive_set_peer");
	_g_EVP_PKEY_encrypt = (int (*)(EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_encrypt");
	_g_EVP_PKEY_encrypt_init = (int (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_encrypt_init");
	_g_EVP_PKEY_free = (void (*)(EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_free");
	_g_EVP_PKEY_fromdata = (int (*)(EVP_PKEY_CTX_PTR, EVP_PKEY_PTR*, int, OSSL_PARAM_PTR))dlsym(handle, "EVP_PKEY_fromdata");
	_g_EVP_PKEY_fromdata_init = (int (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_fromdata_init");
	_g_EVP_PKEY_get0 = (void* (*)(const EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get0");
	_g_EVP_PKEY_get0_DSA = (const DSA_PTR (*)(const EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get0_DSA");
	_g_EVP_PKEY_get0_EC_KEY = (const EC_KEY_PTR (*)(const EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get0_EC_KEY");
	_g_EVP_PKEY_get1_RSA = (RSA_PTR (*)(EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get1_RSA");
	_g_EVP_PKEY_get1_encoded_public_key = (size_t (*)(EVP_PKEY_PTR, unsigned char**))dlsym(handle, "EVP_PKEY_get1_encoded_public_key");
	_g_EVP_PKEY_get_bits = (int (*)(const EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get_bits");
	_g_EVP_PKEY_get_bn_param = (int (*)(const EVP_PKEY_PTR, const char*, BIGNUM_PTR*))dlsym(handle, "EVP_PKEY_get_bn_param");
	_g_EVP_PKEY_get_raw_private_key = (int (*)(const EVP_PKEY_PTR, unsigned char*, size_t*))dlsym(handle, "EVP_PKEY_get_raw_private_key");
	_g_EVP_PKEY_get_raw_public_key = (int (*)(const EVP_PKEY_PTR, unsigned char*, size_t*))dlsym(handle, "EVP_PKEY_get_raw_public_key");
	_g_EVP_PKEY_get_size = (int (*)(const EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_get_size");
	_g_EVP_PKEY_keygen = (int (*)(EVP_PKEY_CTX_PTR, EVP_PKEY_PTR*))dlsym(handle, "EVP_PKEY_keygen");
	_g_EVP_PKEY_keygen_init = (int (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_keygen_init");
	_g_EVP_PKEY_new = (EVP_PKEY_PTR (*)(void))dlsym(handle, "EVP_PKEY_new");
	_g_EVP_PKEY_new_raw_private_key = (EVP_PKEY_PTR (*)(int, ENGINE_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_new_raw_private_key");
	_g_EVP_PKEY_new_raw_public_key = (EVP_PKEY_PTR (*)(int, ENGINE_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_new_raw_public_key");
	_g_EVP_PKEY_paramgen = (int (*)(EVP_PKEY_CTX_PTR, EVP_PKEY_PTR*))dlsym(handle, "EVP_PKEY_paramgen");
	_g_EVP_PKEY_paramgen_init = (int (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_paramgen_init");
	_g_EVP_PKEY_set1_EC_KEY = (int (*)(EVP_PKEY_PTR, EC_KEY_PTR))dlsym(handle, "EVP_PKEY_set1_EC_KEY");
	_g_EVP_PKEY_set1_encoded_public_key = (int (*)(EVP_PKEY_PTR, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_set1_encoded_public_key");
	_g_EVP_PKEY_sign = (int (*)(EVP_PKEY_CTX_PTR, unsigned char*, size_t*, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_sign");
	_g_EVP_PKEY_sign_init = (int (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_sign_init");
	_g_EVP_PKEY_size = (int (*)(const EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_size");
	_g_EVP_PKEY_up_ref = (int (*)(EVP_PKEY_PTR))dlsym(handle, "EVP_PKEY_up_ref");
	_g_EVP_PKEY_verify = (int (*)(EVP_PKEY_CTX_PTR, const unsigned char*, size_t, const unsigned char*, size_t))dlsym(handle, "EVP_PKEY_verify");
	_g_EVP_PKEY_verify_init = (int (*)(EVP_PKEY_CTX_PTR))dlsym(handle, "EVP_PKEY_verify_init");
	_g_EVP_SIGNATURE_fetch = (EVP_SIGNATURE_PTR (*)(OSSL_LIB_CTX_PTR, const char*, const char*))dlsym(handle, "EVP_SIGNATURE_fetch");
	_g_EVP_SIGNATURE_free = (void (*)(EVP_SIGNATURE_PTR))dlsym(handle, "EVP_SIGNATURE_free");
	_g_EVP_aes_128_cbc = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_128_cbc");
	_g_EVP_aes_128_ctr = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_128_ctr");
	_g_EVP_aes_128_ecb = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_128_ecb");
	_g_EVP_aes_128_gcm = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_128_gcm");
	_g_EVP_aes_192_cbc = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_192_cbc");
	_g_EVP_aes_192_ctr = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_192_ctr");
	_g_EVP_aes_192_ecb = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_192_ecb");
	_g_EVP_aes_192_gcm = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_192_gcm");
	_g_EVP_aes_256_cbc = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_256_cbc");
	_g_EVP_aes_256_ctr = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_256_ctr");
	_g_EVP_aes_256_ecb = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_256_ecb");
	_g_EVP_aes_256_gcm = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_aes_256_gcm");
	_g_EVP_default_properties_enable_fips = (int (*)(OSSL_LIB_CTX_PTR, int))dlsym(handle, "EVP_default_properties_enable_fips");
	_g_EVP_default_properties_is_fips_enabled = (int (*)(OSSL_LIB_CTX_PTR))dlsym(handle, "EVP_default_properties_is_fips_enabled");
	_g_EVP_des_cbc = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_des_cbc");
	_g_EVP_des_ecb = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_des_ecb");
	_g_EVP_des_ede3_cbc = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_des_ede3_cbc");
	_g_EVP_des_ede3_ecb = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_des_ede3_ecb");
	_g_EVP_md4 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_md4");
	_g_EVP_md5 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_md5");
	_g_EVP_md5_sha1 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_md5_sha1");
	_g_EVP_rc4 = (EVP_CIPHER_PTR (*)(void))dlsym(handle, "EVP_rc4");
	_g_EVP_sha1 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha1");
	_g_EVP_sha224 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha224");
	_g_EVP_sha256 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha256");
	_g_EVP_sha384 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha384");
	_g_EVP_sha3_224 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha3_224");
	_g_EVP_sha3_256 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha3_256");
	_g_EVP_sha3_384 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha3_384");
	_g_EVP_sha3_512 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha3_512");
	_g_EVP_sha512 = (const EVP_MD_PTR (*)(void))dlsym(handle, "EVP_sha512");
	_g_FIPS_mode = (int (*)(void))dlsym(handle, "FIPS_mode");
	_g_FIPS_mode_set = (int (*)(int))dlsym(handle, "FIPS_mode_set");
	_g_HMAC_CTX_cleanup = (void (*)(HMAC_CTX_PTR))dlsym(handle, "HMAC_CTX_cleanup");
	_g_HMAC_CTX_copy = (int (*)(HMAC_CTX_PTR, HMAC_CTX_PTR))dlsym(handle, "HMAC_CTX_copy");
	_g_HMAC_CTX_free = (void (*)(HMAC_CTX_PTR))dlsym(handle, "HMAC_CTX_free");
	_g_HMAC_CTX_init = (void (*)(HMAC_CTX_PTR))dlsym(handle, "HMAC_CTX_init");
	_g_HMAC_CTX_new = (HMAC_CTX_PTR (*)(void))dlsym(handle, "HMAC_CTX_new");
	_g_HMAC_Final = (int (*)(HMAC_CTX_PTR, unsigned char*, unsigned int*))dlsym(handle, "HMAC_Final");
	_g_HMAC_Init_ex = (int (*)(HMAC_CTX_PTR, const void*, int, const EVP_MD_PTR, ENGINE_PTR))dlsym(handle, "HMAC_Init_ex");
	_g_HMAC_Update = (int (*)(HMAC_CTX_PTR, const unsigned char*, size_t))dlsym(handle, "HMAC_Update");
	_g_MD5_Final = (int (*)(unsigned char*, MD5_CTX_PTR))dlsym(handle, "MD5_Final");
	_g_MD5_Init = (int (*)(MD5_CTX_PTR))dlsym(handle, "MD5_Init");
	_g_MD5_Update = (int (*)(MD5_CTX_PTR, const void*, size_t))dlsym(handle, "MD5_Update");
	_g_OBJ_nid2sn = (const char* (*)(int))dlsym(handle, "OBJ_nid2sn");
	_g_OPENSSL_add_all_algorithms_conf = (void (*)(void))dlsym(handle, "OPENSSL_add_all_algorithms_conf");
	_g_OPENSSL_init = (void (*)(void))dlsym(handle, "OPENSSL_init");
	_g_OPENSSL_init_crypto = (int (*)(uint64_t, const OPENSSL_INIT_SETTINGS_PTR))dlsym(handle, "OPENSSL_init_crypto");
	_g_OSSL_PARAM_BLD_free = (void (*)(OSSL_PARAM_BLD_PTR))dlsym(handle, "OSSL_PARAM_BLD_free");
	_g_OSSL_PARAM_BLD_new = (OSSL_PARAM_BLD_PTR (*)(void))dlsym(handle, "OSSL_PARAM_BLD_new");
	_g_OSSL_PARAM_BLD_push_BN = (int (*)(OSSL_PARAM_BLD_PTR, const char*, const BIGNUM_PTR))dlsym(handle, "OSSL_PARAM_BLD_push_BN");
	_g_OSSL_PARAM_BLD_push_int32 = (int (*)(OSSL_PARAM_BLD_PTR, const char*, int32_t))dlsym(handle, "OSSL_PARAM_BLD_push_int32");
	_g_OSSL_PARAM_BLD_push_octet_string = (int (*)(OSSL_PARAM_BLD_PTR, const char*, const void*, size_t))dlsym(handle, "OSSL_PARAM_BLD_push_octet_string");
	_g_OSSL_PARAM_BLD_push_utf8_string = (int (*)(OSSL_PARAM_BLD_PTR, const char*, const char*, size_t))dlsym(handle, "OSSL_PARAM_BLD_push_utf8_string");
	_g_OSSL_PARAM_BLD_to_param = (OSSL_PARAM_PTR (*)(OSSL_PARAM_BLD_PTR))dlsym(handle, "OSSL_PARAM_BLD_to_param");
	_g_OSSL_PARAM_free = (void (*)(OSSL_PARAM_PTR))dlsym(handle, "OSSL_PARAM_free");
	_g_OSSL_PROVIDER_available = (int (*)(OSSL_LIB_CTX_PTR, const char*))dlsym(handle, "OSSL_PROVIDER_available");
	_g_OSSL_PROVIDER_get0_name = (const char* (*)(const OSSL_PROVIDER_PTR))dlsym(handle, "OSSL_PROVIDER_get0_name");
	_g_OSSL_PROVIDER_try_load = (OSSL_PROVIDER_PTR (*)(OSSL_LIB_CTX_PTR, const char*, int))dlsym(handle, "OSSL_PROVIDER_try_load");
	_g_OpenSSL_version = (const char* (*)(int))dlsym(handle, "OpenSSL_version");
	_g_PKCS5_PBKDF2_HMAC = (int (*)(const char*, int, const unsigned char*, int, int, const EVP_MD_PTR, int, unsigned char*))dlsym(handle, "PKCS5_PBKDF2_HMAC");
	_g_RAND_bytes = (int (*)(unsigned char*, int))dlsym(handle, "RAND_bytes");
	_g_RSA_free = (void (*)(RSA_PTR))dlsym(handle, "RSA_free");
	_g_RSA_get0_crt_params = (void (*)(const RSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*, const BIGNUM_PTR*))dlsym(handle, "RSA_get0_crt_params");
	_g_RSA_get0_factors = (void (*)(const RSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*))dlsym(handle, "RSA_get0_factors");
	_g_RSA_get0_key = (void (*)(const RSA_PTR, const BIGNUM_PTR*, const BIGNUM_PTR*, const BIGNUM_PTR*))dlsym(handle, "RSA_get0_key");
	_g_RSA_new = (RSA_PTR (*)(void))dlsym(handle, "RSA_new");
	_g_RSA_set0_crt_params = (int (*)(RSA_PTR, BIGNUM_PTR, BIGNUM_PTR, BIGNUM_PTR))dlsym(handle, "RSA_set0_crt_params");
	_g_RSA_set0_factors = (int (*)(RSA_PTR, BIGNUM_PTR, BIGNUM_PTR))dlsym(handle, "RSA_set0_factors");
	_g_RSA_set0_key = (int (*)(RSA_PTR, BIGNUM_PTR, BIGNUM_PTR, BIGNUM_PTR))dlsym(handle, "RSA_set0_key");
	_g_SHA1_Final = (int (*)(unsigned char*, SHA_CTX_PTR))dlsym(handle, "SHA1_Final");
	_g_SHA1_Init = (int (*)(SHA_CTX_PTR))dlsym(handle, "SHA1_Init");
	_g_SHA1_Update = (int (*)(SHA_CTX_PTR, const void*, size_t))dlsym(handle, "SHA1_Update");
	_g_SSLeay_version = (const char* (*)(int))dlsym(handle, "SSLeay_version");
	_g_bn_expand2 = (BIGNUM_PTR (*)(BIGNUM_PTR, int))dlsym(handle, "bn_expand2");
}

BIGNUM_PTR BN_bin2bn(const unsigned char* _arg0, int _arg1, BIGNUM_PTR _arg2) {
	return _g_BN_bin2bn(_arg0, _arg1, _arg2);
}

int BN_bn2bin(const BIGNUM_PTR _arg0, unsigned char* _arg1) {
	return _g_BN_bn2bin(_arg0, _arg1);
}

int BN_bn2binpad(const BIGNUM_PTR _arg0, unsigned char* _arg1, int _arg2) {
	return _g_BN_bn2binpad(_arg0, _arg1, _arg2);
}

int BN_bn2lebinpad(const BIGNUM_PTR _arg0, unsigned char* _arg1, int _arg2) {
	return _g_BN_bn2lebinpad(_arg0, _arg1, _arg2);
}

void BN_clear(BIGNUM_PTR _arg0) {
	_g_BN_clear(_arg0);
}

void BN_clear_free(BIGNUM_PTR _arg0) {
	_g_BN_clear_free(_arg0);
}

void BN_free(BIGNUM_PTR _arg0) {
	_g_BN_free(_arg0);
}

BIGNUM_PTR BN_lebin2bn(const unsigned char* _arg0, int _arg1, BIGNUM_PTR _arg2) {
	return _g_BN_lebin2bn(_arg0, _arg1, _arg2);
}

BIGNUM_PTR BN_new(void) {
	return _g_BN_new();
}

int BN_num_bits(const BIGNUM_PTR _arg0) {
	return _g_BN_num_bits(_arg0);
}

int CRYPTO_THREADID_set_callback(threadid_func _arg0) {
	return _g_CRYPTO_THREADID_set_callback(_arg0);
}

void CRYPTO_THREADID_set_numeric(CRYPTO_THREADID_PTR _arg0, unsigned long _arg1) {
	_g_CRYPTO_THREADID_set_numeric(_arg0, _arg1);
}

void CRYPTO_free(void* _arg0, const char* _arg1, int _arg2) {
	_g_CRYPTO_free(_arg0, _arg1, _arg2);
}

void* CRYPTO_malloc(size_t _arg0, const char* _arg1, int _arg2) {
	return _g_CRYPTO_malloc(_arg0, _arg1, _arg2);
}

int CRYPTO_num_locks(void) {
	return _g_CRYPTO_num_locks();
}

void CRYPTO_set_locking_callback(locking_func _arg0) {
	_g_CRYPTO_set_locking_callback(_arg0);
}

void DSA_free(DSA_PTR _arg0) {
	_g_DSA_free(_arg0);
}

int DSA_generate_key(DSA_PTR _arg0) {
	return _g_DSA_generate_key(_arg0);
}

void DSA_get0_key(const DSA_PTR _arg0, const BIGNUM_PTR* _arg1, const BIGNUM_PTR* _arg2) {
	_g_DSA_get0_key(_arg0, _arg1, _arg2);
}

void DSA_get0_pqg(const DSA_PTR _arg0, const BIGNUM_PTR* _arg1, const BIGNUM_PTR* _arg2, const BIGNUM_PTR* _arg3) {
	_g_DSA_get0_pqg(_arg0, _arg1, _arg2, _arg3);
}

DSA_PTR DSA_new(void) {
	return _g_DSA_new();
}

int DSA_set0_key(DSA_PTR _arg0, BIGNUM_PTR _arg1, BIGNUM_PTR _arg2) {
	return _g_DSA_set0_key(_arg0, _arg1, _arg2);
}

int DSA_set0_pqg(DSA_PTR _arg0, BIGNUM_PTR _arg1, BIGNUM_PTR _arg2, BIGNUM_PTR _arg3) {
	return _g_DSA_set0_pqg(_arg0, _arg1, _arg2, _arg3);
}

void EC_GROUP_free(EC_GROUP_PTR _arg0) {
	_g_EC_GROUP_free(_arg0);
}

EC_GROUP_PTR EC_GROUP_new_by_curve_name(int _arg0) {
	return _g_EC_GROUP_new_by_curve_name(_arg0);
}

void EC_KEY_free(EC_KEY_PTR _arg0) {
	_g_EC_KEY_free(_arg0);
}

const EC_GROUP_PTR EC_KEY_get0_group(const EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_group(_arg0);
}

const BIGNUM_PTR EC_KEY_get0_private_key(const EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_private_key(_arg0);
}

const EC_POINT_PTR EC_KEY_get0_public_key(const EC_KEY_PTR _arg0) {
	return _g_EC_KEY_get0_public_key(_arg0);
}

EC_KEY_PTR EC_KEY_new_by_curve_name(int _arg0) {
	return _g_EC_KEY_new_by_curve_name(_arg0);
}

int EC_KEY_set_private_key(EC_KEY_PTR _arg0, const BIGNUM_PTR _arg1) {
	return _g_EC_KEY_set_private_key(_arg0, _arg1);
}

int EC_KEY_set_public_key(EC_KEY_PTR _arg0, const EC_POINT_PTR _arg1) {
	return _g_EC_KEY_set_public_key(_arg0, _arg1);
}

int EC_KEY_set_public_key_affine_coordinates(EC_KEY_PTR _arg0, BIGNUM_PTR _arg1, BIGNUM_PTR _arg2) {
	return _g_EC_KEY_set_public_key_affine_coordinates(_arg0, _arg1, _arg2);
}

void EC_POINT_free(EC_POINT_PTR _arg0) {
	_g_EC_POINT_free(_arg0);
}

int EC_POINT_get_affine_coordinates_GFp(const EC_GROUP_PTR _arg0, const EC_POINT_PTR _arg1, BIGNUM_PTR _arg2, BIGNUM_PTR _arg3, BN_CTX_PTR _arg4) {
	return _g_EC_POINT_get_affine_coordinates_GFp(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EC_POINT_mul(const EC_GROUP_PTR _arg0, EC_POINT_PTR _arg1, const BIGNUM_PTR _arg2, const EC_POINT_PTR _arg3, const BIGNUM_PTR _arg4, BN_CTX_PTR _arg5) {
	return _g_EC_POINT_mul(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

EC_POINT_PTR EC_POINT_new(const EC_GROUP_PTR _arg0) {
	return _g_EC_POINT_new(_arg0);
}

int EC_POINT_oct2point(const EC_GROUP_PTR _arg0, EC_POINT_PTR _arg1, const unsigned char* _arg2, size_t _arg3, BN_CTX_PTR _arg4) {
	return _g_EC_POINT_oct2point(_arg0, _arg1, _arg2, _arg3, _arg4);
}

size_t EC_POINT_point2oct(const EC_GROUP_PTR _arg0, const EC_POINT_PTR _arg1, point_conversion_form_t _arg2, unsigned char* _arg3, size_t _arg4, BN_CTX_PTR _arg5) {
	return _g_EC_POINT_point2oct(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int EC_POINT_set_affine_coordinates(const EC_GROUP_PTR _arg0, EC_POINT_PTR _arg1, const BIGNUM_PTR _arg2, const BIGNUM_PTR _arg3, BN_CTX_PTR _arg4) {
	return _g_EC_POINT_set_affine_coordinates(_arg0, _arg1, _arg2, _arg3, _arg4);
}

void ERR_clear_error(void) {
	_g_ERR_clear_error();
}

void ERR_error_string_n(unsigned long _arg0, char* _arg1, size_t _arg2) {
	_g_ERR_error_string_n(_arg0, _arg1, _arg2);
}

unsigned long ERR_get_error_all(const char** _arg0, int* _arg1, const char** _arg2, const char** _arg3, int* _arg4) {
	return _g_ERR_get_error_all(_arg0, _arg1, _arg2, _arg3, _arg4);
}

unsigned long ERR_get_error_line(const char** _arg0, int* _arg1) {
	return _g_ERR_get_error_line(_arg0, _arg1);
}

void ERR_load_crypto_strings(void) {
	_g_ERR_load_crypto_strings();
}

void ERR_remove_thread_state(const CRYPTO_THREADID_PTR _arg0) {
	_g_ERR_remove_thread_state(_arg0);
}

int EVP_CIPHER_CTX_ctrl(EVP_CIPHER_CTX_PTR _arg0, int _arg1, int _arg2, void* _arg3) {
	return _g_EVP_CIPHER_CTX_ctrl(_arg0, _arg1, _arg2, _arg3);
}

void EVP_CIPHER_CTX_free(EVP_CIPHER_CTX_PTR _arg0) {
	_g_EVP_CIPHER_CTX_free(_arg0);
}

EVP_CIPHER_CTX_PTR EVP_CIPHER_CTX_new(void) {
	return _g_EVP_CIPHER_CTX_new();
}

int EVP_CIPHER_CTX_set_key_length(EVP_CIPHER_CTX_PTR _arg0, int _arg1) {
	return _g_EVP_CIPHER_CTX_set_key_length(_arg0, _arg1);
}

int EVP_CIPHER_CTX_set_padding(EVP_CIPHER_CTX_PTR _arg0, int _arg1) {
	return _g_EVP_CIPHER_CTX_set_padding(_arg0, _arg1);
}

int EVP_CIPHER_block_size(const EVP_CIPHER_PTR _arg0) {
	return _g_EVP_CIPHER_block_size(_arg0);
}

EVP_CIPHER_PTR EVP_CIPHER_fetch(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_CIPHER_fetch(_arg0, _arg1, _arg2);
}

const char* EVP_CIPHER_get0_name(const EVP_CIPHER_PTR _arg0) {
	return _g_EVP_CIPHER_get0_name(_arg0);
}

int EVP_CIPHER_get_block_size(const EVP_CIPHER_PTR _arg0) {
	return _g_EVP_CIPHER_get_block_size(_arg0);
}

int EVP_CipherInit_ex(EVP_CIPHER_CTX_PTR _arg0, const EVP_CIPHER_PTR _arg1, ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4, int _arg5) {
	return _g_EVP_CipherInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int EVP_CipherUpdate(EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4) {
	return _g_EVP_CipherUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DecryptFinal_ex(EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2) {
	return _g_EVP_DecryptFinal_ex(_arg0, _arg1, _arg2);
}

int EVP_DecryptInit_ex(EVP_CIPHER_CTX_PTR _arg0, const EVP_CIPHER_PTR _arg1, ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4) {
	return _g_EVP_DecryptInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DecryptUpdate(EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4) {
	return _g_EVP_DecryptUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_Digest(const void* _arg0, size_t _arg1, unsigned char* _arg2, unsigned int* _arg3, const EVP_MD_PTR _arg4, ENGINE_PTR _arg5) {
	return _g_EVP_Digest(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

int EVP_DigestFinal(EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, unsigned int* _arg2) {
	return _g_EVP_DigestFinal(_arg0, _arg1, _arg2);
}

int EVP_DigestInit(EVP_MD_CTX_PTR _arg0, const EVP_MD_PTR _arg1) {
	return _g_EVP_DigestInit(_arg0, _arg1);
}

int EVP_DigestInit_ex(EVP_MD_CTX_PTR _arg0, const EVP_MD_PTR _arg1, ENGINE_PTR _arg2) {
	return _g_EVP_DigestInit_ex(_arg0, _arg1, _arg2);
}

int EVP_DigestSign(EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_DigestSign(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DigestSignFinal(EVP_MD_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2) {
	return _g_EVP_DigestSignFinal(_arg0, _arg1, _arg2);
}

int EVP_DigestSignInit(EVP_MD_CTX_PTR _arg0, EVP_PKEY_CTX_PTR* _arg1, const EVP_MD_PTR _arg2, ENGINE_PTR _arg3, EVP_PKEY_PTR _arg4) {
	return _g_EVP_DigestSignInit(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DigestUpdate(EVP_MD_CTX_PTR _arg0, const void* _arg1, size_t _arg2) {
	return _g_EVP_DigestUpdate(_arg0, _arg1, _arg2);
}

int EVP_DigestVerify(EVP_MD_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_DigestVerify(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_DigestVerifyFinal(EVP_MD_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2) {
	return _g_EVP_DigestVerifyFinal(_arg0, _arg1, _arg2);
}

int EVP_DigestVerifyInit(EVP_MD_CTX_PTR _arg0, EVP_PKEY_CTX_PTR* _arg1, const EVP_MD_PTR _arg2, ENGINE_PTR _arg3, EVP_PKEY_PTR _arg4) {
	return _g_EVP_DigestVerifyInit(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_EncryptFinal_ex(EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2) {
	return _g_EVP_EncryptFinal_ex(_arg0, _arg1, _arg2);
}

int EVP_EncryptInit_ex(EVP_CIPHER_CTX_PTR _arg0, const EVP_CIPHER_PTR _arg1, ENGINE_PTR _arg2, const unsigned char* _arg3, const unsigned char* _arg4) {
	return _g_EVP_EncryptInit_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_EncryptUpdate(EVP_CIPHER_CTX_PTR _arg0, unsigned char* _arg1, int* _arg2, const unsigned char* _arg3, int _arg4) {
	return _g_EVP_EncryptUpdate(_arg0, _arg1, _arg2, _arg3, _arg4);
}

void EVP_KDF_CTX_free(EVP_KDF_CTX_PTR _arg0) {
	_g_EVP_KDF_CTX_free(_arg0);
}

size_t EVP_KDF_CTX_get_kdf_size(EVP_KDF_CTX_PTR _arg0) {
	return _g_EVP_KDF_CTX_get_kdf_size(_arg0);
}

EVP_KDF_CTX_PTR EVP_KDF_CTX_new(EVP_KDF_PTR _arg0) {
	return _g_EVP_KDF_CTX_new(_arg0);
}

int EVP_KDF_CTX_set_params(EVP_KDF_CTX_PTR _arg0, const OSSL_PARAM_PTR _arg1) {
	return _g_EVP_KDF_CTX_set_params(_arg0, _arg1);
}

int EVP_KDF_derive(EVP_KDF_CTX_PTR _arg0, unsigned char* _arg1, size_t _arg2, const OSSL_PARAM_PTR _arg3) {
	return _g_EVP_KDF_derive(_arg0, _arg1, _arg2, _arg3);
}

EVP_KDF_PTR EVP_KDF_fetch(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_KDF_fetch(_arg0, _arg1, _arg2);
}

void EVP_KDF_free(EVP_KDF_PTR _arg0) {
	_g_EVP_KDF_free(_arg0);
}

EVP_MAC_CTX_PTR EVP_MAC_CTX_dup(const EVP_MAC_CTX_PTR _arg0) {
	return _g_EVP_MAC_CTX_dup(_arg0);
}

void EVP_MAC_CTX_free(EVP_MAC_CTX_PTR _arg0) {
	_g_EVP_MAC_CTX_free(_arg0);
}

EVP_MAC_CTX_PTR EVP_MAC_CTX_new(EVP_MAC_PTR _arg0) {
	return _g_EVP_MAC_CTX_new(_arg0);
}

int EVP_MAC_CTX_set_params(EVP_MAC_CTX_PTR _arg0, const OSSL_PARAM_PTR _arg1) {
	return _g_EVP_MAC_CTX_set_params(_arg0, _arg1);
}

EVP_MAC_PTR EVP_MAC_fetch(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_MAC_fetch(_arg0, _arg1, _arg2);
}

int EVP_MAC_final(EVP_MAC_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, size_t _arg3) {
	return _g_EVP_MAC_final(_arg0, _arg1, _arg2, _arg3);
}

int EVP_MAC_init(EVP_MAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const OSSL_PARAM_PTR _arg3) {
	return _g_EVP_MAC_init(_arg0, _arg1, _arg2, _arg3);
}

int EVP_MAC_update(EVP_MAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2) {
	return _g_EVP_MAC_update(_arg0, _arg1, _arg2);
}

int EVP_MD_CTX_copy(EVP_MD_CTX_PTR _arg0, const EVP_MD_CTX_PTR _arg1) {
	return _g_EVP_MD_CTX_copy(_arg0, _arg1);
}

int EVP_MD_CTX_copy_ex(EVP_MD_CTX_PTR _arg0, const EVP_MD_CTX_PTR _arg1) {
	return _g_EVP_MD_CTX_copy_ex(_arg0, _arg1);
}

EVP_MD_CTX_PTR EVP_MD_CTX_create(void) {
	return _g_EVP_MD_CTX_create();
}

void EVP_MD_CTX_destroy(EVP_MD_CTX_PTR _arg0) {
	_g_EVP_MD_CTX_destroy(_arg0);
}

void EVP_MD_CTX_free(EVP_MD_CTX_PTR _arg0) {
	_g_EVP_MD_CTX_free(_arg0);
}

EVP_MD_CTX_PTR EVP_MD_CTX_new(void) {
	return _g_EVP_MD_CTX_new();
}

int EVP_MD_block_size(const EVP_MD_PTR _arg0) {
	return _g_EVP_MD_block_size(_arg0);
}

EVP_MD_PTR EVP_MD_fetch(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_MD_fetch(_arg0, _arg1, _arg2);
}

void EVP_MD_free(EVP_MD_PTR _arg0) {
	_g_EVP_MD_free(_arg0);
}

const char* EVP_MD_get0_name(const EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get0_name(_arg0);
}

const OSSL_PROVIDER_PTR EVP_MD_get0_provider(const EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get0_provider(_arg0);
}

int EVP_MD_get_block_size(const EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get_block_size(_arg0);
}

int EVP_MD_get_size(const EVP_MD_PTR _arg0) {
	return _g_EVP_MD_get_size(_arg0);
}

int EVP_MD_size(const EVP_MD_PTR _arg0) {
	return _g_EVP_MD_size(_arg0);
}

int EVP_PKEY_CTX_add1_hkdf_info(EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2) {
	return _g_EVP_PKEY_CTX_add1_hkdf_info(_arg0, _arg1, _arg2);
}

int EVP_PKEY_CTX_ctrl(EVP_PKEY_CTX_PTR _arg0, int _arg1, int _arg2, int _arg3, int _arg4, void* _arg5) {
	return _g_EVP_PKEY_CTX_ctrl(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5);
}

void EVP_PKEY_CTX_free(EVP_PKEY_CTX_PTR _arg0) {
	_g_EVP_PKEY_CTX_free(_arg0);
}

EVP_PKEY_CTX_PTR EVP_PKEY_CTX_new(EVP_PKEY_PTR _arg0, ENGINE_PTR _arg1) {
	return _g_EVP_PKEY_CTX_new(_arg0, _arg1);
}

EVP_PKEY_CTX_PTR EVP_PKEY_CTX_new_from_pkey(OSSL_LIB_CTX_PTR _arg0, EVP_PKEY_PTR _arg1, const char* _arg2) {
	return _g_EVP_PKEY_CTX_new_from_pkey(_arg0, _arg1, _arg2);
}

EVP_PKEY_CTX_PTR EVP_PKEY_CTX_new_id(int _arg0, ENGINE_PTR _arg1) {
	return _g_EVP_PKEY_CTX_new_id(_arg0, _arg1);
}

int EVP_PKEY_CTX_set0_rsa_oaep_label(EVP_PKEY_CTX_PTR _arg0, void* _arg1, int _arg2) {
	return _g_EVP_PKEY_CTX_set0_rsa_oaep_label(_arg0, _arg1, _arg2);
}

int EVP_PKEY_CTX_set1_hkdf_key(EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2) {
	return _g_EVP_PKEY_CTX_set1_hkdf_key(_arg0, _arg1, _arg2);
}

int EVP_PKEY_CTX_set1_hkdf_salt(EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, int _arg2) {
	return _g_EVP_PKEY_CTX_set1_hkdf_salt(_arg0, _arg1, _arg2);
}

int EVP_PKEY_CTX_set_hkdf_md(EVP_PKEY_CTX_PTR _arg0, const EVP_MD_PTR _arg1) {
	return _g_EVP_PKEY_CTX_set_hkdf_md(_arg0, _arg1);
}

int EVP_PKEY_CTX_set_hkdf_mode(EVP_PKEY_CTX_PTR _arg0, int _arg1) {
	return _g_EVP_PKEY_CTX_set_hkdf_mode(_arg0, _arg1);
}

EVP_PKEY_PTR EVP_PKEY_Q_keygen_EC(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, const char* _arg3) {
	return _g_EVP_PKEY_Q_keygen_EC(_arg0, _arg1, _arg2, _arg3);
}

EVP_PKEY_PTR EVP_PKEY_Q_keygen_ED25519(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_PKEY_Q_keygen_ED25519(_arg0, _arg1, _arg2);
}

EVP_PKEY_PTR EVP_PKEY_Q_keygen_RSA(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2, size_t _arg3) {
	return _g_EVP_PKEY_Q_keygen_RSA(_arg0, _arg1, _arg2, _arg3);
}

int EVP_PKEY_assign(EVP_PKEY_PTR _arg0, int _arg1, void* _arg2) {
	return _g_EVP_PKEY_assign(_arg0, _arg1, _arg2);
}

int EVP_PKEY_bits(const EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_bits(_arg0);
}

int EVP_PKEY_decrypt(EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_PKEY_decrypt(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_PKEY_decrypt_init(EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_decrypt_init(_arg0);
}

int EVP_PKEY_derive(EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2) {
	return _g_EVP_PKEY_derive(_arg0, _arg1, _arg2);
}

int EVP_PKEY_derive_init(EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_derive_init(_arg0);
}

int EVP_PKEY_derive_set_peer(EVP_PKEY_CTX_PTR _arg0, EVP_PKEY_PTR _arg1) {
	return _g_EVP_PKEY_derive_set_peer(_arg0, _arg1);
}

int EVP_PKEY_encrypt(EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_PKEY_encrypt(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_PKEY_encrypt_init(EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_encrypt_init(_arg0);
}

void EVP_PKEY_free(EVP_PKEY_PTR _arg0) {
	_g_EVP_PKEY_free(_arg0);
}

int EVP_PKEY_fromdata(EVP_PKEY_CTX_PTR _arg0, EVP_PKEY_PTR* _arg1, int _arg2, OSSL_PARAM_PTR _arg3) {
	return _g_EVP_PKEY_fromdata(_arg0, _arg1, _arg2, _arg3);
}

int EVP_PKEY_fromdata_init(EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_fromdata_init(_arg0);
}

void* EVP_PKEY_get0(const EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get0(_arg0);
}

const DSA_PTR EVP_PKEY_get0_DSA(const EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get0_DSA(_arg0);
}

const EC_KEY_PTR EVP_PKEY_get0_EC_KEY(const EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get0_EC_KEY(_arg0);
}

RSA_PTR EVP_PKEY_get1_RSA(EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get1_RSA(_arg0);
}

size_t EVP_PKEY_get1_encoded_public_key(EVP_PKEY_PTR _arg0, unsigned char** _arg1) {
	return _g_EVP_PKEY_get1_encoded_public_key(_arg0, _arg1);
}

int EVP_PKEY_get_bits(const EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get_bits(_arg0);
}

int EVP_PKEY_get_bn_param(const EVP_PKEY_PTR _arg0, const char* _arg1, BIGNUM_PTR* _arg2) {
	return _g_EVP_PKEY_get_bn_param(_arg0, _arg1, _arg2);
}

int EVP_PKEY_get_raw_private_key(const EVP_PKEY_PTR _arg0, unsigned char* _arg1, size_t* _arg2) {
	return _g_EVP_PKEY_get_raw_private_key(_arg0, _arg1, _arg2);
}

int EVP_PKEY_get_raw_public_key(const EVP_PKEY_PTR _arg0, unsigned char* _arg1, size_t* _arg2) {
	return _g_EVP_PKEY_get_raw_public_key(_arg0, _arg1, _arg2);
}

int EVP_PKEY_get_size(const EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_get_size(_arg0);
}

int EVP_PKEY_keygen(EVP_PKEY_CTX_PTR _arg0, EVP_PKEY_PTR* _arg1) {
	return _g_EVP_PKEY_keygen(_arg0, _arg1);
}

int EVP_PKEY_keygen_init(EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_keygen_init(_arg0);
}

EVP_PKEY_PTR EVP_PKEY_new(void) {
	return _g_EVP_PKEY_new();
}

EVP_PKEY_PTR EVP_PKEY_new_raw_private_key(int _arg0, ENGINE_PTR _arg1, const unsigned char* _arg2, size_t _arg3) {
	return _g_EVP_PKEY_new_raw_private_key(_arg0, _arg1, _arg2, _arg3);
}

EVP_PKEY_PTR EVP_PKEY_new_raw_public_key(int _arg0, ENGINE_PTR _arg1, const unsigned char* _arg2, size_t _arg3) {
	return _g_EVP_PKEY_new_raw_public_key(_arg0, _arg1, _arg2, _arg3);
}

int EVP_PKEY_paramgen(EVP_PKEY_CTX_PTR _arg0, EVP_PKEY_PTR* _arg1) {
	return _g_EVP_PKEY_paramgen(_arg0, _arg1);
}

int EVP_PKEY_paramgen_init(EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_paramgen_init(_arg0);
}

int EVP_PKEY_set1_EC_KEY(EVP_PKEY_PTR _arg0, EC_KEY_PTR _arg1) {
	return _g_EVP_PKEY_set1_EC_KEY(_arg0, _arg1);
}

int EVP_PKEY_set1_encoded_public_key(EVP_PKEY_PTR _arg0, const unsigned char* _arg1, size_t _arg2) {
	return _g_EVP_PKEY_set1_encoded_public_key(_arg0, _arg1, _arg2);
}

int EVP_PKEY_sign(EVP_PKEY_CTX_PTR _arg0, unsigned char* _arg1, size_t* _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_PKEY_sign(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_PKEY_sign_init(EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_sign_init(_arg0);
}

int EVP_PKEY_size(const EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_size(_arg0);
}

int EVP_PKEY_up_ref(EVP_PKEY_PTR _arg0) {
	return _g_EVP_PKEY_up_ref(_arg0);
}

int EVP_PKEY_verify(EVP_PKEY_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2, const unsigned char* _arg3, size_t _arg4) {
	return _g_EVP_PKEY_verify(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int EVP_PKEY_verify_init(EVP_PKEY_CTX_PTR _arg0) {
	return _g_EVP_PKEY_verify_init(_arg0);
}

EVP_SIGNATURE_PTR EVP_SIGNATURE_fetch(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, const char* _arg2) {
	return _g_EVP_SIGNATURE_fetch(_arg0, _arg1, _arg2);
}

void EVP_SIGNATURE_free(EVP_SIGNATURE_PTR _arg0) {
	_g_EVP_SIGNATURE_free(_arg0);
}

EVP_CIPHER_PTR EVP_aes_128_cbc(void) {
	return _g_EVP_aes_128_cbc();
}

EVP_CIPHER_PTR EVP_aes_128_ctr(void) {
	return _g_EVP_aes_128_ctr();
}

EVP_CIPHER_PTR EVP_aes_128_ecb(void) {
	return _g_EVP_aes_128_ecb();
}

EVP_CIPHER_PTR EVP_aes_128_gcm(void) {
	return _g_EVP_aes_128_gcm();
}

EVP_CIPHER_PTR EVP_aes_192_cbc(void) {
	return _g_EVP_aes_192_cbc();
}

EVP_CIPHER_PTR EVP_aes_192_ctr(void) {
	return _g_EVP_aes_192_ctr();
}

EVP_CIPHER_PTR EVP_aes_192_ecb(void) {
	return _g_EVP_aes_192_ecb();
}

EVP_CIPHER_PTR EVP_aes_192_gcm(void) {
	return _g_EVP_aes_192_gcm();
}

EVP_CIPHER_PTR EVP_aes_256_cbc(void) {
	return _g_EVP_aes_256_cbc();
}

EVP_CIPHER_PTR EVP_aes_256_ctr(void) {
	return _g_EVP_aes_256_ctr();
}

EVP_CIPHER_PTR EVP_aes_256_ecb(void) {
	return _g_EVP_aes_256_ecb();
}

EVP_CIPHER_PTR EVP_aes_256_gcm(void) {
	return _g_EVP_aes_256_gcm();
}

int EVP_default_properties_enable_fips(OSSL_LIB_CTX_PTR _arg0, int _arg1) {
	return _g_EVP_default_properties_enable_fips(_arg0, _arg1);
}

int EVP_default_properties_is_fips_enabled(OSSL_LIB_CTX_PTR _arg0) {
	return _g_EVP_default_properties_is_fips_enabled(_arg0);
}

EVP_CIPHER_PTR EVP_des_cbc(void) {
	return _g_EVP_des_cbc();
}

EVP_CIPHER_PTR EVP_des_ecb(void) {
	return _g_EVP_des_ecb();
}

EVP_CIPHER_PTR EVP_des_ede3_cbc(void) {
	return _g_EVP_des_ede3_cbc();
}

EVP_CIPHER_PTR EVP_des_ede3_ecb(void) {
	return _g_EVP_des_ede3_ecb();
}

const EVP_MD_PTR EVP_md4(void) {
	return _g_EVP_md4();
}

const EVP_MD_PTR EVP_md5(void) {
	return _g_EVP_md5();
}

const EVP_MD_PTR EVP_md5_sha1(void) {
	return _g_EVP_md5_sha1();
}

EVP_CIPHER_PTR EVP_rc4(void) {
	return _g_EVP_rc4();
}

const EVP_MD_PTR EVP_sha1(void) {
	return _g_EVP_sha1();
}

const EVP_MD_PTR EVP_sha224(void) {
	return _g_EVP_sha224();
}

const EVP_MD_PTR EVP_sha256(void) {
	return _g_EVP_sha256();
}

const EVP_MD_PTR EVP_sha384(void) {
	return _g_EVP_sha384();
}

const EVP_MD_PTR EVP_sha3_224(void) {
	return _g_EVP_sha3_224();
}

const EVP_MD_PTR EVP_sha3_256(void) {
	return _g_EVP_sha3_256();
}

const EVP_MD_PTR EVP_sha3_384(void) {
	return _g_EVP_sha3_384();
}

const EVP_MD_PTR EVP_sha3_512(void) {
	return _g_EVP_sha3_512();
}

const EVP_MD_PTR EVP_sha512(void) {
	return _g_EVP_sha512();
}

int FIPS_mode(void) {
	return _g_FIPS_mode();
}

int FIPS_mode_set(int _arg0) {
	return _g_FIPS_mode_set(_arg0);
}

void HMAC_CTX_cleanup(HMAC_CTX_PTR _arg0) {
	_g_HMAC_CTX_cleanup(_arg0);
}

int HMAC_CTX_copy(HMAC_CTX_PTR _arg0, HMAC_CTX_PTR _arg1) {
	return _g_HMAC_CTX_copy(_arg0, _arg1);
}

void HMAC_CTX_free(HMAC_CTX_PTR _arg0) {
	_g_HMAC_CTX_free(_arg0);
}

void HMAC_CTX_init(HMAC_CTX_PTR _arg0) {
	_g_HMAC_CTX_init(_arg0);
}

HMAC_CTX_PTR HMAC_CTX_new(void) {
	return _g_HMAC_CTX_new();
}

int HMAC_Final(HMAC_CTX_PTR _arg0, unsigned char* _arg1, unsigned int* _arg2) {
	return _g_HMAC_Final(_arg0, _arg1, _arg2);
}

int HMAC_Init_ex(HMAC_CTX_PTR _arg0, const void* _arg1, int _arg2, const EVP_MD_PTR _arg3, ENGINE_PTR _arg4) {
	return _g_HMAC_Init_ex(_arg0, _arg1, _arg2, _arg3, _arg4);
}

int HMAC_Update(HMAC_CTX_PTR _arg0, const unsigned char* _arg1, size_t _arg2) {
	return _g_HMAC_Update(_arg0, _arg1, _arg2);
}

int MD5_Final(unsigned char* _arg0, MD5_CTX_PTR _arg1) {
	return _g_MD5_Final(_arg0, _arg1);
}

int MD5_Init(MD5_CTX_PTR _arg0) {
	return _g_MD5_Init(_arg0);
}

int MD5_Update(MD5_CTX_PTR _arg0, const void* _arg1, size_t _arg2) {
	return _g_MD5_Update(_arg0, _arg1, _arg2);
}

const char* OBJ_nid2sn(int _arg0) {
	return _g_OBJ_nid2sn(_arg0);
}

void OPENSSL_add_all_algorithms_conf(void) {
	_g_OPENSSL_add_all_algorithms_conf();
}

void OPENSSL_init(void) {
	_g_OPENSSL_init();
}

int OPENSSL_init_crypto(uint64_t _arg0, const OPENSSL_INIT_SETTINGS_PTR _arg1) {
	return _g_OPENSSL_init_crypto(_arg0, _arg1);
}

void OSSL_PARAM_BLD_free(OSSL_PARAM_BLD_PTR _arg0) {
	_g_OSSL_PARAM_BLD_free(_arg0);
}

OSSL_PARAM_BLD_PTR OSSL_PARAM_BLD_new(void) {
	return _g_OSSL_PARAM_BLD_new();
}

int OSSL_PARAM_BLD_push_BN(OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const BIGNUM_PTR _arg2) {
	return _g_OSSL_PARAM_BLD_push_BN(_arg0, _arg1, _arg2);
}

int OSSL_PARAM_BLD_push_int32(OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, int32_t _arg2) {
	return _g_OSSL_PARAM_BLD_push_int32(_arg0, _arg1, _arg2);
}

int OSSL_PARAM_BLD_push_octet_string(OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const void* _arg2, size_t _arg3) {
	return _g_OSSL_PARAM_BLD_push_octet_string(_arg0, _arg1, _arg2, _arg3);
}

int OSSL_PARAM_BLD_push_utf8_string(OSSL_PARAM_BLD_PTR _arg0, const char* _arg1, const char* _arg2, size_t _arg3) {
	return _g_OSSL_PARAM_BLD_push_utf8_string(_arg0, _arg1, _arg2, _arg3);
}

OSSL_PARAM_PTR OSSL_PARAM_BLD_to_param(OSSL_PARAM_BLD_PTR _arg0) {
	return _g_OSSL_PARAM_BLD_to_param(_arg0);
}

void OSSL_PARAM_free(OSSL_PARAM_PTR _arg0) {
	_g_OSSL_PARAM_free(_arg0);
}

int OSSL_PROVIDER_available(OSSL_LIB_CTX_PTR _arg0, const char* _arg1) {
	return _g_OSSL_PROVIDER_available(_arg0, _arg1);
}

const char* OSSL_PROVIDER_get0_name(const OSSL_PROVIDER_PTR _arg0) {
	return _g_OSSL_PROVIDER_get0_name(_arg0);
}

OSSL_PROVIDER_PTR OSSL_PROVIDER_try_load(OSSL_LIB_CTX_PTR _arg0, const char* _arg1, int _arg2) {
	return _g_OSSL_PROVIDER_try_load(_arg0, _arg1, _arg2);
}

const char* OpenSSL_version(int _arg0) {
	return _g_OpenSSL_version(_arg0);
}

int PKCS5_PBKDF2_HMAC(const char* _arg0, int _arg1, const unsigned char* _arg2, int _arg3, int _arg4, const EVP_MD_PTR _arg5, int _arg6, unsigned char* _arg7) {
	return _g_PKCS5_PBKDF2_HMAC(_arg0, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6, _arg7);
}

int RAND_bytes(unsigned char* _arg0, int _arg1) {
	return _g_RAND_bytes(_arg0, _arg1);
}

void RSA_free(RSA_PTR _arg0) {
	_g_RSA_free(_arg0);
}

void RSA_get0_crt_params(const RSA_PTR _arg0, const BIGNUM_PTR* _arg1, const BIGNUM_PTR* _arg2, const BIGNUM_PTR* _arg3) {
	_g_RSA_get0_crt_params(_arg0, _arg1, _arg2, _arg3);
}

void RSA_get0_factors(const RSA_PTR _arg0, const BIGNUM_PTR* _arg1, const BIGNUM_PTR* _arg2) {
	_g_RSA_get0_factors(_arg0, _arg1, _arg2);
}

void RSA_get0_key(const RSA_PTR _arg0, const BIGNUM_PTR* _arg1, const BIGNUM_PTR* _arg2, const BIGNUM_PTR* _arg3) {
	_g_RSA_get0_key(_arg0, _arg1, _arg2, _arg3);
}

RSA_PTR RSA_new(void) {
	return _g_RSA_new();
}

int RSA_set0_crt_params(RSA_PTR _arg0, BIGNUM_PTR _arg1, BIGNUM_PTR _arg2, BIGNUM_PTR _arg3) {
	return _g_RSA_set0_crt_params(_arg0, _arg1, _arg2, _arg3);
}

int RSA_set0_factors(RSA_PTR _arg0, BIGNUM_PTR _arg1, BIGNUM_PTR _arg2) {
	return _g_RSA_set0_factors(_arg0, _arg1, _arg2);
}

int RSA_set0_key(RSA_PTR _arg0, BIGNUM_PTR _arg1, BIGNUM_PTR _arg2, BIGNUM_PTR _arg3) {
	return _g_RSA_set0_key(_arg0, _arg1, _arg2, _arg3);
}

int SHA1_Final(unsigned char* _arg0, SHA_CTX_PTR _arg1) {
	return _g_SHA1_Final(_arg0, _arg1);
}

int SHA1_Init(SHA_CTX_PTR _arg0) {
	return _g_SHA1_Init(_arg0);
}

int SHA1_Update(SHA_CTX_PTR _arg0, const void* _arg1, size_t _arg2) {
	return _g_SHA1_Update(_arg0, _arg1, _arg2);
}

const char* SSLeay_version(int _arg0) {
	return _g_SSLeay_version(_arg0);
}

BIGNUM_PTR bn_expand2(BIGNUM_PTR _arg0, int _arg1) {
	return _g_bn_expand2(_arg0, _arg1);
}

