// Code generated by mkcgo. DO NOT EDIT.

package ossl

/*
#include "ossl.h"
#include "api.h"
void __mkcgoLoad_crypto(void* handle);
*/
import "C"
import (
	"unsafe"
)

func mkcgoLoad_crypto(handle unsafe.Pointer) {
	C.__mkcgoLoad_crypto(handle)
}

func BN_bin2bn(arg0 *byte, arg1 int32, arg2 BIGNUM_PTR) (_r0 BIGNUM_PTR, err error) {
	r0 := C.BN_bin2bn((*C.uchar)(unsafe.Pointer(arg0)), C.int(arg1), C.BIGNUM_PTR(arg2))
	_r0 = BIGNUM_PTR(r0)
	if _r0 == nil {
		err = newError("BN_bin2bn")
	}
	return
}

func BN_bn2bin(a BIGNUM_PTR, to *byte) (_r0 int32) {
	r0 := C.BN_bn2bin(C.BIGNUM_PTR(a), (*C.uchar)(unsafe.Pointer(to)))
	_r0 = int32(r0)
	return
}

func BN_bn2binpad(a BIGNUM_PTR, to *byte, tolen int32) (_r0 int32, err error) {
	r0 := C.BN_bn2binpad(C.BIGNUM_PTR(a), (*C.uchar)(unsafe.Pointer(to)), C.int(tolen))
	_r0 = int32(r0)
	if _r0 == -1 {
		err = newError("BN_bn2binpad")
	}
	return
}

func BN_bn2lebinpad(a BIGNUM_PTR, to *byte, tolen int32) (_r0 int32, err error) {
	r0 := C.BN_bn2lebinpad(C.BIGNUM_PTR(a), (*C.uchar)(unsafe.Pointer(to)), C.int(tolen))
	_r0 = int32(r0)
	if _r0 == -1 {
		err = newError("BN_bn2lebinpad")
	}
	return
}

func BN_clear(arg0 BIGNUM_PTR) {
	C.BN_clear(C.BIGNUM_PTR(arg0))
}

func BN_clear_free(arg0 BIGNUM_PTR) {
	C.BN_clear_free(C.BIGNUM_PTR(arg0))
}

func BN_free(arg0 BIGNUM_PTR) {
	C.BN_free(C.BIGNUM_PTR(arg0))
}

func BN_lebin2bn(s *byte, len int32, ret BIGNUM_PTR) (_r0 BIGNUM_PTR, err error) {
	r0 := C.BN_lebin2bn((*C.uchar)(unsafe.Pointer(s)), C.int(len), C.BIGNUM_PTR(ret))
	_r0 = BIGNUM_PTR(r0)
	if _r0 == nil {
		err = newError("BN_lebin2bn")
	}
	return
}

func BN_new() (_r0 BIGNUM_PTR, err error) {
	r0 := C.BN_new()
	_r0 = BIGNUM_PTR(r0)
	if _r0 == nil {
		err = newError("BN_new")
	}
	return
}

func BN_num_bits(arg0 BIGNUM_PTR) (_r0 int32) {
	r0 := C.BN_num_bits(C.BIGNUM_PTR(arg0))
	_r0 = int32(r0)
	return
}

func CRYPTO_free(str unsafe.Pointer, file *byte, line int32) {
	C.CRYPTO_free(str, (*C.char)(unsafe.Pointer(file)), C.int(line))
}

func CRYPTO_malloc(num int, file *byte, line int32) (_r0 unsafe.Pointer) {
	r0 := C.CRYPTO_malloc(C.size_t(num), (*C.char)(unsafe.Pointer(file)), C.int(line))
	_r0 = unsafe.Pointer(r0)
	return
}

func DSA_free(r DSA_PTR) {
	C.DSA_free(C.DSA_PTR(r))
}

func DSA_generate_key(a DSA_PTR) (err error) {
	r0 := C.DSA_generate_key(C.DSA_PTR(a))
	if r0 != 1 {
		err = newError("DSA_generate_key")
	}
	return
}

func DSA_get0_key(d DSA_PTR, pub_key *BIGNUM_PTR, priv_key *BIGNUM_PTR) {
	C.DSA_get0_key(C.DSA_PTR(d), (*C.BIGNUM_PTR)(unsafe.Pointer(pub_key)), (*C.BIGNUM_PTR)(unsafe.Pointer(priv_key)))
}

func DSA_get0_pqg(d DSA_PTR, p *BIGNUM_PTR, q *BIGNUM_PTR, g *BIGNUM_PTR) {
	C.DSA_get0_pqg(C.DSA_PTR(d), (*C.BIGNUM_PTR)(unsafe.Pointer(p)), (*C.BIGNUM_PTR)(unsafe.Pointer(q)), (*C.BIGNUM_PTR)(unsafe.Pointer(g)))
}

func DSA_new() (_r0 DSA_PTR, err error) {
	r0 := C.DSA_new()
	_r0 = DSA_PTR(r0)
	if _r0 == nil {
		err = newError("DSA_new")
	}
	return
}

func DSA_set0_key(d DSA_PTR, pub_key BIGNUM_PTR, priv_key BIGNUM_PTR) (err error) {
	r0 := C.DSA_set0_key(C.DSA_PTR(d), C.BIGNUM_PTR(pub_key), C.BIGNUM_PTR(priv_key))
	if r0 != 1 {
		err = newError("DSA_set0_key")
	}
	return
}

func DSA_set0_pqg(d DSA_PTR, p BIGNUM_PTR, q BIGNUM_PTR, g BIGNUM_PTR) (err error) {
	r0 := C.DSA_set0_pqg(C.DSA_PTR(d), C.BIGNUM_PTR(p), C.BIGNUM_PTR(q), C.BIGNUM_PTR(g))
	if r0 != 1 {
		err = newError("DSA_set0_pqg")
	}
	return
}

func EC_GROUP_free(group EC_GROUP_PTR) {
	C.EC_GROUP_free(C.EC_GROUP_PTR(group))
}

func EC_GROUP_new_by_curve_name(nid int32) (_r0 EC_GROUP_PTR, err error) {
	r0 := C.EC_GROUP_new_by_curve_name(C.int(nid))
	_r0 = EC_GROUP_PTR(r0)
	if _r0 == nil {
		err = newError("EC_GROUP_new_by_curve_name")
	}
	return
}

func EC_KEY_free(arg0 EC_KEY_PTR) {
	C.EC_KEY_free(C.EC_KEY_PTR(arg0))
}

func EC_KEY_get0_group(arg0 EC_KEY_PTR) (_r0 EC_GROUP_PTR, err error) {
	r0 := C.EC_KEY_get0_group(C.EC_KEY_PTR(arg0))
	_r0 = EC_GROUP_PTR(r0)
	if _r0 == nil {
		err = newError("EC_KEY_get0_group")
	}
	return
}

func EC_KEY_get0_private_key(arg0 EC_KEY_PTR) (_r0 BIGNUM_PTR, err error) {
	r0 := C.EC_KEY_get0_private_key(C.EC_KEY_PTR(arg0))
	_r0 = BIGNUM_PTR(r0)
	if _r0 == nil {
		err = newError("EC_KEY_get0_private_key")
	}
	return
}

func EC_KEY_get0_public_key(arg0 EC_KEY_PTR) (_r0 EC_POINT_PTR, err error) {
	r0 := C.EC_KEY_get0_public_key(C.EC_KEY_PTR(arg0))
	_r0 = EC_POINT_PTR(r0)
	if _r0 == nil {
		err = newError("EC_KEY_get0_public_key")
	}
	return
}

func EC_KEY_new_by_curve_name(arg0 int32) (_r0 EC_KEY_PTR, err error) {
	r0 := C.EC_KEY_new_by_curve_name(C.int(arg0))
	_r0 = EC_KEY_PTR(r0)
	if _r0 == nil {
		err = newError("EC_KEY_new_by_curve_name")
	}
	return
}

func EC_KEY_set_private_key(arg0 EC_KEY_PTR, arg1 BIGNUM_PTR) (err error) {
	r0 := C.EC_KEY_set_private_key(C.EC_KEY_PTR(arg0), C.BIGNUM_PTR(arg1))
	if r0 != 1 {
		err = newError("EC_KEY_set_private_key")
	}
	return
}

func EC_KEY_set_public_key(key EC_KEY_PTR, pub EC_POINT_PTR) (err error) {
	r0 := C.EC_KEY_set_public_key(C.EC_KEY_PTR(key), C.EC_POINT_PTR(pub))
	if r0 != 1 {
		err = newError("EC_KEY_set_public_key")
	}
	return
}

func EC_KEY_set_public_key_affine_coordinates(key EC_KEY_PTR, x BIGNUM_PTR, y BIGNUM_PTR) (err error) {
	r0 := C.EC_KEY_set_public_key_affine_coordinates(C.EC_KEY_PTR(key), C.BIGNUM_PTR(x), C.BIGNUM_PTR(y))
	if r0 != 1 {
		err = newError("EC_KEY_set_public_key_affine_coordinates")
	}
	return
}

func EC_POINT_free(arg0 EC_POINT_PTR) {
	C.EC_POINT_free(C.EC_POINT_PTR(arg0))
}

func EC_POINT_get_affine_coordinates_GFp(arg0 EC_GROUP_PTR, arg1 EC_POINT_PTR, arg2 BIGNUM_PTR, arg3 BIGNUM_PTR, arg4 BN_CTX_PTR) (err error) {
	r0 := C.EC_POINT_get_affine_coordinates_GFp(C.EC_GROUP_PTR(arg0), C.EC_POINT_PTR(arg1), C.BIGNUM_PTR(arg2), C.BIGNUM_PTR(arg3), C.BN_CTX_PTR(arg4))
	if r0 != 1 {
		err = newError("EC_POINT_get_affine_coordinates_GFp")
	}
	return
}

func EC_POINT_mul(group EC_GROUP_PTR, r EC_POINT_PTR, n BIGNUM_PTR, q EC_POINT_PTR, m BIGNUM_PTR, ctx BN_CTX_PTR) (err error) {
	r0 := C.EC_POINT_mul(C.EC_GROUP_PTR(group), C.EC_POINT_PTR(r), C.BIGNUM_PTR(n), C.EC_POINT_PTR(q), C.BIGNUM_PTR(m), C.BN_CTX_PTR(ctx))
	if r0 != 1 {
		err = newError("EC_POINT_mul")
	}
	return
}

func EC_POINT_new(arg0 EC_GROUP_PTR) (_r0 EC_POINT_PTR, err error) {
	r0 := C.EC_POINT_new(C.EC_GROUP_PTR(arg0))
	_r0 = EC_POINT_PTR(r0)
	if _r0 == nil {
		err = newError("EC_POINT_new")
	}
	return
}

func EC_POINT_oct2point(group EC_GROUP_PTR, p EC_POINT_PTR, buf *byte, len int, ctx BN_CTX_PTR) (err error) {
	r0 := C.EC_POINT_oct2point(C.EC_GROUP_PTR(group), C.EC_POINT_PTR(p), (*C.uchar)(unsafe.Pointer(buf)), C.size_t(len), C.BN_CTX_PTR(ctx))
	if r0 != 1 {
		err = newError("EC_POINT_oct2point")
	}
	return
}

func EC_POINT_point2oct(group EC_GROUP_PTR, p EC_POINT_PTR, form Point_conversion_form_t, buf *byte, len int, ctx BN_CTX_PTR) (_r0 int, err error) {
	r0 := C.EC_POINT_point2oct(C.EC_GROUP_PTR(group), C.EC_POINT_PTR(p), C.point_conversion_form_t(form), (*C.uchar)(unsafe.Pointer(buf)), C.size_t(len), C.BN_CTX_PTR(ctx))
	_r0 = int(r0)
	if _r0 == 0 {
		err = newError("EC_POINT_point2oct")
	}
	return
}

func EC_POINT_set_affine_coordinates(arg0 EC_GROUP_PTR, arg1 EC_POINT_PTR, arg2 BIGNUM_PTR, arg3 BIGNUM_PTR, arg4 BN_CTX_PTR) (err error) {
	r0 := C.EC_POINT_set_affine_coordinates(C.EC_GROUP_PTR(arg0), C.EC_POINT_PTR(arg1), C.BIGNUM_PTR(arg2), C.BIGNUM_PTR(arg3), C.BN_CTX_PTR(arg4))
	if r0 != 1 {
		err = newError("EC_POINT_set_affine_coordinates")
	}
	return
}

func ERR_clear_error() {
	C.ERR_clear_error()
}

func ERR_error_string_n(e uint64, buf *byte, len int) {
	C.ERR_error_string_n(C.ulong(e), (*C.char)(unsafe.Pointer(buf)), C.size_t(len))
}

func ERR_get_error_all(file **byte, line *int32, fn **byte, data **byte, flags *int32) (_r0 uint64) {
	r0 := C.ERR_get_error_all((**C.char)(unsafe.Pointer(file)), (*C.int)(unsafe.Pointer(line)), (**C.char)(unsafe.Pointer(fn)), (**C.char)(unsafe.Pointer(data)), (*C.int)(unsafe.Pointer(flags)))
	_r0 = uint64(r0)
	return
}

func ERR_get_error_line(file **byte, line *int32) (_r0 uint64) {
	r0 := C.ERR_get_error_line((**C.char)(unsafe.Pointer(file)), (*C.int)(unsafe.Pointer(line)))
	_r0 = uint64(r0)
	return
}

func ERR_load_crypto_strings() {
	C.ERR_load_crypto_strings()
}

func EVP_CIPHER_CTX_ctrl(ctx EVP_CIPHER_CTX_PTR, cmd int32, p1 int32, p2 unsafe.Pointer) (err error) {
	r0 := C.EVP_CIPHER_CTX_ctrl(C.EVP_CIPHER_CTX_PTR(ctx), C.int(cmd), C.int(p1), p2)
	if r0 != 1 {
		err = newError("EVP_CIPHER_CTX_ctrl")
	}
	return
}

func EVP_CIPHER_CTX_free(ctx EVP_CIPHER_CTX_PTR) {
	C.EVP_CIPHER_CTX_free(C.EVP_CIPHER_CTX_PTR(ctx))
}

func EVP_CIPHER_CTX_new() (_r0 EVP_CIPHER_CTX_PTR, err error) {
	r0 := C.EVP_CIPHER_CTX_new()
	_r0 = EVP_CIPHER_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_CIPHER_CTX_new")
	}
	return
}

func EVP_CIPHER_CTX_set_key_length(ctx EVP_CIPHER_CTX_PTR, keylen int32) (err error) {
	r0 := C.EVP_CIPHER_CTX_set_key_length(C.EVP_CIPHER_CTX_PTR(ctx), C.int(keylen))
	if r0 != 1 {
		err = newError("EVP_CIPHER_CTX_set_key_length")
	}
	return
}

func EVP_CIPHER_CTX_set_padding(x EVP_CIPHER_CTX_PTR, padding int32) (err error) {
	r0 := C.EVP_CIPHER_CTX_set_padding(C.EVP_CIPHER_CTX_PTR(x), C.int(padding))
	if r0 != 1 {
		err = newError("EVP_CIPHER_CTX_set_padding")
	}
	return
}

func _EVP_CIPHER_block_size(e EVP_CIPHER_PTR) (_r0 int32) {
	r0 := C.EVP_CIPHER_block_size(C.EVP_CIPHER_PTR(e))
	_r0 = int32(r0)
	return
}

func EVP_CIPHER_fetch(ctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (_r0 EVP_CIPHER_PTR, err error) {
	r0 := C.EVP_CIPHER_fetch(C.OSSL_LIB_CTX_PTR(ctx), (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)))
	_r0 = EVP_CIPHER_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_CIPHER_fetch")
	}
	return
}

func EVP_CIPHER_get0_name(cipher EVP_CIPHER_PTR) (_r0 *byte) {
	r0 := C.EVP_CIPHER_get0_name(C.EVP_CIPHER_PTR(cipher))
	_r0 = (*byte)(unsafe.Pointer(r0))
	return
}

func _EVP_CIPHER_get_block_size(e EVP_CIPHER_PTR) (_r0 int32) {
	r0 := C.EVP_CIPHER_get_block_size(C.EVP_CIPHER_PTR(e))
	_r0 = int32(r0)
	return
}

func EVP_CipherInit_ex(ctx EVP_CIPHER_CTX_PTR, typ EVP_CIPHER_PTR, impl ENGINE_PTR, key *byte, iv *byte, enc int32) (err error) {
	r0 := C.EVP_CipherInit_ex(C.EVP_CIPHER_CTX_PTR(ctx), C.EVP_CIPHER_PTR(typ), C.ENGINE_PTR(impl), (*C.uchar)(unsafe.Pointer(key)), (*C.uchar)(unsafe.Pointer(iv)), C.int(enc))
	if r0 != 1 {
		err = newError("EVP_CipherInit_ex")
	}
	return
}

func EVP_CipherUpdate(ctx EVP_CIPHER_CTX_PTR, out *byte, outl *int32, in *byte, inl int32) (err error) {
	r0 := C.EVP_CipherUpdate(C.EVP_CIPHER_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(out)), (*C.int)(unsafe.Pointer(outl)), (*C.uchar)(unsafe.Pointer(in)), C.int(inl))
	if r0 != 1 {
		err = newError("EVP_CipherUpdate")
	}
	return
}

func EVP_DecryptFinal_ex(ctx EVP_CIPHER_CTX_PTR, outm *byte, outl *int32) (err error) {
	r0 := C.EVP_DecryptFinal_ex(C.EVP_CIPHER_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(outm)), (*C.int)(unsafe.Pointer(outl)))
	if r0 != 1 {
		err = newError("EVP_DecryptFinal_ex")
	}
	return
}

func EVP_DecryptInit_ex(ctx EVP_CIPHER_CTX_PTR, typ EVP_CIPHER_PTR, impl ENGINE_PTR, key *byte, iv *byte) (err error) {
	r0 := C.EVP_DecryptInit_ex(C.EVP_CIPHER_CTX_PTR(ctx), C.EVP_CIPHER_PTR(typ), C.ENGINE_PTR(impl), (*C.uchar)(unsafe.Pointer(key)), (*C.uchar)(unsafe.Pointer(iv)))
	if r0 != 1 {
		err = newError("EVP_DecryptInit_ex")
	}
	return
}

func EVP_DecryptUpdate(ctx EVP_CIPHER_CTX_PTR, out *byte, outl *int32, in *byte, inl int32) (err error) {
	r0 := C.EVP_DecryptUpdate(C.EVP_CIPHER_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(out)), (*C.int)(unsafe.Pointer(outl)), (*C.uchar)(unsafe.Pointer(in)), C.int(inl))
	if r0 != 1 {
		err = newError("EVP_DecryptUpdate")
	}
	return
}

func EVP_Digest(data unsafe.Pointer, count int, md *byte, size *uint32, typ EVP_MD_PTR, impl ENGINE_PTR) (err error) {
	r0 := C.EVP_Digest(data, C.size_t(count), (*C.uchar)(unsafe.Pointer(md)), (*C.uint)(unsafe.Pointer(size)), C.EVP_MD_PTR(typ), C.ENGINE_PTR(impl))
	if r0 != 1 {
		err = newError("EVP_Digest")
	}
	return
}

func EVP_DigestFinal(ctx EVP_MD_CTX_PTR, md *byte, s *uint32) (err error) {
	r0 := C.EVP_DigestFinal(C.EVP_MD_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(md)), (*C.uint)(unsafe.Pointer(s)))
	if r0 != 1 {
		err = newError("EVP_DigestFinal")
	}
	return
}

func EVP_DigestInit(ctx EVP_MD_CTX_PTR, typ EVP_MD_PTR) (err error) {
	r0 := C.EVP_DigestInit(C.EVP_MD_CTX_PTR(ctx), C.EVP_MD_PTR(typ))
	if r0 != 1 {
		err = newError("EVP_DigestInit")
	}
	return
}

func EVP_DigestInit_ex(ctx EVP_MD_CTX_PTR, typ EVP_MD_PTR, impl ENGINE_PTR) (err error) {
	r0 := C.EVP_DigestInit_ex(C.EVP_MD_CTX_PTR(ctx), C.EVP_MD_PTR(typ), C.ENGINE_PTR(impl))
	if r0 != 1 {
		err = newError("EVP_DigestInit_ex")
	}
	return
}

func EVP_DigestSign(ctx EVP_MD_CTX_PTR, sigret *byte, siglen *int, tbs *byte, tbslen int) (err error) {
	r0 := C.EVP_DigestSign(C.EVP_MD_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(sigret)), (*C.size_t)(unsafe.Pointer(siglen)), (*C.uchar)(unsafe.Pointer(tbs)), C.size_t(tbslen))
	if r0 != 1 {
		err = newError("EVP_DigestSign")
	}
	return
}

func EVP_DigestSignFinal(ctx EVP_MD_CTX_PTR, sig *byte, siglen *int) (err error) {
	r0 := C.EVP_DigestSignFinal(C.EVP_MD_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(sig)), (*C.size_t)(unsafe.Pointer(siglen)))
	if r0 != 1 {
		err = newError("EVP_DigestSignFinal")
	}
	return
}

func EVP_DigestSignInit(ctx EVP_MD_CTX_PTR, pctx *EVP_PKEY_CTX_PTR, typ EVP_MD_PTR, e ENGINE_PTR, pkey EVP_PKEY_PTR) (err error) {
	r0 := C.EVP_DigestSignInit(C.EVP_MD_CTX_PTR(ctx), (*C.EVP_PKEY_CTX_PTR)(unsafe.Pointer(pctx)), C.EVP_MD_PTR(typ), C.ENGINE_PTR(e), C.EVP_PKEY_PTR(pkey))
	if r0 != 1 {
		err = newError("EVP_DigestSignInit")
	}
	return
}

func EVP_DigestUpdate(ctx EVP_MD_CTX_PTR, d unsafe.Pointer, cnt int) (err error) {
	r0 := C.EVP_DigestUpdate(C.EVP_MD_CTX_PTR(ctx), d, C.size_t(cnt))
	if r0 != 1 {
		err = newError("EVP_DigestUpdate")
	}
	return
}

func EVP_DigestVerify(ctx EVP_MD_CTX_PTR, sigret *byte, siglen int, tbs *byte, tbslen int) (err error) {
	r0 := C.EVP_DigestVerify(C.EVP_MD_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(sigret)), C.size_t(siglen), (*C.uchar)(unsafe.Pointer(tbs)), C.size_t(tbslen))
	if r0 != 1 {
		err = newError("EVP_DigestVerify")
	}
	return
}

func EVP_DigestVerifyFinal(ctx EVP_MD_CTX_PTR, sig *byte, siglen int) (err error) {
	r0 := C.EVP_DigestVerifyFinal(C.EVP_MD_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(sig)), C.size_t(siglen))
	if r0 != 1 {
		err = newError("EVP_DigestVerifyFinal")
	}
	return
}

func EVP_DigestVerifyInit(ctx EVP_MD_CTX_PTR, pctx *EVP_PKEY_CTX_PTR, typ EVP_MD_PTR, e ENGINE_PTR, pkey EVP_PKEY_PTR) (err error) {
	r0 := C.EVP_DigestVerifyInit(C.EVP_MD_CTX_PTR(ctx), (*C.EVP_PKEY_CTX_PTR)(unsafe.Pointer(pctx)), C.EVP_MD_PTR(typ), C.ENGINE_PTR(e), C.EVP_PKEY_PTR(pkey))
	if r0 != 1 {
		err = newError("EVP_DigestVerifyInit")
	}
	return
}

func EVP_EncryptFinal_ex(ctx EVP_CIPHER_CTX_PTR, out *byte, outl *int32) (err error) {
	r0 := C.EVP_EncryptFinal_ex(C.EVP_CIPHER_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(out)), (*C.int)(unsafe.Pointer(outl)))
	if r0 != 1 {
		err = newError("EVP_EncryptFinal_ex")
	}
	return
}

func EVP_EncryptInit_ex(ctx EVP_CIPHER_CTX_PTR, typ EVP_CIPHER_PTR, impl ENGINE_PTR, key *byte, iv *byte) (err error) {
	r0 := C.EVP_EncryptInit_ex(C.EVP_CIPHER_CTX_PTR(ctx), C.EVP_CIPHER_PTR(typ), C.ENGINE_PTR(impl), (*C.uchar)(unsafe.Pointer(key)), (*C.uchar)(unsafe.Pointer(iv)))
	if r0 != 1 {
		err = newError("EVP_EncryptInit_ex")
	}
	return
}

func EVP_EncryptUpdate(ctx EVP_CIPHER_CTX_PTR, out *byte, outl *int32, in *byte, inl int32) (err error) {
	r0 := C.EVP_EncryptUpdate(C.EVP_CIPHER_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(out)), (*C.int)(unsafe.Pointer(outl)), (*C.uchar)(unsafe.Pointer(in)), C.int(inl))
	if r0 != 1 {
		err = newError("EVP_EncryptUpdate")
	}
	return
}

func EVP_KDF_CTX_free(ctx EVP_KDF_CTX_PTR) {
	C.EVP_KDF_CTX_free(C.EVP_KDF_CTX_PTR(ctx))
}

func EVP_KDF_CTX_get_kdf_size(ctx EVP_KDF_CTX_PTR) (_r0 int, err error) {
	r0 := C.EVP_KDF_CTX_get_kdf_size(C.EVP_KDF_CTX_PTR(ctx))
	_r0 = int(r0)
	if _r0 == 0 {
		err = newError("EVP_KDF_CTX_get_kdf_size")
	}
	return
}

func EVP_KDF_CTX_new(kdf EVP_KDF_PTR) (_r0 EVP_KDF_CTX_PTR, err error) {
	r0 := C.EVP_KDF_CTX_new(C.EVP_KDF_PTR(kdf))
	_r0 = EVP_KDF_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_KDF_CTX_new")
	}
	return
}

func EVP_KDF_CTX_set_params(ctx EVP_KDF_CTX_PTR, params OSSL_PARAM_PTR) (err error) {
	r0 := C.EVP_KDF_CTX_set_params(C.EVP_KDF_CTX_PTR(ctx), C.OSSL_PARAM_PTR(params))
	if r0 != 1 {
		err = newError("EVP_KDF_CTX_set_params")
	}
	return
}

func EVP_KDF_derive(ctx EVP_KDF_CTX_PTR, key *byte, keylen int, params OSSL_PARAM_PTR) (err error) {
	r0 := C.EVP_KDF_derive(C.EVP_KDF_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(key)), C.size_t(keylen), C.OSSL_PARAM_PTR(params))
	if r0 != 1 {
		err = newError("EVP_KDF_derive")
	}
	return
}

func EVP_KDF_fetch(libctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (_r0 EVP_KDF_PTR, err error) {
	r0 := C.EVP_KDF_fetch(C.OSSL_LIB_CTX_PTR(libctx), (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)))
	_r0 = EVP_KDF_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_KDF_fetch")
	}
	return
}

func EVP_KDF_free(kdf EVP_KDF_PTR) {
	C.EVP_KDF_free(C.EVP_KDF_PTR(kdf))
}

func EVP_MAC_CTX_dup(arg0 EVP_MAC_CTX_PTR) (_r0 EVP_MAC_CTX_PTR, err error) {
	r0 := C.EVP_MAC_CTX_dup(C.EVP_MAC_CTX_PTR(arg0))
	_r0 = EVP_MAC_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_MAC_CTX_dup")
	}
	return
}

func EVP_MAC_CTX_free(arg0 EVP_MAC_CTX_PTR) {
	C.EVP_MAC_CTX_free(C.EVP_MAC_CTX_PTR(arg0))
}

func EVP_MAC_CTX_new(arg0 EVP_MAC_PTR) (_r0 EVP_MAC_CTX_PTR, err error) {
	r0 := C.EVP_MAC_CTX_new(C.EVP_MAC_PTR(arg0))
	_r0 = EVP_MAC_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_MAC_CTX_new")
	}
	return
}

func EVP_MAC_CTX_set_params(ctx EVP_MAC_CTX_PTR, params OSSL_PARAM_PTR) (err error) {
	r0 := C.EVP_MAC_CTX_set_params(C.EVP_MAC_CTX_PTR(ctx), C.OSSL_PARAM_PTR(params))
	if r0 != 1 {
		err = newError("EVP_MAC_CTX_set_params")
	}
	return
}

func EVP_MAC_fetch(ctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (_r0 EVP_MAC_PTR, err error) {
	r0 := C.EVP_MAC_fetch(C.OSSL_LIB_CTX_PTR(ctx), (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)))
	_r0 = EVP_MAC_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_MAC_fetch")
	}
	return
}

func EVP_MAC_final(ctx EVP_MAC_CTX_PTR, out *byte, outl *int, outsize int) (err error) {
	r0 := C.EVP_MAC_final(C.EVP_MAC_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(out)), (*C.size_t)(unsafe.Pointer(outl)), C.size_t(outsize))
	if r0 != 1 {
		err = newError("EVP_MAC_final")
	}
	return
}

func EVP_MAC_init(ctx EVP_MAC_CTX_PTR, key *byte, keylen int, params OSSL_PARAM_PTR) (err error) {
	r0 := C.EVP_MAC_init(C.EVP_MAC_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(key)), C.size_t(keylen), C.OSSL_PARAM_PTR(params))
	if r0 != 1 {
		err = newError("EVP_MAC_init")
	}
	return
}

func EVP_MAC_update(ctx EVP_MAC_CTX_PTR, data *byte, datalen int) (err error) {
	r0 := C.EVP_MAC_update(C.EVP_MAC_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(data)), C.size_t(datalen))
	if r0 != 1 {
		err = newError("EVP_MAC_update")
	}
	return
}

func EVP_MD_CTX_copy(out EVP_MD_CTX_PTR, in EVP_MD_CTX_PTR) (err error) {
	r0 := C.EVP_MD_CTX_copy(C.EVP_MD_CTX_PTR(out), C.EVP_MD_CTX_PTR(in))
	if r0 != 1 {
		err = newError("EVP_MD_CTX_copy")
	}
	return
}

func EVP_MD_CTX_copy_ex(out EVP_MD_CTX_PTR, in EVP_MD_CTX_PTR) (err error) {
	r0 := C.EVP_MD_CTX_copy_ex(C.EVP_MD_CTX_PTR(out), C.EVP_MD_CTX_PTR(in))
	if r0 != 1 {
		err = newError("EVP_MD_CTX_copy_ex")
	}
	return
}

func _EVP_MD_CTX_create() (_r0 EVP_MD_CTX_PTR, err error) {
	r0 := C.EVP_MD_CTX_create()
	_r0 = EVP_MD_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_MD_CTX_create")
	}
	return
}

func _EVP_MD_CTX_destroy(ctx EVP_MD_CTX_PTR) {
	C.EVP_MD_CTX_destroy(C.EVP_MD_CTX_PTR(ctx))
}

func _EVP_MD_CTX_free(ctx EVP_MD_CTX_PTR) {
	C.EVP_MD_CTX_free(C.EVP_MD_CTX_PTR(ctx))
}

func _EVP_MD_CTX_new() (_r0 EVP_MD_CTX_PTR, err error) {
	r0 := C.EVP_MD_CTX_new()
	_r0 = EVP_MD_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_MD_CTX_new")
	}
	return
}

func _EVP_MD_block_size(md EVP_MD_PTR) (_r0 int32) {
	r0 := C.EVP_MD_block_size(C.EVP_MD_PTR(md))
	_r0 = int32(r0)
	return
}

func EVP_MD_fetch(ctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (_r0 EVP_MD_PTR, err error) {
	r0 := C.EVP_MD_fetch(C.OSSL_LIB_CTX_PTR(ctx), (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)))
	_r0 = EVP_MD_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_MD_fetch")
	}
	return
}

func EVP_MD_free(md EVP_MD_PTR) {
	C.EVP_MD_free(C.EVP_MD_PTR(md))
}

func EVP_MD_get0_name(md EVP_MD_PTR) (_r0 *byte) {
	r0 := C.EVP_MD_get0_name(C.EVP_MD_PTR(md))
	_r0 = (*byte)(unsafe.Pointer(r0))
	return
}

func EVP_MD_get0_provider(md EVP_MD_PTR) (_r0 OSSL_PROVIDER_PTR, err error) {
	r0 := C.EVP_MD_get0_provider(C.EVP_MD_PTR(md))
	_r0 = OSSL_PROVIDER_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_MD_get0_provider")
	}
	return
}

func _EVP_MD_get_block_size(md EVP_MD_PTR) (_r0 int32) {
	r0 := C.EVP_MD_get_block_size(C.EVP_MD_PTR(md))
	_r0 = int32(r0)
	return
}

func _EVP_MD_get_size(md EVP_MD_PTR) (_r0 int32) {
	r0 := C.EVP_MD_get_size(C.EVP_MD_PTR(md))
	_r0 = int32(r0)
	return
}

func _EVP_MD_size(md EVP_MD_PTR) (_r0 int32) {
	r0 := C.EVP_MD_size(C.EVP_MD_PTR(md))
	_r0 = int32(r0)
	return
}

func EVP_PKEY_CTX_add1_hkdf_info(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 int32) (err error) {
	r0 := C.EVP_PKEY_CTX_add1_hkdf_info(C.EVP_PKEY_CTX_PTR(arg0), (*C.uchar)(unsafe.Pointer(arg1)), C.int(arg2))
	if r0 != 1 {
		err = newError("EVP_PKEY_CTX_add1_hkdf_info")
	}
	return
}

func EVP_PKEY_CTX_ctrl(ctx EVP_PKEY_CTX_PTR, keytype int32, optype int32, cmd int32, p1 int32, p2 unsafe.Pointer) (err error) {
	r0 := C.EVP_PKEY_CTX_ctrl(C.EVP_PKEY_CTX_PTR(ctx), C.int(keytype), C.int(optype), C.int(cmd), C.int(p1), p2)
	if r0 != 1 {
		err = newError("EVP_PKEY_CTX_ctrl")
	}
	return
}

func EVP_PKEY_CTX_free(arg0 EVP_PKEY_CTX_PTR) {
	C.EVP_PKEY_CTX_free(C.EVP_PKEY_CTX_PTR(arg0))
}

func EVP_PKEY_CTX_new(arg0 EVP_PKEY_PTR, arg1 ENGINE_PTR) (_r0 EVP_PKEY_CTX_PTR, err error) {
	r0 := C.EVP_PKEY_CTX_new(C.EVP_PKEY_PTR(arg0), C.ENGINE_PTR(arg1))
	_r0 = EVP_PKEY_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_CTX_new")
	}
	return
}

func EVP_PKEY_CTX_new_from_pkey(libctx OSSL_LIB_CTX_PTR, pkey EVP_PKEY_PTR, propquery *byte) (_r0 EVP_PKEY_CTX_PTR, err error) {
	r0 := C.EVP_PKEY_CTX_new_from_pkey(C.OSSL_LIB_CTX_PTR(libctx), C.EVP_PKEY_PTR(pkey), (*C.char)(unsafe.Pointer(propquery)))
	_r0 = EVP_PKEY_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_CTX_new_from_pkey")
	}
	return
}

func EVP_PKEY_CTX_new_id(id int32, e ENGINE_PTR) (_r0 EVP_PKEY_CTX_PTR, err error) {
	r0 := C.EVP_PKEY_CTX_new_id(C.int(id), C.ENGINE_PTR(e))
	_r0 = EVP_PKEY_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_CTX_new_id")
	}
	return
}

func EVP_PKEY_CTX_set0_rsa_oaep_label(ctx EVP_PKEY_CTX_PTR, label unsafe.Pointer, len int32) (err error) {
	r0 := C.EVP_PKEY_CTX_set0_rsa_oaep_label(C.EVP_PKEY_CTX_PTR(ctx), label, C.int(len))
	if r0 != 1 {
		err = newError("EVP_PKEY_CTX_set0_rsa_oaep_label")
	}
	return
}

func EVP_PKEY_CTX_set1_hkdf_key(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 int32) (err error) {
	r0 := C.EVP_PKEY_CTX_set1_hkdf_key(C.EVP_PKEY_CTX_PTR(arg0), (*C.uchar)(unsafe.Pointer(arg1)), C.int(arg2))
	if r0 != 1 {
		err = newError("EVP_PKEY_CTX_set1_hkdf_key")
	}
	return
}

func EVP_PKEY_CTX_set1_hkdf_salt(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 int32) (err error) {
	r0 := C.EVP_PKEY_CTX_set1_hkdf_salt(C.EVP_PKEY_CTX_PTR(arg0), (*C.uchar)(unsafe.Pointer(arg1)), C.int(arg2))
	if r0 != 1 {
		err = newError("EVP_PKEY_CTX_set1_hkdf_salt")
	}
	return
}

func EVP_PKEY_CTX_set_hkdf_md(arg0 EVP_PKEY_CTX_PTR, arg1 EVP_MD_PTR) (err error) {
	r0 := C.EVP_PKEY_CTX_set_hkdf_md(C.EVP_PKEY_CTX_PTR(arg0), C.EVP_MD_PTR(arg1))
	if r0 != 1 {
		err = newError("EVP_PKEY_CTX_set_hkdf_md")
	}
	return
}

func EVP_PKEY_CTX_set_hkdf_mode(arg0 EVP_PKEY_CTX_PTR, arg1 int32) (err error) {
	r0 := C.EVP_PKEY_CTX_set_hkdf_mode(C.EVP_PKEY_CTX_PTR(arg0), C.int(arg1))
	if r0 != 1 {
		err = newError("EVP_PKEY_CTX_set_hkdf_mode")
	}
	return
}

func EVP_PKEY_Q_keygen_EC(ctx OSSL_LIB_CTX_PTR, propq *byte, typ *byte, arg1 *byte) (_r0 EVP_PKEY_PTR, err error) {
	r0 := C.EVP_PKEY_Q_keygen_EC(C.OSSL_LIB_CTX_PTR(ctx), (*C.char)(unsafe.Pointer(propq)), (*C.char)(unsafe.Pointer(typ)), (*C.char)(unsafe.Pointer(arg1)))
	_r0 = EVP_PKEY_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_Q_keygen_EC")
	}
	return
}

func EVP_PKEY_Q_keygen_ED25519(ctx OSSL_LIB_CTX_PTR, propq *byte, typ *byte) (_r0 EVP_PKEY_PTR, err error) {
	r0 := C.EVP_PKEY_Q_keygen_ED25519(C.OSSL_LIB_CTX_PTR(ctx), (*C.char)(unsafe.Pointer(propq)), (*C.char)(unsafe.Pointer(typ)))
	_r0 = EVP_PKEY_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_Q_keygen_ED25519")
	}
	return
}

func EVP_PKEY_Q_keygen_RSA(ctx OSSL_LIB_CTX_PTR, propq *byte, typ *byte, arg1 int) (_r0 EVP_PKEY_PTR, err error) {
	r0 := C.EVP_PKEY_Q_keygen_RSA(C.OSSL_LIB_CTX_PTR(ctx), (*C.char)(unsafe.Pointer(propq)), (*C.char)(unsafe.Pointer(typ)), C.size_t(arg1))
	_r0 = EVP_PKEY_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_Q_keygen_RSA")
	}
	return
}

func EVP_PKEY_assign(pkey EVP_PKEY_PTR, typ int32, key unsafe.Pointer) (err error) {
	r0 := C.EVP_PKEY_assign(C.EVP_PKEY_PTR(pkey), C.int(typ), key)
	if r0 != 1 {
		err = newError("EVP_PKEY_assign")
	}
	return
}

func _EVP_PKEY_bits(pkey EVP_PKEY_PTR) (_r0 int32) {
	r0 := C.EVP_PKEY_bits(C.EVP_PKEY_PTR(pkey))
	_r0 = int32(r0)
	return
}

func EVP_PKEY_decrypt(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 *int, arg3 *byte, arg4 int) (err error) {
	r0 := C.EVP_PKEY_decrypt(C.EVP_PKEY_CTX_PTR(arg0), (*C.uchar)(unsafe.Pointer(arg1)), (*C.size_t)(unsafe.Pointer(arg2)), (*C.uchar)(unsafe.Pointer(arg3)), C.size_t(arg4))
	if r0 != 1 {
		err = newError("EVP_PKEY_decrypt")
	}
	return
}

func EVP_PKEY_decrypt_init(arg0 EVP_PKEY_CTX_PTR) (err error) {
	r0 := C.EVP_PKEY_decrypt_init(C.EVP_PKEY_CTX_PTR(arg0))
	if r0 != 1 {
		err = newError("EVP_PKEY_decrypt_init")
	}
	return
}

func EVP_PKEY_derive(ctx EVP_PKEY_CTX_PTR, key *byte, keylen *int) (err error) {
	r0 := C.EVP_PKEY_derive(C.EVP_PKEY_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(key)), (*C.size_t)(unsafe.Pointer(keylen)))
	if r0 != 1 {
		err = newError("EVP_PKEY_derive")
	}
	return
}

func EVP_PKEY_derive_init(ctx EVP_PKEY_CTX_PTR) (err error) {
	r0 := C.EVP_PKEY_derive_init(C.EVP_PKEY_CTX_PTR(ctx))
	if r0 != 1 {
		err = newError("EVP_PKEY_derive_init")
	}
	return
}

func EVP_PKEY_derive_set_peer(ctx EVP_PKEY_CTX_PTR, peer EVP_PKEY_PTR) (err error) {
	r0 := C.EVP_PKEY_derive_set_peer(C.EVP_PKEY_CTX_PTR(ctx), C.EVP_PKEY_PTR(peer))
	if r0 != 1 {
		err = newError("EVP_PKEY_derive_set_peer")
	}
	return
}

func EVP_PKEY_encrypt(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 *int, arg3 *byte, arg4 int) (err error) {
	r0 := C.EVP_PKEY_encrypt(C.EVP_PKEY_CTX_PTR(arg0), (*C.uchar)(unsafe.Pointer(arg1)), (*C.size_t)(unsafe.Pointer(arg2)), (*C.uchar)(unsafe.Pointer(arg3)), C.size_t(arg4))
	if r0 != 1 {
		err = newError("EVP_PKEY_encrypt")
	}
	return
}

func EVP_PKEY_encrypt_init(arg0 EVP_PKEY_CTX_PTR) (err error) {
	r0 := C.EVP_PKEY_encrypt_init(C.EVP_PKEY_CTX_PTR(arg0))
	if r0 != 1 {
		err = newError("EVP_PKEY_encrypt_init")
	}
	return
}

func EVP_PKEY_free(key EVP_PKEY_PTR) {
	C.EVP_PKEY_free(C.EVP_PKEY_PTR(key))
}

func EVP_PKEY_fromdata(ctx EVP_PKEY_CTX_PTR, pkey *EVP_PKEY_PTR, selection int32, params OSSL_PARAM_PTR) (err error) {
	r0 := C.EVP_PKEY_fromdata(C.EVP_PKEY_CTX_PTR(ctx), (*C.EVP_PKEY_PTR)(unsafe.Pointer(pkey)), C.int(selection), C.OSSL_PARAM_PTR(params))
	if r0 != 1 {
		err = newError("EVP_PKEY_fromdata")
	}
	return
}

func EVP_PKEY_fromdata_init(ctx EVP_PKEY_CTX_PTR) (err error) {
	r0 := C.EVP_PKEY_fromdata_init(C.EVP_PKEY_CTX_PTR(ctx))
	if r0 != 1 {
		err = newError("EVP_PKEY_fromdata_init")
	}
	return
}

func EVP_PKEY_get0(pkey EVP_PKEY_PTR) (_r0 unsafe.Pointer, err error) {
	r0 := C.EVP_PKEY_get0(C.EVP_PKEY_PTR(pkey))
	_r0 = unsafe.Pointer(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_get0")
	}
	return
}

func EVP_PKEY_get0_DSA(pkey EVP_PKEY_PTR) (_r0 DSA_PTR, err error) {
	r0 := C.EVP_PKEY_get0_DSA(C.EVP_PKEY_PTR(pkey))
	_r0 = DSA_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_get0_DSA")
	}
	return
}

func EVP_PKEY_get0_EC_KEY(pkey EVP_PKEY_PTR) (_r0 EC_KEY_PTR, err error) {
	r0 := C.EVP_PKEY_get0_EC_KEY(C.EVP_PKEY_PTR(pkey))
	_r0 = EC_KEY_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_get0_EC_KEY")
	}
	return
}

func EVP_PKEY_get1_RSA(pkey EVP_PKEY_PTR) (_r0 RSA_PTR, err error) {
	r0 := C.EVP_PKEY_get1_RSA(C.EVP_PKEY_PTR(pkey))
	_r0 = RSA_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_get1_RSA")
	}
	return
}

func EVP_PKEY_get1_encoded_public_key(pkey EVP_PKEY_PTR, ppub **byte) (_r0 int, err error) {
	r0 := C.EVP_PKEY_get1_encoded_public_key(C.EVP_PKEY_PTR(pkey), (**C.uchar)(unsafe.Pointer(ppub)))
	_r0 = int(r0)
	if _r0 == 0 {
		err = newError("EVP_PKEY_get1_encoded_public_key")
	}
	return
}

func _EVP_PKEY_get_bits(pkey EVP_PKEY_PTR) (_r0 int32) {
	r0 := C.EVP_PKEY_get_bits(C.EVP_PKEY_PTR(pkey))
	_r0 = int32(r0)
	return
}

func EVP_PKEY_get_bn_param(pkey EVP_PKEY_PTR, key_name *byte, bn *BIGNUM_PTR) (err error) {
	r0 := C.EVP_PKEY_get_bn_param(C.EVP_PKEY_PTR(pkey), (*C.char)(unsafe.Pointer(key_name)), (*C.BIGNUM_PTR)(unsafe.Pointer(bn)))
	if r0 != 1 {
		err = newError("EVP_PKEY_get_bn_param")
	}
	return
}

func EVP_PKEY_get_raw_private_key(pkey EVP_PKEY_PTR, priv *byte, len *int) (err error) {
	r0 := C.EVP_PKEY_get_raw_private_key(C.EVP_PKEY_PTR(pkey), (*C.uchar)(unsafe.Pointer(priv)), (*C.size_t)(unsafe.Pointer(len)))
	if r0 != 1 {
		err = newError("EVP_PKEY_get_raw_private_key")
	}
	return
}

func EVP_PKEY_get_raw_public_key(pkey EVP_PKEY_PTR, pub *byte, len *int) (err error) {
	r0 := C.EVP_PKEY_get_raw_public_key(C.EVP_PKEY_PTR(pkey), (*C.uchar)(unsafe.Pointer(pub)), (*C.size_t)(unsafe.Pointer(len)))
	if r0 != 1 {
		err = newError("EVP_PKEY_get_raw_public_key")
	}
	return
}

func _EVP_PKEY_get_size(pkey EVP_PKEY_PTR) (_r0 int32) {
	r0 := C.EVP_PKEY_get_size(C.EVP_PKEY_PTR(pkey))
	_r0 = int32(r0)
	return
}

func EVP_PKEY_keygen(ctx EVP_PKEY_CTX_PTR, ppkey *EVP_PKEY_PTR) (err error) {
	r0 := C.EVP_PKEY_keygen(C.EVP_PKEY_CTX_PTR(ctx), (*C.EVP_PKEY_PTR)(unsafe.Pointer(ppkey)))
	if r0 != 1 {
		err = newError("EVP_PKEY_keygen")
	}
	return
}

func EVP_PKEY_keygen_init(ctx EVP_PKEY_CTX_PTR) (err error) {
	r0 := C.EVP_PKEY_keygen_init(C.EVP_PKEY_CTX_PTR(ctx))
	if r0 != 1 {
		err = newError("EVP_PKEY_keygen_init")
	}
	return
}

func EVP_PKEY_new() (_r0 EVP_PKEY_PTR, err error) {
	r0 := C.EVP_PKEY_new()
	_r0 = EVP_PKEY_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_new")
	}
	return
}

func EVP_PKEY_new_raw_private_key(typ int32, e ENGINE_PTR, key *byte, keylen int) (_r0 EVP_PKEY_PTR, err error) {
	r0 := C.EVP_PKEY_new_raw_private_key(C.int(typ), C.ENGINE_PTR(e), (*C.uchar)(unsafe.Pointer(key)), C.size_t(keylen))
	_r0 = EVP_PKEY_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_new_raw_private_key")
	}
	return
}

func EVP_PKEY_new_raw_public_key(typ int32, e ENGINE_PTR, key *byte, keylen int) (_r0 EVP_PKEY_PTR, err error) {
	r0 := C.EVP_PKEY_new_raw_public_key(C.int(typ), C.ENGINE_PTR(e), (*C.uchar)(unsafe.Pointer(key)), C.size_t(keylen))
	_r0 = EVP_PKEY_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_PKEY_new_raw_public_key")
	}
	return
}

func EVP_PKEY_paramgen(ctx EVP_PKEY_CTX_PTR, ppkey *EVP_PKEY_PTR) (err error) {
	r0 := C.EVP_PKEY_paramgen(C.EVP_PKEY_CTX_PTR(ctx), (*C.EVP_PKEY_PTR)(unsafe.Pointer(ppkey)))
	if r0 != 1 {
		err = newError("EVP_PKEY_paramgen")
	}
	return
}

func EVP_PKEY_paramgen_init(ctx EVP_PKEY_CTX_PTR) (err error) {
	r0 := C.EVP_PKEY_paramgen_init(C.EVP_PKEY_CTX_PTR(ctx))
	if r0 != 1 {
		err = newError("EVP_PKEY_paramgen_init")
	}
	return
}

func EVP_PKEY_set1_EC_KEY(pkey EVP_PKEY_PTR, key EC_KEY_PTR) (err error) {
	r0 := C.EVP_PKEY_set1_EC_KEY(C.EVP_PKEY_PTR(pkey), C.EC_KEY_PTR(key))
	if r0 != 1 {
		err = newError("EVP_PKEY_set1_EC_KEY")
	}
	return
}

func EVP_PKEY_set1_encoded_public_key(pkey EVP_PKEY_PTR, pub *byte, publen int) (err error) {
	r0 := C.EVP_PKEY_set1_encoded_public_key(C.EVP_PKEY_PTR(pkey), (*C.uchar)(unsafe.Pointer(pub)), C.size_t(publen))
	if r0 != 1 {
		err = newError("EVP_PKEY_set1_encoded_public_key")
	}
	return
}

func EVP_PKEY_sign(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 *int, arg3 *byte, arg4 int) (err error) {
	r0 := C.EVP_PKEY_sign(C.EVP_PKEY_CTX_PTR(arg0), (*C.uchar)(unsafe.Pointer(arg1)), (*C.size_t)(unsafe.Pointer(arg2)), (*C.uchar)(unsafe.Pointer(arg3)), C.size_t(arg4))
	if r0 != 1 {
		err = newError("EVP_PKEY_sign")
	}
	return
}

func EVP_PKEY_sign_init(arg0 EVP_PKEY_CTX_PTR) (err error) {
	r0 := C.EVP_PKEY_sign_init(C.EVP_PKEY_CTX_PTR(arg0))
	if r0 != 1 {
		err = newError("EVP_PKEY_sign_init")
	}
	return
}

func _EVP_PKEY_size(pkey EVP_PKEY_PTR) (_r0 int32) {
	r0 := C.EVP_PKEY_size(C.EVP_PKEY_PTR(pkey))
	_r0 = int32(r0)
	return
}

func EVP_PKEY_up_ref(key EVP_PKEY_PTR) (err error) {
	r0 := C.EVP_PKEY_up_ref(C.EVP_PKEY_PTR(key))
	if r0 != 1 {
		err = newError("EVP_PKEY_up_ref")
	}
	return
}

func EVP_PKEY_verify(ctx EVP_PKEY_CTX_PTR, sig *byte, siglen int, tbs *byte, tbslen int) (err error) {
	r0 := C.EVP_PKEY_verify(C.EVP_PKEY_CTX_PTR(ctx), (*C.uchar)(unsafe.Pointer(sig)), C.size_t(siglen), (*C.uchar)(unsafe.Pointer(tbs)), C.size_t(tbslen))
	if r0 != 1 {
		err = newError("EVP_PKEY_verify")
	}
	return
}

func EVP_PKEY_verify_init(arg0 EVP_PKEY_CTX_PTR) (err error) {
	r0 := C.EVP_PKEY_verify_init(C.EVP_PKEY_CTX_PTR(arg0))
	if r0 != 1 {
		err = newError("EVP_PKEY_verify_init")
	}
	return
}

func EVP_SIGNATURE_fetch(ctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (_r0 EVP_SIGNATURE_PTR, err error) {
	r0 := C.EVP_SIGNATURE_fetch(C.OSSL_LIB_CTX_PTR(ctx), (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)))
	_r0 = EVP_SIGNATURE_PTR(r0)
	if _r0 == nil {
		err = newError("EVP_SIGNATURE_fetch")
	}
	return
}

func EVP_SIGNATURE_free(signature EVP_SIGNATURE_PTR) {
	C.EVP_SIGNATURE_free(C.EVP_SIGNATURE_PTR(signature))
}

func EVP_aes_128_cbc() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_128_cbc()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_128_ctr() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_128_ctr()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_128_ecb() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_128_ecb()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_128_gcm() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_128_gcm()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_192_cbc() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_192_cbc()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_192_ctr() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_192_ctr()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_192_ecb() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_192_ecb()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_192_gcm() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_192_gcm()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_256_cbc() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_256_cbc()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_256_ctr() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_256_ctr()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_256_ecb() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_256_ecb()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_aes_256_gcm() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_aes_256_gcm()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_default_properties_enable_fips(libctx OSSL_LIB_CTX_PTR, enable int32) (err error) {
	r0 := C.EVP_default_properties_enable_fips(C.OSSL_LIB_CTX_PTR(libctx), C.int(enable))
	if r0 != 1 {
		err = newError("EVP_default_properties_enable_fips")
	}
	return
}

func EVP_default_properties_is_fips_enabled(libctx OSSL_LIB_CTX_PTR) (_r0 int32) {
	r0 := C.EVP_default_properties_is_fips_enabled(C.OSSL_LIB_CTX_PTR(libctx))
	_r0 = int32(r0)
	return
}

func EVP_des_cbc() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_des_cbc()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_des_ecb() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_des_ecb()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_des_ede3_cbc() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_des_ede3_cbc()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_des_ede3_ecb() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_des_ede3_ecb()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_md4() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_md4()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_md5() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_md5()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_md5_sha1() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_md5_sha1()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_rc4() (_r0 EVP_CIPHER_PTR) {
	r0 := C.EVP_rc4()
	_r0 = EVP_CIPHER_PTR(r0)
	return
}

func EVP_sha1() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha1()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_sha224() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha224()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_sha256() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha256()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_sha384() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha384()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_sha3_224() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha3_224()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_sha3_256() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha3_256()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_sha3_384() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha3_384()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_sha3_512() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha3_512()
	_r0 = EVP_MD_PTR(r0)
	return
}

func EVP_sha512() (_r0 EVP_MD_PTR) {
	r0 := C.EVP_sha512()
	_r0 = EVP_MD_PTR(r0)
	return
}

func FIPS_mode() (_r0 int32) {
	r0 := C.FIPS_mode()
	_r0 = int32(r0)
	return
}

func FIPS_mode_set(r int32) (err error) {
	r0 := C.FIPS_mode_set(C.int(r))
	if r0 != 1 {
		err = newError("FIPS_mode_set")
	}
	return
}

func HMAC_CTX_cleanup(arg0 HMAC_CTX_PTR) {
	C.HMAC_CTX_cleanup(C.HMAC_CTX_PTR(arg0))
}

func HMAC_CTX_copy(dest HMAC_CTX_PTR, src HMAC_CTX_PTR) (err error) {
	r0 := C.HMAC_CTX_copy(C.HMAC_CTX_PTR(dest), C.HMAC_CTX_PTR(src))
	if r0 != 1 {
		err = newError("HMAC_CTX_copy")
	}
	return
}

func HMAC_CTX_free(arg0 HMAC_CTX_PTR) {
	C.HMAC_CTX_free(C.HMAC_CTX_PTR(arg0))
}

func HMAC_CTX_init(arg0 HMAC_CTX_PTR) {
	C.HMAC_CTX_init(C.HMAC_CTX_PTR(arg0))
}

func HMAC_CTX_new() (_r0 HMAC_CTX_PTR, err error) {
	r0 := C.HMAC_CTX_new()
	_r0 = HMAC_CTX_PTR(r0)
	if _r0 == nil {
		err = newError("HMAC_CTX_new")
	}
	return
}

func HMAC_Final(arg0 HMAC_CTX_PTR, arg1 *byte, arg2 *uint32) (err error) {
	r0 := C.HMAC_Final(C.HMAC_CTX_PTR(arg0), (*C.uchar)(unsafe.Pointer(arg1)), (*C.uint)(unsafe.Pointer(arg2)))
	if r0 != 1 {
		err = newError("HMAC_Final")
	}
	return
}

func HMAC_Init_ex(arg0 HMAC_CTX_PTR, arg1 unsafe.Pointer, arg2 int32, arg3 EVP_MD_PTR, arg4 ENGINE_PTR) (err error) {
	r0 := C.HMAC_Init_ex(C.HMAC_CTX_PTR(arg0), arg1, C.int(arg2), C.EVP_MD_PTR(arg3), C.ENGINE_PTR(arg4))
	if r0 != 1 {
		err = newError("HMAC_Init_ex")
	}
	return
}

func HMAC_Update(arg0 HMAC_CTX_PTR, arg1 *byte, arg2 int) (err error) {
	r0 := C.HMAC_Update(C.HMAC_CTX_PTR(arg0), (*C.uchar)(unsafe.Pointer(arg1)), C.size_t(arg2))
	if r0 != 1 {
		err = newError("HMAC_Update")
	}
	return
}

func MD5_Final(md *byte, c MD5_CTX_PTR) (err error) {
	r0 := C.MD5_Final((*C.uchar)(unsafe.Pointer(md)), C.MD5_CTX_PTR(c))
	if r0 != 1 {
		err = newError("MD5_Final")
	}
	return
}

func MD5_Init(c MD5_CTX_PTR) (err error) {
	r0 := C.MD5_Init(C.MD5_CTX_PTR(c))
	if r0 != 1 {
		err = newError("MD5_Init")
	}
	return
}

func MD5_Update(c MD5_CTX_PTR, data unsafe.Pointer, len int) (err error) {
	r0 := C.MD5_Update(C.MD5_CTX_PTR(c), data, C.size_t(len))
	if r0 != 1 {
		err = newError("MD5_Update")
	}
	return
}

func OBJ_nid2sn(n int32) (_r0 *byte) {
	r0 := C.OBJ_nid2sn(C.int(n))
	_r0 = (*byte)(unsafe.Pointer(r0))
	return
}

func OPENSSL_add_all_algorithms_conf() {
	C.OPENSSL_add_all_algorithms_conf()
}

func OPENSSL_init() {
	C.OPENSSL_init()
}

func OPENSSL_init_crypto(ops uint64, settings OPENSSL_INIT_SETTINGS_PTR) (err error) {
	r0 := C.OPENSSL_init_crypto(C.uint64_t(ops), C.OPENSSL_INIT_SETTINGS_PTR(settings))
	if r0 != 1 {
		err = newError("OPENSSL_init_crypto")
	}
	return
}

func OSSL_PARAM_BLD_free(bld OSSL_PARAM_BLD_PTR) {
	C.OSSL_PARAM_BLD_free(C.OSSL_PARAM_BLD_PTR(bld))
}

func OSSL_PARAM_BLD_new() (_r0 OSSL_PARAM_BLD_PTR, err error) {
	r0 := C.OSSL_PARAM_BLD_new()
	_r0 = OSSL_PARAM_BLD_PTR(r0)
	if _r0 == nil {
		err = newError("OSSL_PARAM_BLD_new")
	}
	return
}

func OSSL_PARAM_BLD_push_BN(bld OSSL_PARAM_BLD_PTR, key *byte, bn BIGNUM_PTR) (err error) {
	r0 := C.OSSL_PARAM_BLD_push_BN(C.OSSL_PARAM_BLD_PTR(bld), (*C.char)(unsafe.Pointer(key)), C.BIGNUM_PTR(bn))
	if r0 != 1 {
		err = newError("OSSL_PARAM_BLD_push_BN")
	}
	return
}

func OSSL_PARAM_BLD_push_int32(bld OSSL_PARAM_BLD_PTR, key *byte, num int32) (err error) {
	r0 := C.OSSL_PARAM_BLD_push_int32(C.OSSL_PARAM_BLD_PTR(bld), (*C.char)(unsafe.Pointer(key)), C.int32_t(num))
	if r0 != 1 {
		err = newError("OSSL_PARAM_BLD_push_int32")
	}
	return
}

func OSSL_PARAM_BLD_push_octet_string(bld OSSL_PARAM_BLD_PTR, key *byte, buf unsafe.Pointer, bsize int) (err error) {
	r0 := C.OSSL_PARAM_BLD_push_octet_string(C.OSSL_PARAM_BLD_PTR(bld), (*C.char)(unsafe.Pointer(key)), buf, C.size_t(bsize))
	if r0 != 1 {
		err = newError("OSSL_PARAM_BLD_push_octet_string")
	}
	return
}

func OSSL_PARAM_BLD_push_utf8_string(bld OSSL_PARAM_BLD_PTR, key *byte, buf *byte, bsize int) (err error) {
	r0 := C.OSSL_PARAM_BLD_push_utf8_string(C.OSSL_PARAM_BLD_PTR(bld), (*C.char)(unsafe.Pointer(key)), (*C.char)(unsafe.Pointer(buf)), C.size_t(bsize))
	if r0 != 1 {
		err = newError("OSSL_PARAM_BLD_push_utf8_string")
	}
	return
}

func OSSL_PARAM_BLD_to_param(bld OSSL_PARAM_BLD_PTR) (_r0 OSSL_PARAM_PTR, err error) {
	r0 := C.OSSL_PARAM_BLD_to_param(C.OSSL_PARAM_BLD_PTR(bld))
	_r0 = OSSL_PARAM_PTR(r0)
	if _r0 == nil {
		err = newError("OSSL_PARAM_BLD_to_param")
	}
	return
}

func OSSL_PARAM_free(p OSSL_PARAM_PTR) {
	C.OSSL_PARAM_free(C.OSSL_PARAM_PTR(p))
}

func OSSL_PROVIDER_available(libctx OSSL_LIB_CTX_PTR, name *byte) (_r0 int32) {
	r0 := C.OSSL_PROVIDER_available(C.OSSL_LIB_CTX_PTR(libctx), (*C.char)(unsafe.Pointer(name)))
	_r0 = int32(r0)
	return
}

func OSSL_PROVIDER_get0_name(prov OSSL_PROVIDER_PTR) (_r0 *byte) {
	r0 := C.OSSL_PROVIDER_get0_name(C.OSSL_PROVIDER_PTR(prov))
	_r0 = (*byte)(unsafe.Pointer(r0))
	return
}

func OSSL_PROVIDER_try_load(libctx OSSL_LIB_CTX_PTR, name *byte, retain_fallbacks int32) (_r0 OSSL_PROVIDER_PTR, err error) {
	r0 := C.OSSL_PROVIDER_try_load(C.OSSL_LIB_CTX_PTR(libctx), (*C.char)(unsafe.Pointer(name)), C.int(retain_fallbacks))
	_r0 = OSSL_PROVIDER_PTR(r0)
	if _r0 == nil {
		err = newError("OSSL_PROVIDER_try_load")
	}
	return
}

func _OpenSSL_version(typ int32) (_r0 *byte) {
	r0 := C.OpenSSL_version(C.int(typ))
	_r0 = (*byte)(unsafe.Pointer(r0))
	return
}

func PKCS5_PBKDF2_HMAC(pass *byte, passlen int32, salt *byte, saltlen int32, iter int32, digest EVP_MD_PTR, keylen int32, out *byte) (err error) {
	r0 := C.PKCS5_PBKDF2_HMAC((*C.char)(unsafe.Pointer(pass)), C.int(passlen), (*C.uchar)(unsafe.Pointer(salt)), C.int(saltlen), C.int(iter), C.EVP_MD_PTR(digest), C.int(keylen), (*C.uchar)(unsafe.Pointer(out)))
	if r0 != 1 {
		err = newError("PKCS5_PBKDF2_HMAC")
	}
	return
}

func RAND_bytes(buf *byte, num int32) (err error) {
	r0 := C.RAND_bytes((*C.uchar)(unsafe.Pointer(buf)), C.int(num))
	if r0 != 1 {
		err = newError("RAND_bytes")
	}
	return
}

func RSA_free(r RSA_PTR) {
	C.RSA_free(C.RSA_PTR(r))
}

func RSA_get0_crt_params(r RSA_PTR, dmp1 *BIGNUM_PTR, dmq1 *BIGNUM_PTR, iqmp *BIGNUM_PTR) {
	C.RSA_get0_crt_params(C.RSA_PTR(r), (*C.BIGNUM_PTR)(unsafe.Pointer(dmp1)), (*C.BIGNUM_PTR)(unsafe.Pointer(dmq1)), (*C.BIGNUM_PTR)(unsafe.Pointer(iqmp)))
}

func RSA_get0_factors(r RSA_PTR, p *BIGNUM_PTR, q *BIGNUM_PTR) {
	C.RSA_get0_factors(C.RSA_PTR(r), (*C.BIGNUM_PTR)(unsafe.Pointer(p)), (*C.BIGNUM_PTR)(unsafe.Pointer(q)))
}

func RSA_get0_key(r RSA_PTR, n *BIGNUM_PTR, e *BIGNUM_PTR, d *BIGNUM_PTR) {
	C.RSA_get0_key(C.RSA_PTR(r), (*C.BIGNUM_PTR)(unsafe.Pointer(n)), (*C.BIGNUM_PTR)(unsafe.Pointer(e)), (*C.BIGNUM_PTR)(unsafe.Pointer(d)))
}

func RSA_new() (_r0 RSA_PTR, err error) {
	r0 := C.RSA_new()
	_r0 = RSA_PTR(r0)
	if _r0 == nil {
		err = newError("RSA_new")
	}
	return
}

func RSA_set0_crt_params(r RSA_PTR, dmp1 BIGNUM_PTR, dmq1 BIGNUM_PTR, iqmp BIGNUM_PTR) (err error) {
	r0 := C.RSA_set0_crt_params(C.RSA_PTR(r), C.BIGNUM_PTR(dmp1), C.BIGNUM_PTR(dmq1), C.BIGNUM_PTR(iqmp))
	if r0 != 1 {
		err = newError("RSA_set0_crt_params")
	}
	return
}

func RSA_set0_factors(r RSA_PTR, p BIGNUM_PTR, q BIGNUM_PTR) (err error) {
	r0 := C.RSA_set0_factors(C.RSA_PTR(r), C.BIGNUM_PTR(p), C.BIGNUM_PTR(q))
	if r0 != 1 {
		err = newError("RSA_set0_factors")
	}
	return
}

func RSA_set0_key(r RSA_PTR, n BIGNUM_PTR, e BIGNUM_PTR, d BIGNUM_PTR) (err error) {
	r0 := C.RSA_set0_key(C.RSA_PTR(r), C.BIGNUM_PTR(n), C.BIGNUM_PTR(e), C.BIGNUM_PTR(d))
	if r0 != 1 {
		err = newError("RSA_set0_key")
	}
	return
}

func SHA1_Final(md *byte, c SHA_CTX_PTR) (err error) {
	r0 := C.SHA1_Final((*C.uchar)(unsafe.Pointer(md)), C.SHA_CTX_PTR(c))
	if r0 != 1 {
		err = newError("SHA1_Final")
	}
	return
}

func SHA1_Init(c SHA_CTX_PTR) (err error) {
	r0 := C.SHA1_Init(C.SHA_CTX_PTR(c))
	if r0 != 1 {
		err = newError("SHA1_Init")
	}
	return
}

func SHA1_Update(c SHA_CTX_PTR, data unsafe.Pointer, len int) (err error) {
	r0 := C.SHA1_Update(C.SHA_CTX_PTR(c), data, C.size_t(len))
	if r0 != 1 {
		err = newError("SHA1_Update")
	}
	return
}

func _SSLeay_version(typ int32) (_r0 *byte) {
	r0 := C.SSLeay_version(C.int(typ))
	_r0 = (*byte)(unsafe.Pointer(r0))
	return
}

func BN_expand2(a BIGNUM_PTR, n int32) (_r0 BIGNUM_PTR, err error) {
	r0 := C.bn_expand2(C.BIGNUM_PTR(a), C.int(n))
	_r0 = BIGNUM_PTR(r0)
	if _r0 == nil {
		err = newError("bn_expand2")
	}
	return
}
