package main

import (
	"fmt"
	"io"
	"slices"
	"strconv"
	"strings"

	"github.com/golang-fips/openssl/v2/internal/mkcgo"
)

// generateGo output Go source file from src.
func generateGo(src *mkcgo.Source, w io.Writer) {
	// Output header notice and package declaration.
	fmt.Fprintf(w, "// Code generated by mkcgo. DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", *packageName)

	// This block outputs C header includes and forward declarations for loader functions.
	fmt.Fprintf(w, "/*\n")
	if *includeHeader != "" {
		fmt.Fprintf(w, "#include \"%s\"\n", *includeHeader)
	}
	for _, file := range src.Files {
		fmt.Fprintf(w, "#include %q\n", file)
	}
	for _, tag := range src.Tags() {
		fmt.Fprintf(w, "void __mkcgoLoad_%s(void* handle);\n", tag)
	}
	fmt.Fprintf(w, "*/\n")
	fmt.Fprintf(w, "import \"C\"\n")
	fmt.Fprintf(w, "import \"unsafe\"\n\n")

	// Generate Go enum values for C enums.
	generateGoEnums(src.Enums, w)

	// Generate type aliases for all
	generateGoAliases(src.Funcs, w)

	// Generate Go wrapper functions that load the C symbols.
	for _, tag := range src.Tags() {
		fmt.Fprintf(w, "func mkcgoLoad_%s(handle unsafe.Pointer) {\n", tag)
		fmt.Fprintf(w, "\tC.__mkcgoLoad_%s(handle)\n", tag)
		fmt.Fprintf(w, "}\n\n")
	}

	// Generate function wrappers.
	for _, fn := range src.Funcs {
		generateGoFn(fn, w)
	}
}

// generateGoEnums generates Go enum values for C enums.
func generateGoEnums(enums []*mkcgo.Enum, w io.Writer) {
	if len(enums) == 0 {
		return
	}
	fmt.Fprintf(w, "const (\n")
	for _, enum := range enums {
		fmt.Fprintf(w, "\t%s = %s\n", enum.Name, enum.Value)
	}
	fmt.Fprintf(w, ")\n\n")
}

// generateGoAliases generates Go type aliases for C types.
func generateGoAliases(funcs []*mkcgo.Func, w io.Writer) {
	// Traverse all functions and collect the unique C types.
	ctypes := make(map[string]struct{})
	for _, fn := range funcs {
		handleType := func(typ string) {
			if typ == "" {
				return
			}
			typ = strings.TrimPrefix(typ, "const ")
			typ = strings.TrimRight(typ, "*")
			if _, ok := ctypes[typ]; ok {
				return
			}
			ctypes[typ] = struct{}{}
		}
		for _, p := range fn.Params {
			if p.IsVariadic() {
				continue
			}
			handleType(p.Type)
		}
		handleType(fn.Ret.Type)
	}
	types := make([]string, 0, len(ctypes))
	for typ := range ctypes {
		types = append(types, typ)
	}
	slices.Sort(types)
	for _, typ := range types {
		if isStdType(typ) {
			// Skip standard types.
			continue
		}
		fmt.Fprintf(w, "type %s = C.%s\n", typ, typ)
	}
}

// generateC creates the C source file content.
func generateC(src *mkcgo.Source, w io.Writer) {
	// Header and includes.
	fmt.Fprintf(w, "// Code generated by mkcgo. DO NOT EDIT.\n\n")
	if *includeHeader != "" {
		fmt.Fprintf(w, "#include \"%s\"\n", *includeHeader)
	}
	for _, file := range src.Files {
		fmt.Fprintf(w, "#include %q\n", file)
	}
	fmt.Fprintf(w, "#include <stddef.h>\n")
	fmt.Fprintf(w, "#include <stdlib.h>\n")
	fmt.Fprintf(w, "#include <stdint.h>\n")
	fmt.Fprintf(w, "#include <stdio.h>\n")
	fmt.Fprintf(w, "\n")

	// Platform-specific includes.
	fmt.Fprintf(w, "#ifdef _WIN32\n")
	fmt.Fprintf(w, "#include <windows.h>\n")
	fmt.Fprintf(w, "#define dlsym GetProcAddress\n")
	fmt.Fprintf(w, "#else\n")
	fmt.Fprintf(w, "#include <dlfcn.h>\n")
	fmt.Fprintf(w, "#endif\n\n")

	// Function pointer declarations.
	for _, fn := range src.Funcs {
		if fn.Variadic {
			continue
		}
		fmt.Fprintf(w, "%s (*_g_%s)(%s);\n", fn.Ret.Type, fn.CName, fnToCArgs(fn, false, true))
	}
	fmt.Fprintf(w, "\n")

	fmt.Fprintf(w, "#define __mkcgo__dlsym(name) __mkcgo__dlsym2(name, name)\n\n")

	fmt.Fprintf(w, "#define __mkcgo__dlsym2(cname, importname)								\\\n")
	fmt.Fprintf(w, "\t_g_##cname = (typeof(_g_##cname))dlsym(handle, #importname);			\\\n")
	fmt.Fprintf(w, "\tif (_g_##cname == NULL) {												\\\n")
	fmt.Fprintf(w, "\t\tfprintf(stderr, \"Cannot get required symbol \" #cname \"\\n\");	\\\n")
	fmt.Fprintf(w, "\t\tabort();															\\\n")
	fmt.Fprintf(w, "\t}\n\n")

	// Loader functions for each tag.
	for _, tag := range src.Tags() {
		fmt.Fprintf(w, "void __mkcgoLoad_%s(void* handle) {\n", tag)
		for _, fn := range src.Funcs {
			if fn.Variadic || fn.Tag != tag {
				continue
			}
			if fn.CName == fn.ImportName {
				fmt.Fprintf(w, "\t__mkcgo__dlsym(%s)\n", fn.CName)
			} else {
				fmt.Fprintf(w, "\t__mkcgo__dlsym2(%s, %s)\n", fn.CName, fn.ImportName)
			}
		}
		fmt.Fprintf(w, "}\n\n")
	}

	// Generate C function wrappers.
	for _, fn := range src.Funcs {
		generateCFn(fn, w)
	}
}

// generateGoFn generates Go function f.
func generateGoFn(fn *mkcgo.Func, w io.Writer) {
	fmt.Fprintf(w, "func %s(%s)", fn.GoName, fnToGoParams(fn))
	ret := retToGoParams(fn.Ret)
	if len(ret) > 0 {
		fmt.Fprintf(w, " %s ", ret)
	}
	fmt.Fprintf(w, "{\n")
	fmt.Fprintf(w, "\t")
	if !retIsVoid(fn.Ret) {
		fmt.Fprintf(w, "r0 := ")
	}
	fmt.Fprintf(w, "C.%s(%s)\n", fn.CName, fnToGoArgs(fn))
	if !retIsVoid(fn.Ret) {
		errSrc := retToGoSource(fn.Ret)
		if len(errSrc) > 0 {
			fmt.Fprintf(w, "\t%s\n", errSrc)
		}
		fmt.Fprintf(w, "\treturn\n")
	}
	fmt.Fprintf(w, "}\n\n")
}

func generateCFn(fn *mkcgo.Func, w io.Writer) {
	fmt.Fprintf(w, "%s %s(%s) {\n\t", fn.Ret.Type, fn.CName, fnToCArgs(fn, true, true))
	if fn.Ret.Type != "void" {
		fmt.Fprintf(w, "return ")
	}
	fmt.Fprintf(w, "_g_%s(%s);\n", fn.CName, fnToCArgs(fn, true, false))
	fmt.Fprintf(w, "}\n\n")
}

// paramToGo converts C parameter p to Go parameter.
func paramToGo(p *mkcgo.Param) string {
	goType := cArgToCgo(p.Type)
	switch {
	case goType == "unsafe.Pointer" || goType == "":
		return p.Name
	case goType[0] == '*':
		return fmt.Sprintf("(%s)(unsafe.Pointer(%s))", goType, p.Name)
	}
	return fmt.Sprintf("%s(%s)", goType, p.Name)
}

func isStdType(t string) bool {
	switch t {
	case "int8_t", "uint8_t", "int16_t", "uint16_t", "int32_t", "uint32_t", "int64_t", "uint64_t",
		"int", "unsigned int", "long", "unsigned long", "size_t", "uintptr_t", "char", "unsigned char",
		"void", "unsigned long long", "long long", "signed char":
		return true
	}
	return false
}

// cArgToCgo converts C parameter type t to a cgo type,
// that is, a Go type that can be used in a cgo call.
func cArgToCgo(t string) string {
	t, _ = strings.CutPrefix(t, "const ")
	if t == "void" {
		return ""
	}
	if strings.Contains(t, "void*") {
		return "unsafe.Pointer"
	}
	if strings.HasSuffix(t, "*") {
		// Remove all trailing '*' characters.
		var i, n int
		for i = len(t) - 1; i >= 0; i-- {
			if t[i] != '*' {
				break
			}
			n++
		}
		s := cArgToCgo(t[:i+1])
		if s != "" {
			s = strings.Repeat("*", n) + s
		}
		return s
	}
	// Map C types with spaces to cgo special-cased types.
	if isStdType(t) {
		switch t {
		case "signed char":
			t = "schar"
		case "unsigned char":
			t = "uchar"
		case "unsigned short":
			t = "ushort"
		case "unsigned int":
			t = "uint"
		case "unsigned long":
			t = "ulong"
		case "long long":
			t = "longlong"
		case "unsigned long long":
			t = "ulonglong"
		}
		return "C." + t
	}
	// Non-standard C types are aliased to C.<type>.
	return ""
}

// cTypeToGo converts C type t to a Go type.
func cTypeToGo(t string) string {
	t, _ = strings.CutPrefix(t, "const ")
	if t == "void" {
		return ""
	}
	if strings.HasSuffix(t, "void*") {
		return "unsafe.Pointer"
	}
	if strings.HasSuffix(t, "*") {
		// Remove all trailing '*' characters.
		var i, n int
		for i = len(t) - 1; i >= 0; i-- {
			if t[i] != '*' {
				break
			}
			n++
		}
		s := cTypeToGo(t[:i+1])
		s = strings.Repeat("*", n) + s
		return s
	}
	var s string
	switch t {
	case "int8_t":
		s = "int8"
	case "uint8_t":
		s = "uint8"
	case "int16_t":
		s = "int16"
	case "uint16_t":
		s = "uint16"
	case "int32_t":
		s = "int32"
	case "uint32_t":
		s = "uint32"
	case "int64_t":
		s = "int64"
	case "uint64_t":
		s = "uint64"
	case "int":
		s = "int32"
	case "unsigned int":
		s = "uint32"
	case "long":
		s = "int64"
	case "unsigned long":
		s = "uint64"
	case "size_t":
		s = "int"
	case "uintptr_t":
		s = "uintptr"
	case "char", "unsigned char":
		s = "byte"
	default:
		s = t
	}
	return s
}

// paramToC returns C source code of parameter p.
func paramToC(i int, p *mkcgo.Param, paramNames, paramTypes bool) string {
	var s string
	if paramTypes {
		s += p.Type
	}
	if paramNames && p.Type != "void" {
		if len(s) > 0 {
			s += " "
		}
		s += "_arg" + strconv.Itoa(i)
	}
	return s
}

// retToGoParams returns source code of return parameters.
func retToGoParams(r *mkcgo.Return) string {
	if retIsVoid(r) {
		return ""
	}
	return fmt.Sprintf("(%s %s)", r.Name, cTypeToGo(r.Type))
}

func retIsVoid(r *mkcgo.Return) bool {
	return r.Type == "void"
}

// retToGoSource returns Go source code that sets return parameters.
func retToGoSource(r *mkcgo.Return) string {
	if retIsVoid(r) {
		return ""
	}
	goType := cTypeToGo(r.Type)
	s := ""
	switch {
	case goType[0] == '*':
		s = fmt.Sprintf("%s = (%s)(unsafe.Pointer(r0))", r.Name, goType)
	default:
		s = fmt.Sprintf("%s = %s(r0)", r.Name, goType)
	}
	return s
}

// fnToGoParams returns source code for function f parameters.
func fnToGoParams(fn *mkcgo.Func) string {
	return join(fn.Params, func(p *mkcgo.Param) string {
		if p.IsVariadic() {
			return ""
		}
		return p.Name + " " + cTypeToGo(p.Type)
	}, ", ")
}

// argList returns source code for C parameters for function f.
func fnToGoArgs(fn *mkcgo.Func) string {
	a := make([]string, 0, len(fn.Params))
	for _, p := range fn.Params {
		if p.IsVariadic() {
			continue
		}
		a = append(a, paramToGo(p))
	}
	a = slices.DeleteFunc(a, func(s string) bool {
		return s == ""
	})
	return strings.Join(a, ", ")
}

// fnToCArgs returns source code for C parameters for function f.
func fnToCArgs(fn *mkcgo.Func, paramNames, paramTypes bool) string {
	a := make([]string, 0, len(fn.Params))
	for i, p := range fn.Params {
		if p.IsVariadic() {
			continue
		}
		a = append(a, paramToC(i, p, paramNames, paramTypes))
	}
	a = slices.DeleteFunc(a, func(s string) bool {
		return s == ""
	})
	return strings.Join(a, ", ")
}

// join concatenates parameters ps into a string with sep separator.
// Each parameter is converted into string by applying fn to it
// before conversion.
func join(ps []*mkcgo.Param, fn func(*mkcgo.Param) string, sep string) string {
	if len(ps) == 0 {
		return ""
	}
	a := make([]string, 0, len(ps))
	for _, p := range ps {
		a = append(a, fn(p))
	}
	return strings.Join(a, sep)
}
