on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x]
        openssl-version: [1.0.2, 1.1.0, 1.1.1, 3.0.1]
    runs-on: ubuntu-20.04
    steps:
    - name: Install build tools
      run: sudo apt-get install -y build-essential
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install OpenSSL
      run: sudo sh ./scripts/openssl.sh ${{ matrix.openssl-version }}
    - name: Check headers
      working-directory: ./cmd/checkheader
      run: go run . --ossl-include /usr/local/src/openssl-${{ matrix.openssl-version }}/include -shim ../../openssl/shims.h
    - name: Set OpenSSL config and prove FIPS
      run: |
        sudo cp ./scripts/openssl-3.cnf /usr/local/ssl/openssl.cnf
        go test -v -count 0 ./openssl | grep -q "FIPS enabled: true"
      if: ${{ matrix.openssl-version == '3.0.1' }}
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.openssl-version }}
    - name: Run Test
      # Run each test 10 times so the garbage collector chimes in 
      # and exercises the multiple finalizers we use.
      # This can detect use-after-free and double-free issues.
      run: go test -gcflags=all=-d=checkptr -count 10 -v ./...
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.openssl-version }}
  wintest:
    runs-on: windows-2022
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Test
      run: go test -gcflags=all=-d=checkptr -v ./...
      env:
        GO_OPENSSL_VERSION_OVERRIDE: -1_1-x64
